### ISSUE TITLE
Broken group chat, no participants, cannot leave or write?

### ISSUE THREAD

**Issue by fd0** [WhisperSystems/Signal-Android#1029]
I have a group chat with several other people, including @tyll, all running TextSecure 2.0.4. He sees no group details, the list of participants is empty and he cannot leave or write a message. On his phone, messages to the group are displayed in a group thread and he can decrypt the messages. No group avatar is displayed, the name is 'unknown group'. We both can exchange direct messages just fine.

Maybe this is caused by missing the initial group creation message (all particpants at that time running 2.0.3)? How can users fix this, as there is no possibility to leave this empty group? Only by abandoning that group and creating a new one?

**Comment by bbinoy** [comment]
I had the exact same problem yesterday, with Signal 3.7.2. I'm trying to get many people to use Signal, but this annoyed them a lot. This problem seems to exist for a longer time already, would be great if you could fix this!

**Comment by DooMMasteR** [comment]
Updating the group made it worse for us, anyone who tries it also get's his Group broken.

**Comment by exploide** [comment]
Instead of complaining that this issue hits me as well, I would like to think about possible ways to solve this behavior. Especially the issue when switching to a new phone or just reinstalling. I'm not quite sure whether this issue, #1048 or #5636 is the most appropriate one.

As far as I understand, the server is not aware of the concept of groups, this is only a client thing. That is the reason why it does not work as with WhatsApp or Telegram (groups showing up immediately after registering the same number on a new phone).

While it is not ideal that groups are not present immediately, personally I would be fine when everything works out again after someone sends the first message to a particular group.

Currently this results in an unnamed group with broken UX. Instead of this, the following changes could improve the situation.

- a message of a specific group appears for the first time on the freshly installed client and it notices that it misses the group details
- the client sends a (not yet implemented) group-detail-request to the originator of the group message
- the latter answers with a (unicast?!) group-detail-message so the client can setup the group correctly

I guess this would require a few changes to the protocol but it would fix several issues and enhance the user experience significantly, since nobody has to care about the group mess after a reinstall. Group reestablishment would work silently w/o user interaction and all they have to do is accepting the new key.

**Comment by moxie0** [comment]
@exploide This is the plan. We can eventually combine that with a discovery request so that groups do appear on reinstall.

**Comment by 2-4601** [comment]
Fix in 3.24.0 (cf01959e16acc1ff31cd007d68b3ba43810b6c3a)
