### ISSUE TITLE
Archive

### ISSUE THREAD

**Issue by andypust** [WhisperSystems/Signal-Android#1141]
I see the option of deleting messages and limiting conversation limits in the settings, so I don't know if the practice of regularly deleting messages is a practice in security. But I like to keep an archive of my messages, separate from my "current" messages. I think this is a pretty common feature in most messaging platforms. 

![archive](https://f.cloud.github.com/assets/6936150/2405528/f7775dba-aa52-11e3-9d05-21b7848dfd60.png)

**Comment by manhole11** [comment]
Any update on this?

**Comment by andy11** [comment]
Sorry for dropping out on this. 

I think I can re-implement these changes on the latest branch this weekend.

Two things that are still needed are:
- An image to use as a background image when there is nothing in your inbox
- Icons to use for "Archive" and "Move to inbox"

Can anyone help out with these?

**Comment by agrajaghh** [comment]
For the background image: How about just a gray text saying something like:
> You don't have any messages yet.
> To write a message, click on the "+" in the bottom right corner.

These are the archive and inbox icons from https://github.com/google/material-design-icons/ :

ic_archive_black_48dp.png
![ic_archive_black_48dp](https://cloud.githubusercontent.com/assets/5296073/6091777/97f7c0ea-aebc-11e4-9316-2190296a91f7.png)

ic_inbox_black_48dp
![ic_inbox_black_48dp](https://cloud.githubusercontent.com/assets/5296073/6091778/9a0373e8-aebc-11e4-9e21-016275b04ede.png)

The archive icon looks good to me, but I'm not convinced by the inbox icon. What do you think?

**Comment by andy11** [comment]
In my opinion, I think the "move to inbox" icon would be better with the arrow flipped (up arrow to me implies you're raising the priority which matches what I would typically want when I move something from the archive to the inbox). Flipping the arrow would also make it look more different than the "archive" button (initially I thought both those pictures were for the "archive" action). 

I like the idea of having background text instead of an image when the inbox is empty, so I'll go with that.

Doing merge now, hopefully will have it working again later today.

**Comment by agrajaghh** [comment]
Or what about using the first icon (ic_archive_black_48dp) for both: arrow point down for "putting in archive" and arrow up for "getting out of archive"?

![97f7c0ea-aebc-11e4-9316-2190296a91f7](https://cloud.githubusercontent.com/assets/5296073/6093062/8f2b3392-aef9-11e4-8b0a-53774af0650d.png)

![97f7c0ea-aebc-11e4-9316-2190296a91f7 - kopie](https://cloud.githubusercontent.com/assets/5296073/6093061/8f28ccb0-aef9-11e4-8479-3e3bd7b91bdb.png)

**Comment by andy11** [comment]
That looks great to me!

I think we need to use the white versions of these icons because the background of the action bar is very dark to begin with. I tried the black ones and they were very hard to see.

Could you make a white version of the "move to inbox" icon?

**Comment by agrajaghh** [comment]
Here you go:

![ic_archive_48px](https://cloud.githubusercontent.com/assets/5296073/6093121/aa661fc6-aefb-11e4-9dfd-003144e0f7dc.png)
![ic_archive_arrow_up_48px](https://cloud.githubusercontent.com/assets/5296073/6093122/aa94d780-aefb-11e4-9864-3af1d45b5ec0.png)
since they are white you won't see them probably, open them in a new tab ;) If you need the svg, just tell me...

**Comment by andy11** [comment]
Awesome, thanks :)

Things went well with the merge. I'll post a demo video later today.

**Comment by andy11** [comment]
Ok, here's a video: https://www.dropbox.com/s/o6bz1okfejuumfq/inbox-textsecure.mov?dl=0 (lag is due to emulator -- it runs nicely on my nexus 5)

Code: https://github.com/andy11/TextSecure/tree/ba7381af24a2ef5f1cbc632c5884ecb2aa6c5ee3
Diff: https://github.com/andy11/TextSecure/commit/ba7381af24a2ef5f1cbc632c5884ecb2aa6c5ee3

I decided to hold off on adding the splash text appear when you have an empty inbox for now. I think it looks alright without it (but don't mind adding it if others prefer). 

One part that's not shown in the video is that if you receive a new text or send a new text in an archived conversation, the thread is automatically moved to your inbox.

What do you think? There are probably ways to make my changes in a cleaner way, so just say something if you think it can be done better.

@mcginty: can you take a look?

**Comment by andy11** [comment]
I forgot to add:

A known issue that will need to be fixed is allowing users to upgrade without a reinstall/re-import of messages. I added a field in the database table, which caused a problem for me when I tried upgrading. The video was taken by first uninstalling TS, installing the inbox-enabled version, and then running "Import plaintext backup".

**Comment by agrajaghh** [comment]
Video looks good to me!

I just had a quick look at the code: indent should be 2 spaces, not 4. And there shouln't be any comments in the code.

**Comment by andy11** [comment]
Ok, I've done some cleaning and fixed the crash that was happening on upgrade from a version without the "inbox" column in the "thread" table.

Code: https://github.com/andy11/TextSecure/tree/c2910a2de1f4db2c87736c104526e94642e9f801
Diff: https://github.com/andy11/TextSecure/compare/c2910a2de1f4db2c87736c104526e94642e9f801
Video (unchanged): https://www.dropbox.com/s/o6bz1okfejuumfq/inbox-textsecure.mov

**Comment by agrajaghh** [comment]
You should include the icons in different resolutions (mdpi, hdpi, xhdpi, xxhdpi) and for the light and dark theme. Currently you just got the giant white icons, if I saw it correctly. Just tell me if you need the svg files.

**Comment by andy11** [comment]
Re: sizes -- Ah, ok. Yeah you're right. I used the File -> New -> Image Asset tool to add these latest images (saw it recommended in a SO post). Does this look right to you?

Re: light/dark theme -- Based on where the icons are displayed (title bar w/ dark background), I had been thinking that the white icons should be used for both the dark & light theme. I couldn't see the black version very well when it was the default. Does that seem reasonable?


Code: https://github.com/andy11/TextSecure/tree/6ba81e3db0eb69ad5d9a2ea752177ad24d1cb697
Diff: https://github.com/andy11/TextSecure/compare/6ba81e3db0eb69ad5d9a2ea752177ad24d1cb697
Video (unchanged): https://www.dropbox.com/s/o6bz1okfejuumfq/inbox-textsecure.mov

**Comment by agrajaghh** [comment]
oh sorry, you're right, white is good for both themes, I was confused...

**Comment by McLoo** [comment]
Does this still work with fe5fc411a701bdb1bb3e07e36c7c58fe7adddcb8? As there can be draft only threads now.

**Comment by andy11** [comment]
I just pulled all the latest changes into my branch and it seems to work. 

New video (showing features from fe5fc41): https://www.dropbox.com/s/b2de0kh0i2syiya/inbox-textsecure-2.mov

Code: https://github.com/andy11/TextSecure/tree/6c33a8923aefa8f347716a2bb66223694eb61ef4
Diff: https://github.com/andy11/TextSecure/compare/6c33a8923aefa8f347716a2bb66223694eb61ef4

**Comment by andy11** [comment]
There's something off with the process of deleting a thread with only a draft in it, but it's unrelated to my changes & can be reproduced on the main WhisperSystems/TextSecure branch.

Issue is filed here: https://github.com/WhisperSystems/TextSecure/issues/2473

**Comment by agrajaghh** [comment]
@andy11 I just tried it out, looks good :) I guess next step is to rebase (there were changes to `DatabaseFactory`in the meantime) and create a PR?

**Comment by aesahaettr** [comment]
Any update on this? Looking forward to archiving support.

**Comment by hughbragg** [comment]
Nice idea. How do I look-in/search the archive?

**Comment by moxie0** [comment]
@hughbragg This is an issue tracker not a discussion forum, for support questions please contact support@whispersystems.org thanks!
