### ISSUE TITLE
show message count next to contact name

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#1198]
The stock rom shows the number of messages per thread (user/group).
This is a nice feature and should easily be integrated as the message count is passed to a variable in ConversationListItem.java already.

here my simple example: 
![count](https://f.cloud.github.com/assets/5326916/2448714/acf3230e-aea9-11e3-9567-3c6d5038165d.png)

not the nice light gray smaller number like the stock sms app...

Another wessenger shows the number of unread messages instead which also is a fine feature

**Comment by tatwater** [comment]
+1 to @ykarm for clearly displaying the options and to this thread - I am in favor of the Show total + Show unread + Show drafts option, because it really isn't that much more clutter and I often want to know how many messages I have in given conversations. I'm also very okay with needing to enable this in Settings for it do display if the consensus is that by default it should be cleaner.

I like this information because if my phone is filling up (or if I have some free time and want to clean), I would like to be able to run through my longer threads and choose the messages to delete (also, having a message locking ability would make this process faster).

The default Android Messaging app has the thread count, and I have really appreciated having this info!

**Comment by 2-4601** [comment]
Signal Desktop shows unread counts in the conversation list.

**Comment by moxie0** [comment]
I don't think we're going to add a total count, but unread count is now in 4.13.0
