### ISSUE TITLE
Can't send SMS to numbers with MS Outlook phone number format

### ISSUE THREAD

**Issue by liayn** [WhisperSystems/Signal-Android#1516]
I'm trying out TextSecure for the first time and wanted to send SMS to friends, who's contacts are stored in my exchange account.
The numbers were entered in MS Outlook and are stored in this (year long default) format:
```
+xx (xxx) xxxxxxx
```

The sending of the message fails without giving a reason. (I can text these people with the on-board messaging app and I can call them, so the number is correct.)

After playing around a bit, I noticed that the parentheses seem to be the culprit. Any other Android app silently discards them and dials the number.
I added a new number manually (without parentheses) and things worked out just fine.

Then I changed the number of the aforementioned friend to not contain the parentheses anymore in my address book and tried to re-add him to TextSecure. Unfortunately TextSecure somehow caches the old/other number somewhere and I'm not able to enter his number in any way. Neither by selecting it from the (now updated) address book, nor by entering it manually without any special characters. I guess #791 is related here.

Both problems are real show stoppers for using TextSecure. (I'm not able to update all phone numbers in the corporate phone book ;-))

Device-Specs:
Alcatel One Touch Idol X+ Dual SIM (but just using 1 SIM currently)
Android: 4.2.2

**Comment by rrthomas** [comment]
I have the same problem, specifically with numbers containing parens in my address book (numbers starting with a + work fine, and spaces are OK too).

I have a Fairphone 1U running its latest Android 4.2.2, I'm in the UK on the T-Mobile network. In this case I simply deleted the parens from the relevant contact's number, and that fixed the problem.

**Comment by liayn** [comment]
Closing this issue now, due to lack of response of the dev-team and serious attempts to get this fixed. I lost interest into TextSecure meanwhile anyway.

**Comment by rrthomas** [comment]
@liayn, please can you reopen the issue, and let the developers close it if they decide they definitely won't fix it?

**Comment by liayn** [comment]
1 year is enough grace period. Feel free to open a new issue and reference this one. I want that one off my issue list here in github. thx for understanding.

**Comment by rrthomas** [comment]
@liayn feel free to unsubscribe.

**Comment by liayn** [comment]
Doesn't remove it from my open issue list.

**Comment by rrthomas** [comment]
It seems what you really need, @liayn, is the list of issues you're subscribed to. This doesn't seem to exist in the github UI (see http://stackoverflow.com/questions/25438721/how-can-i-see-all-the-issues-im-watching-on-github ) but you can get a list of all issues you're subscribed to that have had t least one update: https://github.com/notifications?all=1 (IMO, closing an issue just because /you/ lose interest in it is unfortunate, especially when, as here, several other users have both expressed an interest, and given information that might help an interested developer solve it.)

**Comment by liayn** [comment]
Well, the last interaction that happened here from others (except you) was -6 months. That equals NO interest.
If it would be pressing for others, I'd expect here a post frequency of 1 post per day on a user base of > 500.000 installations + a big fat rant. As simple as that.
The information of the people is not lost, as anyone, who has that very problem, is free to open a new issue (which might get some kind of attention if you're lucky) and reference the information here.

**Comment by sseide** [comment]
Sorry - i hope for an fix with every update TextSecure gets (without
getting one by now :-( ). And why should i pollute the bugtracking
system with mails without beeing able to add new informations for this
special case?

Please reopen this case.

Thanks,
Stefan


Am 15.05.2015 um 12:43 schrieb Markus Klein:

**Comment by liayn** [comment]
Because only nagging helps in in open source. The sad truth, even if a company is behind it.
You need to constantly make noise around an issue, in order to stay on top of the lists. Don't expect serious management behind the issue management on github.

You see, nagging me already even brought me to the point to reopen this issue.

**Comment by rrthomas** [comment]
@liayn, as a long-time free software & open source maintainer and contributor, I find nagging demotivating. I don't mind the occasional ping, but unless the person writing has something to offer to a fix, merely reminding me that I don't have infinite time to write software for other people for free does not help. When people make a lot of noise on a bug that is not being fixed fast enough for their taste, that just makes me want to close it "WONTFIX" to get rid of the noise. Volume of original comments is useful as a crude measure of how important an issue is to users; volume of "where's my bug fix???" is just a headache. As a user, having to wade through long bug threads full of noise merely to work out whether there's a workaround and whether it's likely to be fixed is also an annoyance. Using bug trackers that avoid this through barriers to entry, or active curation, is often a relief.

On the other hand, I frequently get notifications of bugs fixed years after I reported them. As a user, it's nice to know. Sometimes, I am able to remove workarounds I installed, and can delete maintenance tasks from my lists. On the other hand, when I report a bug and it is closed simply for lack of developer time or "because it is old" (some bug trackers do this automatically), that is demotivating: I have to engage in pointless activity merely to keep track of the bug; especially when it is a long-term bug that I _can_ work around but would _like_ to be fixed.

A nice thing about computers is that they can store large amounts of information without its becoming a burden. When I used to have a paper address book, backing it up (into a second book) was a chore. Paging through it to find a name and address took time. I would think twice about entering someone into the book: would I need to contact them again? Sometimes, I would get it wrong, and lose an address it turned out I wanted to keep. With an electronic address book, I quickly found I could simply enter every name, address, telephone number &c. I even suspected I might need again. Now I have over 1,000 contacts (more than would fit in my old pocket-book), but I can still find contacts faster than in my old paper book, which never had more than 100 people in it.

I appreciate you may want a "to-do" list of outstanding bugs that you're still interested in. It's a pity that it's not easily available in github, but I've shown you how to get a list of bugs you're subscribed to that have had activity. Maybe you could file a github issue on that? (Github itself is not open source, of course.)

I'm sorry that you feel nagged, I, earlier, thought I was having a conversation trying to persuade you to reopen the issue. Similarly @sseide made a polite request. Neither of us made repeated requests.

**Comment by liayn** [comment]
@rrthomas I'm also VERY involved in Open Source Software and I'm doing quite a lot of work with bug reports (of course with serious software and not with github; but don't get me started on that), but with one big difference to what happens here: If I start taking care of a ticket, I take responsibility and stick to it. In this issue only one person was responding (I'm not even knowing if he is from the dev-team or not) with questions for logs, which I provided + a lot more information. Since then dead silence.

I fully see your points from the dev's perspective, and we created way too many unrelated comments here already. This is again a sign for creating a new duplicate ticket, which holds fresh logs of current versions and is clean. The advantage of computers is that you may reference this issue as a "historic log".
But there is another big difference in this very issue: It is a total usage blocker!
So I'd say a product manager would take such an issue serious, which again is not happening here.

Don't get me wrong, I'm not angry on both of you in any way, I just don't understand, why you want me, as the original reporter, to keep a ticket open, that I can't/will not take care of anymore. Meaning, I'll not provide any more information in case a dev comes around and needs info. That is the worst thing you can experience as dev, having an unresponsive reporter! That's the reason I'm officially stepping back of my "reporter role" here. (Sorry for the dev guy who needs to find this out in 10 years that I wrote this in the middle of a long text.)

**Comment by sseide** [comment]
Now i found some time to clone and settup Textsecure and dig into the code. My phone does not like round brackets in phone numbers - removing them allows the sms to be send as mentioned in the comment from rrthomas on 25.03. 

This can easily tested with the simple example app (with easy modifications) provided in issue 3099 mentioned above.
As the issue 3099 contains an lengthy discussion about things people may try to send messages too i did not used the PhoneNumberUtil.stripSeparators() function which works too and just removed the brackets from the recipients number. Email recipients should be fine with this too...

Attached the fix https://github.com/WhisperSystems/TextSecure/commit/7b70cdffb0ed91db17adee3b4c75326979a2ee45 as pull request.

Hope this long standing bug will be fixed very soon officially...

**Comment by agrajaghh** [comment]
should have been fixed with https://github.com/WhisperSystems/Signal-Android/commit/e808ae0ddcece26d93f097b23d85febc62c7757f
