### ISSUE TITLE
Per contact settings storage

### ISSUE THREAD

**Issue by NOPDev** [WhisperSystems/Signal-Android#1977]
@moxie0 It seems that a per contact user setting storage may be a good idea for the future, as feature implementations such as per contact notification sounds continue to be implemented. Rather than see this fragmented across many different type specific databases it would seem creating a generic db for this task may be desirable. Would you agree?

I have made some modifications that would require this type of storage as well for implementing a MRU (most recently used) transit type for messages instead of automatically defaulting to Push. But before creating yet another database in the factory I wanted get your opinion on the matter.

**Comment by rhodey** [comment]
related to #354

**Comment by FeuRenard** [comment]
In my opinion this issue is solved by https://github.com/WhisperSystems/Signal-Android/commit/40af2a81dbe43ec89fcfea88d33b52814074d90f which introduced [`RecipientPreferenceDatabase`](https://github.com/WhisperSystems/Signal-Android/blob/0619a4d3cd2ce170119cc538f5d8e2e056524685/src/org/thoughtcrime/securesms/database/RecipientPreferenceDatabase.java).
