### ISSUE TITLE
Problems with delivery of messages, receipts

### ISSUE THREAD

**Issue by Deccoy** [WhisperSystems/Signal-Android#2238]
Hey,

I've some screenshots for invalid message or receipt handling:

(1) Message is delivered before sent (Message was delivered successfully)

![1](https://cloud.githubusercontent.com/assets/6777199/5495353/2ce992a6-86fd-11e4-8e89-2f1e377d77f7.png)

![2](https://cloud.githubusercontent.com/assets/6777199/5495355/32af45be-86fd-11e4-92ac-0abe7183e795.png)

(2) Messages are sent, but never delivered (12:35 messages are still not delivered...) 

![3](https://cloud.githubusercontent.com/assets/6777199/5495377/635c5026-86fd-11e4-8720-15fbf6f0da87.png)

(3) Messages are delivered, but receipt is missing

My Phone (Message 11:08 pm has no receipt...)

![4](https://cloud.githubusercontent.com/assets/6777199/5495415/c94116ec-86fd-11e4-98b7-05ff5da5ca1f.png)

Receivers Phone (... but the message is delivered)

![5](https://cloud.githubusercontent.com/assets/6777199/5495423/df2d649c-86fd-11e4-9a8a-b372a0708c2f.png)

We both have the same phone (Android 5.0 vs 4.4), both latest Text Secure Version. The internet connection here is sometimes a bit bad, maybe the internal routine for network problems is a bit buggy?

Let me know if I can help with futher information.

Best regards

**Comment by midi** [comment]
experiencing the same issues.

i know that when i change the phone number, messages can get lost or it will get difficult to start a new conversation, even after "ending the secure session".

also i had changed a google account, which resulted in messages not getting delivered to me, but was able to send.

all this also happens when i don't change the setup, out of the blue. it's really difficult to trust textsecure as main and only messenger.
and it's proving to be equally difficult to trouble shoot for contacts.
if it worked reliably, textsecure would be really amazing.

**Comment by devurandom** [comment]
Copying my issue description from #2293:

> Currently message delivery is unreliable. It often happens that I send a message to someone, but do not get a message receipt (check-mark icon). Messages sent later get a receipt. When I talk to the person a few hours later, they tell me they did not receive the message.
>
> This issue is not limited to me sending, but also happens the other way around. It also happens for other people, as I have been told. It also happens for the message receipts themselves – sometimes a message arrives on my phone, but the sender never receives the receipt. The CyanogenMod integrated WhisperPush service is not involved. The issue happens between stock Android users, as well as with CyanogenMod users.
>
> From reading other issues I understand that GCM does not offer reliable delivery. I wonder if the equivalent of XEP-0198 section 4 "Acks" could be implemented on top of it in TextSecure.
>
> Possible duplicates: #679, #970, #1971, #2098, #2238

**Comment by pjstorm** [comment]
We can confirm selective non-functionality of GCM-based "push" receipt notification for folks who are connected through our secure network (https://cryptostorm.is) on Android-based devices. Our dev team is just beginning to look into this - our initial hypothesis is that the transport-level characteristics of GCM are not happy with our SNATted network session topology, basically.

On the flipside, it may be useful to use this behaviour as an inverse test-case for the more general drops of GCM-based message deliver confirmation: we can tune our network to selectively adjust just about every transit metric, and indeed we can set up dedicated test instances to do iterative test mode work on this problem.

All that said, we're most specifically focussed on enabling GCM transit for our network members on Android-based devices. On the surface, this doesn't seem a particularly challenging task given the fairly simple nature of the CGM framework itself.

**Comment by Mihahn** [comment]
The problem still exists and for the last 2 days I was unable to communicate using TextSecure as approximately only 1/4 messages was delivered, so it was unusable...

**Comment by janvlug** [comment]
I searched for more information about GCM reliability.
I found the following information:
Some developer information for keeping push messages work reliable:
https://blog.pushbullet.com/2014/02/12/keeping-google-cloud-messaging-for-android-working-reliably-techincal-post/
Delayed push notifications causes (from a Google developer):
https://productforums.google.com/forum/#!search/gcm/nexus/fslYqYrULto/lU2D3Qe1mugJ
A app that should remedy the problem (I did not test it yet):
https://play.google.com/store/apps/details?id=com.andqlimax.pushfixer.noroot

**Comment by janvlug** [comment]
Actually, I was also wondering what the time_to_live (see: http://developer.android.com/google/gcm/ccs.html#receipts&sref=https://delicious.com/janvlug/search/gcm) is for TextSecure push messages. Can someone direct me where in the code I can find this?

**Comment by peterpanondrugs** [comment]
the message has been trasmitted to the server, but when my parnter is offline (no wifi/mobile internet,...) he (often) doesnt get the messages at all. 
same with receipt marks, sometimes. they dont show up, despite the message was send & received.

**Comment by gordon-morehouse** [comment]
I'm adding my information, gathered over months of usage with multiple users on multiple carriers and Android versions, following conversation in #1583.

I'm running the latest TS update on an old version of Android. Although the messages do eventually arrive (which wasn't the case a few months ago, thanks for that), they're often acknowledged by TextSecure as having been sent, but **receivers receive them with delays ranging from none to hours.**

This may or may not depend on the receiver's phone state:

1. I've been in active conversations with TS users and suddenly the delay appears: confirmations stop coming in. I've been switching to SMS in this case which does seem to work, just as it's announced that SMS transport will be removed.
2. Other times, I may know out of band that the user's phone is charging or otherwise hasn't been used recently and may thus be in some kind of sleep state, and the delay will appear (more often than when I'm sure their phone is active) or not appear (less often).
3. Messages are queued by TextSecure in some fashion and generally when the receiver receives them, they receive them all within a span of seconds. Rarely, receivers may get a bunch of messages but not the last one or two, then shortly after, get the last one or two - as told by confirmation checkboxes.
4. I have experienced receipt of many delayed TextSecure messages instantaneously for no apparent reason when my phone was inactive or active but not using TextSecure.
5. I have experienced receipt of many or single delayed TextSecure messages upon opening the app.

This behavior is, to the best of my knowledge (own use and quizzing friends), fairly consistent across carriers - verified on Sprint, Verizon and T-Mobile.

This behavior is consistent on at least devices running Gingerbread and KitKat.

This behavior is consistent on devices with 512MB to 2GB of RAM.

It appears that this may require some waiting for the issue and debug logging, but I don't know how to accomplish that. Additional complication: receiver may also need to debug log?

**Comment by moxie0** [comment]
@gordon-morehouse At this point experience from anything older than a week is not really relevant any longer.

**Comment by gordon-morehouse** [comment]
...except that it's still happening, as of yesterday - and yes, I received an automatic update several days back.

**Comment by moxie0** [comment]
Whatever is "still happening" is relevant, but information you've gathered "over months of usage" is not. You'll need to clarify exactly what it is you're still experiencing.

**Comment by gordon-morehouse** [comment]
Okay, see you in a few days.

**Comment by devurandom** [comment]
What happened to me yesterday: Someone sent me a few TS messages over the course of several minutes. They notify me about this 10-15 minutes later via XMPP. I open TS and suddenly receive all those messages at once.

**Comment by bvorak** [comment]
That happened to me lately as well, should I file a new issue for that as soon as I can gather a debug log on it?

**Comment by devurandom** [comment]
TBH: For me it is quite ok to receive messages a few minutes later, as long as they are delivered at all and it does not become more than "a few minutes" (say 15). And I am even glad that I receive them in a "digest", which I can answer in one go.

**Comment by moxie0** [comment]
@devurandom Check out #2703. Following the instructions there would be helfpul.

**Comment by gordon-morehouse** [comment]
Delays of hours, suddenly happening in the middle of an active conversation, have been rough for me with multiple friends on multiple carriers for a couple days. Dunno if anything changed in the latest update. I will try to get logs if it keeps happening by coordinating by SMS or phone.

**Comment by midi** [comment]
Had this happen recently as well. Don't understand it, was moving sometimes, but definitely was staying in a place with good connection for a while when I suddenly received a message, dating back one day or so.

**Comment by ortylp** [comment]
Message delivery is definitely unreliable.  All network and GCM service permissions, battery optimisations and whatever there is to be enabled/disabled to give Signal and GCM highest priority is set, but messages are sometimes delivered, sometimes not.
Example: sender on WLAN, receiver on GSM, it works, sender on WLAN, receiver on WLAN, does not work... 

And please let GCM Free version to be available from F-Droid...

**Comment by Deccoy** [comment]
Fixed, thanks!
