### ISSUE TITLE
"Error sending message" if group member uninstalls TextSecure

### ISSUE THREAD

**Issue by rmueller83** [WhisperSystems/Signal-Android#2408]
In a group chat, a member removed TextSecure or unregistered from the service.
Since then, all messages yield to "Error sending message" although the other remaining group members receive the messages successfully.
I also did not find a way to remove that member from the group.

In the log I get these exceptions:
W/TextSecureMessageSender( 3082): org.whispersystems.textsecure.api.push.exceptions.UnregisteredUserException: org.whispersystems.textsecure.api.push.exceptions.NotFoundException: Not found
W/TextSecureMessageSender( 3082): at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:148)
W/TextSecureMessageSender( 3082): at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:177)
W/TextSecureMessageSender( 3082): at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:156)
W/TextSecureMessageSender( 3082): at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:99)
W/TextSecureMessageSender( 3082): at org.thoughtcrime.securesms.jobs.PushGroupSendJob.deliver(PushGroupSendJob.java:138)
W/TextSecureMessageSender( 3082): at org.thoughtcrime.securesms.jobs.PushGroupSendJob.onSend(PushGroupSendJob.java:74)
W/TextSecureMessageSender( 3082): at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:38)
W/TextSecureMessageSender( 3082): at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/TextSecureMessageSender( 3082): at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:72)
W/TextSecureMessageSender( 3082): at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/TextSecureMessageSender( 3082): Caused by: org.whispersystems.textsecure.api.push.exceptions.NotFoundException: Not found
W/TextSecureMessageSender( 3082): at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeBaseRequest(PushServiceSocket.java:447)
W/TextSecureMessageSender( 3082): at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:410)
W/TextSecureMessageSender( 3082): at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:146)
W/TextSecureMessageSender( 3082): ... 9 more

**Comment by onny** [comment]
Yep I also experienced this issue

**Comment by TWfromSWD** [comment]
Had this problem too. Found no other way to solve this than deleting the group and starting a new one.

**Comment by shaaati** [comment]
Today I had to fight a very similar issue. A friend of mine got a new phone and caused trouble in two medium-sized groups (10 to 15 people). Everyone got the "Error sending message", together with an "unknown identity" information every time they tried to send a message to the group.

The only way to resolve the issue was to create a new test group and selectively invite people one after another. This way I was able to figure out the person making the problems.
After that it still took a while for her to react and until then, communication in the groups was practically impossible.

I don't really know how to resolve the issue. TS was not *wrong* by definition because there really was one person with an unknown key that did not correctly receive the messages.
However, this lead to some of my friends arguing whether they should change to another messenger with less problems. I feel that group communication should work more robust for a better user experience.

Two ideas:
* Fail silently if the majority of the group gets the message (don't know whether this is feasible).
* **(rather a work around)** Allow group creators to delete people from the group. In this case it would probably be helpful to implement some kind of *group moderators* with deletion rights, in case a group creator itself causes the problem or is unavailable for a longer time.

**Comment by RealMabuse** [comment]
That's a problem that should be solved. We had that problem yesterday because one group member bought a new phone and another one's had been out of order. And now we have two people less using Textsecure, because they were annoyed by all those key exchange messages and those error messages...

**Comment by mcginty** [comment]
Things will get better in the next release with improved key conflict management.

**Comment by jeremymasters** [comment]
@mcginty excited for each new release, like any voracious end-user. :)

**Comment by aurisnoctis** [comment]
@mcginty Wonderful - can't wait!

At the moment people think messages don't arrive at anyone's phone anymore and switch to WhatsApp until I explain to just ignore the error and trust they nonetheless arrive while I try to find who caused the problem this time. Without me as an "admin" people would have changed back to WhatsApp altogether.

Solutions:
- smaller less colorful information that x members have not received the message, even better - who - then it would be easier to ignore, though also not a long-term solution
- +1 for simple solution from @shaaati : creator can delete people

We have a group of colleagues with a moderate exchange rate of users, fortunately. Still it is annoying simple non-committed (to privacy) members that just want a messenger. To create, move to, and delete groups regularly even though the majority of people in that group stay the same is difficult to justify.

I am curious how the new version will manage this!

**Comment by Jens14L** [comment]
More functions for groups (remove members, multiple admins, description/status, …) would be really nice.

**Comment by mcginty** [comment]
@Jens14L please keep comments relevant and helpful to the issue, that's unrelated.

**Comment by manhole11** [comment]
When a member of the group unregisters from textsecure, the error I get now is "Some issues need your attention". A list of the users is displayed and you can do nothing. Same issues, different error messages...

**Comment by gladiac** [comment]
Ping! This is really an annoying issue with groups ...

**Comment by gladiac** [comment]
Ping!

**Comment by moxie0** [comment]
@gladiac Do this again and we'll ban you from the OWS repos.

**Comment by tylerstyle** [comment]
I've got the same Problem since I switched to my new Phone two days ago.

Everyone in the Group gets an error message stating a delivery Problem though everyone gets the messages correctly.
And that on the latest Signal Version (3.5 and Beta-3.6).
Deleting and adding People to Groups should definitely be an option.

I even wrote every single one of the Members private Chats as to trigger the key exchange to no avail.

Only option would be to delete the Group and start anew which is not a viable Option, every time someone switches their Provider or Handset.
Given a fairly large group this would amount to being forced to delete and recreate Groups on a regular basis.

**Comment by mawed** [comment]
As far as I know you can update a group which solves the problem with new keys. To do so, someone has to delete you and put you to the group again. You can do this in the group-conversation via menuebutton -> update group

**Comment by tylerstyle** [comment]
There is no way to delete Members, that I could find.
At least not on Android.

**Comment by mawed** [comment]
Oh sorry, than a normal readd works maybe?

I can choose people already in the group. This should update the group and solve the problem.

**Comment by tylerstyle** [comment]
That readds a person to the group but after that the Problem starts and
every person sending a message gets the error.

**Comment by mawed** [comment]
I thought your problem could be the same as here: #2581.

**Comment by ivilata** [comment]
In case this is still useful, this is the flow I observed:

  1. 4 people in the same group, working ok.
  2. 1 person reinstalls Signal (iOS).
  3. Whenever another person sends a message to the group, the message is flagged with "Some issues need your attention". Selecting it shows that the one that left is not validated. The message is received 5 times by the other members.
  4. This last person validates the problematic contact.  Now the message he sends are received normally by the others.
  5. As other people revalidate the problematic contact, their messages stop getting duplicated.

My log shows nothing relevant about the issue.  I'm using LibreSignal 3.12.0, but others are using the official Signal app.  I'll add more info as soon as I have it.

**Comment by tx3eh8IUD1** [comment]
I still encounter this (or at least a similar) issue. Why is the thread closed?

The following happened:
User de-registers from signal and uninstalls. 
No one seems to be able to delete the number from the group. 
Group members receive error when sending messages (started only about a week after the user left signal).

**Comment by haffenloher** [comment]
> Group members receive error when sending messages

Which version of the Signal client do they use? What is the error message? Please capture a debug log after the error happens and post it here.

**Comment by tx3eh8IUD1** [comment]
Sorry, @haffenloher for the lack of detail. By looking closer at the problem I realize that I should post my problems to the signal desktop github. I only encounter issues on my android "by proxy":

On my android signal client (3.15.2) all works fine with the group when I send messages using my phone. 

For my signal desktop (0.11.0) I get two errors for every message I send: "Message not sent. ResendMessage not sent. Resend" (sic!) and the small red circle with a "!". 
![signal-desktop](https://cloud.githubusercontent.com/assets/6958661/15171879/1e6ce6ba-1752-11e6-99d6-04dcbbc3a152.png)

This happens whenever I send a message and started about a week after a member de-registering signal and uninstalling the app (without leaving the group). 
For message sent via the desktop client, my signal android only shows one "check mark" (for successful send), and it lacks the second check mark (for successful retrieval of the message). However, no error message appears.

**Comment by shaaati** [comment]
I am experiencing exactly the same issue.
A while ago I filed https://github.com/WhisperSystems/Signal-Desktop/issues/448. Since then the symptoms have changed (the non-existing number no longer shows up as being the problem source, instead both Android and Desktop behave exactly like yours), but the issue itself still persists.

**Comment by haffenloher** [comment]
> By looking closer at the problem I realize that I should post my problems to the signal desktop github.

Yep :) Signal Desktop doesn't use your phone as a proxy, it works on its own, so this probably doesn't have much to do with the Android client.

> For message sent via the desktop client, my signal android only shows one "check mark" (for successful send), and it lacks the second check mark (for successful retrieval of the message).

Yeah, delivery receipts for *group* messages sent via desktop aren't processed by the android client (if they arrive before the outgoing sync message, I think). I thought there was an open issue for this, but I can't seem to find it.

**Comment by 2-4601** [comment]
> I thought there was an open issue for this, but I can't seem to find it.

#4924

**Comment by Sur3** [comment]
Hi i deregistered the old number in signal and registered a new number, but the old number is still listed in groups, i think the old number should be replaced by the new number in groups or at least be removed from all groups so that a new foreign registrar of my old number can't read my old groups!
