### ISSUE TITLE
Language selection should ask for confirmation before changing to selected language.

### ISSUE THREAD

**Issue by git12a** [WhisperSystems/Signal-Android#2476]
Presently, when one selects a language from the list inside Language settings, it just directly switches to that language. Imagine the panic on the mind of normal average user when he sees a language he accidentally tapped on (and don't know it) and wants to revert to previous (or English) language. 

It should ask "do you want to switch to LanguageName?"

**Comment by DustinLim** [comment]
I feel that changing the theme/language is jarring because the app immediately returns you to the main settings screen. Returning to the language picker can be challenging, in case you selected the wrong one.

Asking confirmation might be overkill, however keeping the user on the appearance screen would help a lot.
