### ISSUE TITLE
Play store screenshot needs update

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/Signal-Android#2711]
the one with the green logo 

And maybe the one with the image ~~view~~ bubble.

**Comment by jtracey** [comment]
Maybe the banner too, at the top of the page in the play store app.

**Comment by moxie0** [comment]
hook me up with some screenshots and i'll put them up there

**Comment by McLoo** [comment]
No more password screenshot to update. Closing...

Though I would suggests to add a dark theme screenshot, convo list

**Comment by Lokesh-Krishna** [comment]
To begin with, could this screenshot showing off a Signal call be added?
I'll also try to get more screenshots showing off the changes since the last batch was added, importantly the change in the name.
![connected android call two words](https://cloud.githubusercontent.com/assets/20235646/20780413/c6569a12-b7a0-11e6-8463-6d7e225e02c2.png)

**Comment by nrizzio** [comment]
This issue can be closed because both the app icon and the screenshots have been updated since a long time ago. :fireworks:
