### ISSUE TITLE
No option to force-ignore someone's textsecure account

### ISSUE THREAD

**Issue by rigaac** [WhisperSystems/Signal-Android#274]
From the "Manage Identity Keys" screen there is no way to remove a key

**Comment by black-puppydog** [comment]
After looking at some similar (mostly locked/closed) issues this one seems to be the best I can comment on as a non-collaborator.

I have had this happen to with friends a couple of times.
I tell them about TS, they try it, maybe even like it, then someone in a "clique" stops using it and suddenly everyone uninstalls.
The reason is quite simply that always having to remember to long-press is annoying enough for them to uninstall it entirely.
And no, there is absolutely no way that I will make them lift a single finger on their part to "properly unregister".

I think that is the problem here: Once someone decides to not use TS any longer, that's it. We cannot reasonably expect them to re-register and/or go through a complete unregister after they decided they don't care about the app.
And to be quite honest: I love TS for many reasons, even compiled my own from a feature branch I wanted badly, but even I find myself wondering if it is really worth the trouble for exactly this reason.
It is like an inverse network effect. :/

**Comment by Diapolo** [comment]
I also have problems with contacts who uninstalled Signal but still show up in my list as Signal users. There is no way to force them to be NO Signal users, so I always have to manually switch to insecure SMS... this is a big UX mess! :-/

**Comment by FeuRenard** [comment]
This issue would be solved by implementing #2285, right?
So this is some kind of duplicate.

**Comment by 2-4601** [comment]
Lot's of old TextSecure specific discussion here and two-issues-in-one syndrome. Closing in favour of #2285 and #4678.
