### ISSUE TITLE
emoji flags missing from drawer

### ISSUE THREAD

**Issue by oorittole** [WhisperSystems/Signal-Android#3316]
The 10 flags (JP US FR DE IT GB ES RU CN KR) that where present in emoji_3_wrapped.png are no more in emoji-3.png / emoji-places.png (TS ≥2.16.3).

Many many thanks for your excellent work! Keep going!

**Comment by mcginty** [comment]
Thanks for the report @oorittole - I noticed this too and am looking into adding back those (and hopefully more flags too). It looks like the set I imported from stores flags in a separate spot.

**Comment by jeremymasters** [comment]
When I would try to use the flags before, they never showed up in my message even though they indicated they had been pressed.

**Comment by wp9015362** [comment]
> @mcginty wrote:
> 
> It looks like the set I imported from stores flags in a separate spot.

The source for the Google "Noto Color Emoji" Emoji set seems to be over there:

SVGs:
https://code.google.com/p/noto/source/browse/?name=master#git%2Fcolor_emoji%2Fsvg

PNGs:
https://code.google.com/p/noto/source/browse/?name=master#git%2Fcolor_emoji%2Fpng%2F128

Regards

**Comment by mcginty** [comment]
@wp9015362 that's the repo i'm talking about, there aren't any flags in that folder.

**Comment by wp9015362** [comment]
> @mcginty wrote:
> 
> @wp9015362 that's the repo i'm talking about, there aren't any flags in that folder.

Wrong.

Let's take the flag for the United States for example:

https://noto.googlecode.com/git-history/master/color_emoji/svg/emoji_u1f1fa_1f1f8.svg

According to the Unicode Emoji Chart Index, see:

http://www.unicode.org/emoji/charts/full-emoji-list.html

the code(s) for the United States flag for example are U+1F1FA and U+1F1F8.

If you look at those alone you get just a separate "U":

https://noto.googlecode.com/git-history/master/color_emoji/svg/emoji_u1f1fa.svg

and a separate "S":

https://noto.googlecode.com/git-history/master/color_emoji/svg/emoji_u1f1f8.svg

But if you combine them in the file name like this:

emoji_u1f1fa_1f1f8.svg

then you get the flag, see:

https://noto.googlecode.com/git-history/master/color_emoji/svg/emoji_u1f1fa_1f1f8.svg

Regards

**Comment by mcginty** [comment]
What I mean is it's not in the png folder and I haven't looked their batch svg rendering setup yet. I understand how the emoji work, thanks.

**Comment by wp9015362** [comment]
> @mcginty wrote:
> 
> What I mean is it's not in the png folder and I haven't looked their batch svg rendering setup yet. I understand how the emoji work, thanks.

Can't you just use the SVGs directly in TextSecure?

Maybe that would also solve the low resolution issue:

https://github.com/WhisperSystems/TextSecure/issues/3318

?

Anyway:

Can't you just switch to the open source "Emoji One" Emoji set:

http://emojione.com/
https://github.com/Ranks/emojione

The "Emoji One" Emoji set looks a heck of a lot better than the Google "Noto Color Emoji" Emoji set IMHO.

And it looks much more similar to the Apple set, which in turn would result in a much better interoperability with Signal-OS.

And the Emoji One devs even already said that they will release a Unicode 7.0 update soon, see:

https://github.com/Ranks/emojione/issues/68#issuecomment-93861096
https://github.com/Ranks/emojione/issues/68#issuecomment-93880415
https://github.com/Ranks/emojione/issues/105#issuecomment-106951709

So, why am I mentioning this here?

Because Emoji One has flags for pretty much all countries in the world, see:

http://emojione.com/blog/weve-added-emoji-flags-entire-world/

And they even have them available as PNGs, see for example:

https://github.com/Ranks/emojione/blob/master/assets/png/1F1FA-1F1F8.png

So, it would be much appreciated if you could switch to Emoji One.

Regards

**Comment by moxie0** [comment]
f7474362ff8bc75fff70ed75a1caad31fd55374e
