### ISSUE TITLE
Notification sound incorrectly plays when viewing a conversation from recipient

### ISSUE THREAD

**Issue by Spakman** [WhisperSystems/Signal-Android#3337]
With my Nexus 6 (Android 5.1) on priority mode TextSecure does not play notification sounds. This is correct.

However, with my phone set up as above, if I send a message to someone and remain viewing that conversation, TextSecure will incorrectly play the notification sound if that person replies to me.

**Comment by rhodey** [comment]
I'm able to reproduce this on my Nexus 5 running Android 5.1 & TextSecure 2.16.3, steps to reproduce.

1) enable Settings > Notifications > In-thread notifications
2) press the volume up hardware key to bring up the notification widget thing
3) turn volume up all the way so you won't miss the sound
4) tap the star for priority, set to indefinitely
5) open a conversation with person A
6) receive message form person A
7) notice the message notification sound plays

note: the phone does not vibrate in this case even if it is enabled within settings.

**Comment by rhodey** [comment]
a commenter in [this issue](https://code.google.com/p/android/issues/detail?id=80031) on the android bug tracker concluded on February 15th of this year that `It's currently impossible to detect "priority" mode or reliably set the phone's mode to "none" or "priority".`

I've spent sometime searching and can't find any information disputing this. the root of this bug is the "In-thread notifications" setting, as implemented [here](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/notifications/MessageNotifier.java#L296).

**Comment by whatchanged** [comment]
This issue still exists on Signal 3.6.1 on Android 5.1.1. I have an LG Nexus 4 device with T-Mobile USA as the carrier.
