### ISSUE TITLE
block typing if max length exceeded

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/Signal-Android#3362]
When typing a really long message, textsecure used to block the typing when I reached the max length limit. It just happened to me that I exceeded that limit (without noticing) and sent a message that was automatically trimmed while being sent. Please notify the user that the message will be trimmed, or prevent the typing in the first place.
Don't know in which version this problem arose

**Comment by oaim** [comment]
I'm working on a fix

**Comment by McLoo** [comment]
This can easily be reproduce with pasting rather than typing. Paste 3000, get -1000 left and free typing, until something happens to min integer being -2^31 😁

![screenshot_2015-06-26-22-43-43](https://cloud.githubusercontent.com/assets/5326916/8387355/24c3102a-1c58-11e5-8f4b-b704d209a544.png)

*why can't I figure out such  things on a slot machine or cash dispenser? *

**Comment by ehartsuyker** [comment]
If anyone's watching this thread, I have a partial fix [here](https://github.com/WhisperSystems/TextSecure/issues/3658) and could use some help from a better Android dev.

**Comment by agrajaghh** [comment]
closing in favor of #5146
