### ISSUE TITLE
messaged received while in muted thread not marked as read

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/Signal-Android#3562]
1) start a new thread with A
2) send some messages back and forth
3) mute A
4) receive message from A while in thread with A
5) back out to conversation list
6) notice that conversation with A is shown as unread

**Comment by Dyras** [comment]
This happens for me when I'm the one sending the message. If I write something and then I back out of the conversation until the app closes, I can actually see my own message as unread.

Should I make my own issue for that?

**Comment by ChaoticMind** [comment]
@Dyras yes, and it would be good to put the steps clearly, as the top post did.

**Comment by Fanch3n** [comment]
I'm not quite sure if I have the same issue, but it is at least very similar.
When I write to myself, then return to the conversation list and open a different conversation, my last message will be shown as unread. Also happens when using quick reply.

(By the way, debug logs don't seem to work for me - I just get the first 6 lines, which is device/app information, but there is no actual log. Did I miss something or is that a bug?)

**Comment by ChaoticMind** [comment]
@Fanch3n Are you running Android 2.3? According to [this](https://github.com/WhisperSystems/TextSecure/issues/3723#issuecomment-122651978) comment, that version doesn't generate proper logs and you'll need to use adb instead.
But I think your bug is reproducible so you don't need a debug log for it. Unsure if #3643 also solves this variation of the bug.
