### ISSUE TITLE
Turning encryption on/off only possible after you write something

### ISSUE THREAD

**Issue by ComeGitSome** [WhisperSystems/Signal-Android#3689]
Long press on paperclip does nothing. Should allow switching between TextSecure and unencrypted sms so it works like long press on send icon.

**Comment by Dyras** [comment]
Honestly I don't see the problem with how it works now.

**Comment by ComeGitSome** [comment]
I'd say it's related to #3639 in a way. It's not obvious how to send unencrypted messages so people try to use "end secure session". It doesn't make any sense that you would have to start writing something before being able to turn encryption on/off, that should be possible before you start writing the message.

**Comment by JasonLocklin** [comment]
Hiding functionality behind long press means most people will never find it. It does no harm being there for advanced users, but that functionality needs to be available in a more intuitive way. This should be labeled a ux issue (and is complementary to #3639).

The primary reason for a user to need to send an insecure SMS to another textsecure user is when one or both users has no data service (e.g., because it was turned off by accident, roaming, or cellular network failure). Users have an expectation (from SMS) that messages will always be delivered nearly immediately, unless notified otherwise about an error. When this expectation is violated, they will blame textsecure.

**Current situation:** User needs to know what the checkmark icons mean and monitor them to identify if there was a problem sending the message. If the message is urgent, the user needs to know that if it doesn't go through in a reasonable time, they need to re-type the message in the text-entry field, long-press on the send button, and chose send_insecure_SMS.

**Better situation:** User sends the message. If it doesn't go though in, say 30 seconds, the user is notified of the problem and given the option to wait or re-send the message as SMS if it's urgent. 

Case 1: No data (i.e., ... icon):
>    Unable to send message. Is data turned off? Will try again in 30 seconds, or if it's urgent, send as _insecure_SMS_.

Case 2: Unable to reach contact (i.e., single checkmark icon):
>   Recipient appears to be offline and will receive the message immediately after reconnecting. If it's urgent, the message can be sent as an _insecure_SMS_

(_insecure_SMS_ is clickable and re-sends as SMS).

**Comment by agrajaghh** [comment]
fixed
