### ISSUE TITLE
textsecure contacts do not auto update on receiving a message from a newly registered TS who is in your contact list

### ISSUE THREAD

**Issue by heyimgay** [WhisperSystems/Signal-Android#3949]
it requires a manual refresh of the contact list (with the not so obvious pull to refresh mechanism)

**Comment by real-or-random** [comment]
I can confirm this. I had the same issue yesterday.

**Comment by SchubSchub** [comment]
Are you using Textsecure or Signal. Pull to refresh didn't work with my Textsecure... Could you tell me in detail how to refresh the contact list in TS?
Thanks!

**Comment by real-or-random** [comment]
It's when TextSecure shows you the contacts to add to the group (with the checkboxes on the right.) Then you can pull downwards to refresh. A progress spinner will show up to confirm the refresh.

**Comment by gordon-morehouse** [comment]
I am having this problem with a new Signal user. That particular pull-to-refresh does not work for me on the latest TextSecure on Android 2.3.4. (Sorry, I know.)

**Comment by SchubSchub** [comment]
It doesn't work for me either. There is no spinner showing up.
I am using TS 2.25.3  on a Samsung GT-S7562 with Android 4.0.4
I tested a little bit an guess that it is only updating automatically about once a day. 
(maybe the same with RedPhone as explained here: http://support.whispersystems.org/customer/portal/questions/13037535-how-to-resync-contacts-after-friends-have-signed-up-for-red-phone- )
To manually refresh the list I had to unregister and reregister my phone number through the settings menu. It was OK because it didn't change anything and I was still connected to my group chats afterwards.

**Comment by jaylinski** [comment]
same here, please fix.

**Comment by KuenzelIT** [comment]
I had to go look here to find out how to refresh my contact list. This really is not very obvious. I liked it more by using the menu and press "refresh my contacts". At least there should be a documentation somewhere.

**Comment by peter-greskovic** [comment]
I can confirm this. New user (has not been in my phone book before he installed TS/Android/current) does not appear in my list of textsecure users even after several days. One of my other TS contacts can see him as TS user though (phone number was checked and is correct).

**Comment by Pesebrero** [comment]
Could you tell where are you from and which carrier are you using?

I'm from Argentina, using Tuenti (Movistar). I have this issue: https://github.com/WhisperSystems/Signal-Android/issues/4378. And perhaps this is also related: https://github.com/WhisperSystems/Signal-Android/issues/1511

**Comment by moxie0** [comment]
in 3.4.0
