### ISSUE TITLE
Cannot share photos from Google Photos

### ISSUE THREAD

**Issue by legovini** [WhisperSystems/Signal-Android#3989]
I have a Nexus 6 with stock android 5.1.1, the problem is always reproducible. The steps are:

1. Take a photo with the phone camera;
2. Go to the Photos app, open the image and "share it to TextSecure";
3. TextSecure opens. Chose a recipient. The image appears in the conversation;
4. Press "send". The message disappears, nothing is sent.

Here is the debug log:

https://gist.github.com/anonymous/32aae2e2352b96d4bf40

The initial logged crash is probably not related to this, but to another issue that I'm going to report right after this.

**Comment by 2-4601** [comment]
Sounds like #3307.
Cannot reproduce with Nexus 4, TS 2.25.3, Photos app 1.3.0.101074912

**Comment by legovini** [comment]
You're right, it's probably the same issue. But there you wrote that you can reproduce it...
I'm using the same software versions as you.

**Comment by 2-4601** [comment]
I could reproduce it at that time but it was fixed and has been working for me since.

**Comment by legovini** [comment]
I had it crash again, and this time I think the crash *is* related to this issue. When trying to share an image I ended up with the "broken image" thumbnail on TextSecure, and when I tried to send it TS crashed. Not sure about what I did differently.

https://gist.github.com/anonymous/da059f1d7f3e7018a259

**Comment by 2-4601** [comment]
Uhhh... for some reason the sharing does not work for me any more. Every picture I now share with Photos vanishes and produces the content provider permission error ([log](https://gist.github.com/anonymous/e1e5e35328f1795fbe8c))
Unsure what triggered it. Yesterday it worked. Since then I have booted my phone but there hasn't been any updates to the Photos app. The first time I noticed this was with a screenshot that I edited (cropped) with the Photos in-app editor.

**Comment by hoechenberger** [comment]
I am experiencing the same problem (message disappears) on Android 5.1.1 running on a Nexus 5.

**Comment by mcginty** [comment]
This is only happening with the Photos app, correct?

**Comment by hoechenberger** [comment]
I've only tested with the Photos app so far.

**Comment by legovini** [comment]
I can't say if it happens *only* with the Photos app, but I tried another couple of apps and it didn't happen. For example I tried sharing an image from a file manager: it worked fine.

**Comment by mangei** [comment]
I have the same problem with my Nexus 5, Android 5.1.1. I also used the Photos app from Google and it did not work. With QuickPic i.e. it works fine.

**Comment by shaaati** [comment]
I can reproduce this error with the Photos app from Google, as well as with "Secrecy", an app to encrypt files on your phone. Tested on Android 5.1.1, Nexus 5.

**Comment by avtechmjc** [comment]
Same problem, can not send photos from Photos using TextSecure...

**Comment by Hooloovoo** [comment]
Me too, debug log: https://gist.github.com/5bed4503c2ade877a64c 
Signal 3.0.1 beta

**Comment by mcginty** [comment]
Root cause is due to us not dealing with temporary intent-specific URI permissions properly. As it turns out, the temporary permissions to a URI passed in expire after the activity that receives the intent finishes. Since ShareActivity receives the intent and finishes once it opens ConversationActivity, we lose.
