### ISSUE TITLE
Non TS Mms failing to download

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/Signal-Android#4067]
Non TS mms failed to download and seemed to prevent other non TS mms downloading as well. Rebooting the phone seemed to fix it as all the mms then came through. 
https://gist.github.com/6d2c9f390b2c3836bb09

**Comment by mcginty** [comment]
The logs show that it's just sitting there in the connecting phase (no timestamps in the logs, unfortunately, so don't know how long it was sitting there). There are no exceptions from a timeout or otherwise, though. Can you wait until the MMS fails (as in says it failed to download or the download button re-appears) and re-capture a log?

**Comment by jeremymasters** [comment]
I can do that again next time it happens.  Rebooting the phone seemed to fix this particular case.

**Comment by mcginty** [comment]
Oh, MMS, you are so weird.
