### ISSUE TITLE
Duplicate SMS Contacts

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/Signal-Android#4191]
I noticed today that I have some contacts twice in my list but only there. Not TS/Signal contacts but those for sending SMS.

The pattern is the same, a number which I stored formated like +49 171 7654321 is visible like this and as +491717654321. I only could see cell phone number affected.

And I can't see a pattern which contacts are affected and which are not.

**Comment by bartz1** [comment]
What textsecure version are you using? If you're running an older version than 2.28, could you try updating?

**Comment by tehabe** [comment]
The most current one from the Play Store 2.28.1, I actually noticed it when I tried Signal 3.0.0 and assumed at first it was a regression but found it also in the 2.28.1.

**Comment by tdashton** [comment]
Bump, I have the same issue, just downloaded from the store: 2.28.1 running on Cyanogenmod 4.2.2 API 17. When I click the new message bubble most contacts are duplicated in the list, maybe an issue with the formatting of the numbers (w/ or without spaces as above).

**Comment by tehabe** [comment]
@tdashton is right, only contacts which also use WhatsApp are effected. I hope this is fixed soon, also Signal 3.1.1 is affected.

**Comment by g0hl1n** [comment]
Same problem for me: WhatsApp contacts are displayed twice. One time with spaces in the phone number, one time without.

I'm using Singal 3.1.1 on Android 5.1.1!

**Comment by agrajaghh** [comment]
I can confirm this on a Nexus 4 (5.1.1) with Signal 3.3.0

Its ofc just happening when SMS are enabled in Signal, thats why I didn't notice before...

**Comment by RiseT** [comment]
Observation & silly question: It looks like everyone experiencing this issue (including myself) in this thread is from Germany. Any false positives...? :smile:

**Comment by RiseT** [comment]
My stats: Nexus 5, Android 6, Signal 3.3.0, Location Germany

**Comment by RiseT** [comment]
@tehabe Would you mind changing the issue's title as this is not Marshmallow-specific (this issue exists - at least - on Lollipop as well)?

**Comment by RiseT** [comment]
@mcginty Really don't intent to push, but could you please give this bug a slightly higher priority? The thing is that those experiencing it do so on pretty much a daily basis and for a rather long time (much longer than this GitHub issue entry exists). This bug is a bit unnerving, as it increases number of contact entries within the contact list considerably and thus it takes one much longer to scroll through it and find a searched for entry. Thanks in advance!

**Comment by bartz1** [comment]
we're not all from germany

**Comment by RiseT** [comment]
@bartz1 So you are having this issue as well (it's not clear from your prior post above)?

**Comment by bartz1** [comment]
Yes I have had this issues since forever :dancer:

**Comment by tehabe** [comment]
@bartz1 I did not say this limited to Germany, currently most people seem to believe it has something to do with WhatsApp and how it presents itself in the contacts, and with WhatsApp gone so are duplicates, so the idea might be true.

**Comment by RiseT** [comment]
@tehabe I said that and @bartz1 was referencing my post. It seemed to me that everyone posting in this thread is from Germany. Obviously not true. But it definitely seems WhatsApp related.

**Comment by tehabe** [comment]
@RiseT too bad we can't solve this by convincing everybody to switch to Signal. (I know people who use Windows or Blackberry)

**Comment by MT76** [comment]
New Signal user here. Issue still exists. I too can confirm these duplicate contacts are all Whatsapp-linked contacts. 
I would love to see my friends on Signal, but i know most of them are not tech-savvy and will burn Signal because of this. Please try to fix this issue. If you need any more info or logs from me, please let me know.

**Comment by moxie0** [comment]
I think this must be an Android bug, since our contacts query is asking for uniques.  I can't reproduce this on any devices I have, so as a first step someone would need to figure out why this is happening and in what conditions.

**Comment by RiseT** [comment]
I have this issue on a Nexus 5/Android 6.01 and a Nexus 4/Android 5.1.1 (the Nexus 5 got stolen a couple of days ago 😠 , so I cannot report on that anymore. Tomorrow I'll be getting a Nexus 5X).

**Comment by RiseT** [comment]
Let's summarize what I know about this issue so far.

**This happens only with...**
- non-Signal contacts...
- who have WhatsApp installed...
- if you, the Signal user, have WhatsApp installed as well.

**Displayed phone number formats**
- Android's address book: +49 123 1234567
- Signal's address book: +49 123 1234567 AND +491231234567 (= duplicate)

**Phone number formats of linked accounts within Android's address book**
- Signal call: +49 123 1234576
- Signal message: +49 123 1234576
- WhatsApp call: +49 123 1234576
- WhatsApp message: +49 123 1234576

**Comment by MT76** [comment]
Also, the initial contact list shows duplicates, but when you search for a contact (type the name) you will see only 1 entry.

**Comment by Mnyromyr** [comment]
I cannot fully confirm RiseT's summary.
I've two phones here, both tied to German providers, but only one shows this issue.
Neither of the phones has (or had) any WhatsApp installation.
(1) The affected phone is a Samsung Galaxy SIII mini running Android 4.2.2.
The old contact entries are phone/SMS contacts in the format +49123123123 or 0123123123 and have names attached to them. The entries are stored on the SIM.
The new entries are for (and created by?) Signal. They're shown as 0123123123 and you cannot attach any names to them, nor can you merge them with their actual phone contact equivalences.
(2) The unaffected phone is a Galaxy S7 running Android 6.0.1. Phone contacts are usually in format +49123123123 and may be stored on SIM or memory.
New Signal entries appear inside the already existing contacts, as expected.

**Comment by redstwice** [comment]
I have the same problem. I am using google pixel xl and Android 7.1.1. I am also using telegram whose contact list doesn't seem to clash with signal's.

**Comment by LewisGauss** [comment]
I am still facing similar issue on the latest Signal beta, running on android 7.1.1.

**Comment by novationbe** [comment]
I just installed Signal for the fist time on android 7.1.1 on my Nexus 6p. The issue is also happening here.
Never had whatsapp installed.

**Comment by AndHell** [comment]
As you the in the screenshot, this seems to happens for numbers that are stored with whitespaces or other non-numeric chars in it e.g. +49 (123) 123465 or +49 123 123465, and that are also in WhatsApp.
Numbers in that format that are not in WhatsApp are not affected. Changing the number to +49123123456 removes the duplicated entry. After uninstalling WhatsApp, the numbers also appear only once.

My guess is that WhatsApp adds an entry in +49123123456 (android displays them with whitespaces), and therefore we get two entries for the same number.

Without WhatsApp installed I was not able to reproduce the bug.

A manual workaround would be to change every number in the contacts to the +49123123456 format.

I don't know if it’s possible to filter out WhatsApp numbers when reading the numbers from the Android system, otherwise transforming the numbers to the +49123123456 format and search for duplicated entries in the list should work, too. But I haven't tried it out yet.

![screenshot_20170324-141911](https://cloud.githubusercontent.com/assets/11991279/24296417/548361f6-109f-11e7-83ba-9de72c80bbca.png)

**Comment by RiseT** [comment]
I can confirm that the issue disappeared after uninstalling WhatsApp.

**Comment by KevinAT** [comment]
@AndHell can confirm, going through all my contacts one by one and removing all the spaces in the numbers seems to have fixed the issue. though as others have said the problem also exists for people who don't have whatsapp installed. could it be that there are other apps besides whatsapp that cause this issue?

and what should be done to get rid of this problem for everyone? either signal should get an option to ignore duplicate numbers with different formating, that is enabled by default. or signal should ask the user if it can convert the space-numbers to non-space-numbers every time it detects one.

**Comment by joshtriplett** [comment]
This issue still seems to exist in Signal 4.14.10, the latest beta on Android. Many of my Signal conversations appeared to be with phone numbers with no associated contact. Editing the corresponding person's contact and fiddling with the phone number seems to get Signal to recognize it as the same contact.

In the Contacts app, at the bottom of my "All Contacts" list, I have many pseudo-contacts that just show phone numbers, with no names, corresponding to these same people.
