### ISSUE TITLE
Alert user to call ending

### ISSUE THREAD

**Issue by jtracey** [WhisperSystems/Signal-Android#4319]
Sometimes, when I'm using Signal to speak with someone, the call will drop unexpectedly. While I expect this to happen sometimes, right now Signal doesn't provide any indication that it has happened (other than the fact it's no longer running). It would be nice if, before shutting down, it played some tone to make it more obvious.

**Comment by bartz1** [comment]
Happens to me all the time. Conversation closes but I can't know so I keep talking.

**Comment by WhiteHatTux** [comment]
I looked at this previously in redphone and solved it by using the same way a user is notified of a busy line (which is actually how it is done in general telephone matters).
The commit, which did it was: https://github.com/WhiteHatTux/RedPhone/commit/9cc12de10e3467bddc68725607aa12aa4a5c33a8 and should be at least similar to what has to be done now. Sadly i can't apply it to Signal and test because i am having other issues with calling. :-/

**Comment by bartz1** [comment]
This is marked as 3.5. 3.5 has been released but this is still open... ?

**Comment by JoeyFR** [comment]
Please merge this :)
This talking alone issue is very impacting

**Comment by 2-4601** [comment]
Fixed in webRTC https://github.com/WhisperSystems/Signal-Android/pull/5358#issuecomment-281237258
