### ISSUE TITLE
allow direct sharing to contacts via 6.0 ChooserTargetService

### ISSUE THREAD

**Issue by mcginty** [WhisperSystems/Signal-Android#4333]
https://developer.android.com/reference/android/service/chooser/ChooserTargetService.html

**Comment by emmaguy** [comment]
Hi - I really miss this feature from Signal - if I were to implement it and create a PR, would it be accepted?

**Comment by Hanzei** [comment]
@emmaguy I would a love this feature in Signal. It would be great, if you would implement it!

**Comment by riyapenn** [comment]
Please refrain posting "+1" "me too" "I would a love this feature" "same" etc. as a comment without any NEW or actionable information.  The emoji in the comment header allows you to "add your reaction" if you want to express your interest in the feature/comment.

**Comment by cavega** [comment]
What is the status of this issue (feature request)? I checked the most recent pull requests and it doesn't seem someone is working on it. Does it need approval before anyone can work on it and submit a PR? @emmaguy asked the question but no one answered. I wouldn't mind working on a PR for this feature.

**Comment by jeremymasters** [comment]
@cavega I think you can always work on a PR.  Mainly it would probably depend on if @moxie0 feels there are any security issues with this direction or if it's valuable.  My $0.02 is that it would be pretty handy.

**Comment by cavega** [comment]
@jeremymasters Thanks for the response. 

This feature doesn't expose any app information. It would still use the existing Intent mechanism that current allows to send content from 3rd party apps into Signal.  Its primary usage would be to share info from 3rd party apps into the Signal app by bypassing 1 UX interaction. 

Instead of:

- Click share from 3rd party app
- Select Signal app from options
- Select desired contact

It becomes: 

- Click share from 3rd party app
- Select desired Signal contact (Note: Some of the most recent Signal contacts become available, but user can still select Signal app, through existing flow, to pick other contact to send data to).

**Comment by Lokesh-Krishna** [comment]
@cavega In that case a PR would definitely be received favourably. Make sure you tag someone to review it so that it doesn't go unnoticed.
