### ISSUE TITLE
aade4c7 degrades call quality

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/Signal-Android#4382]
3.3.0 branch with 0e291a9509bb364b7595b88dae452df7c714ed7a as the latest commit.
- The call quality is noticeably worse after this commit (I tested several times switching between another 3.3.0 build up to cbc851bdaf9c33a3fa271ec1f668085373b08cf9 and the quality degrade is consistent)
- When I adjust volume during a call there is a bluetooth icon in the overlay volume toast instead of the normal phone icon:

![bt](https://cloud.githubusercontent.com/assets/174176/10951507/93cd10ba-8346-11e5-807b-fc5dae06adcc.png)

Huawei U8800, Android 4.0.4

**Comment by moxie0** [comment]
thanks @2-4601 can you describe in what ways the quality is worse?

**Comment by 2-4601** [comment]
My English vocabulary for describing the quality of a sound is not that great but there is cracking and if I sing a note there a very short but noticeable stops every now and then.
Without this commit there are no such issues. Singing the note sounds continuous all the time and there is no cracking or other noise.

**Comment by moxie0** [comment]
@2-4601 hmm i just tried signing to myself and it was fine on my device. What if you try signing to yourself via a WhatsApp voip call?

**Comment by 2-4601** [comment]
I don't have WhatsApp ;,,(
But singing sounds fine on Signal before this commit.
I guess we need more people to test if this affects only my crappy Huawei device or if it concerns other devices too.

**Comment by jeremymasters** [comment]
Just imagining you guys singing to yourselves on the phone, lol.

**Comment by moxie0** [comment]
@2-4601 when you're singing to yourself, are the two devices in the same room? it's possible this change kicks in some hardware-level echo cancellation, so the best test would be between two devices in separate rooms

**Comment by 2-4601** [comment]
No, they were in different rooms because I was standing at a doorway. My left hand (Nexus 4) was in a different room than my right hand (Huawei).
Sorry, bad joke, really bad joke :see_no_evil: 

I tested now by putting on the news. Left Nexus 4 near the TV speaker and called to my Huawei device. Then I went to the toilet, closed the door and answered. Sound quality was still as bad as before.
Then I tested the above scenario again with a previous build (i.e. without the low volume fix commit) and the sound quality was good.

**Comment by 2-4601** [comment]
I don't get where the bluetooth icon comes to the volume adjustment toast?
@moxie0 Do you have a bluetooth icon or a regular phone icon? Previous builds did not have this bluetooth icon. For the record, I don't have a bluetooth headset, never used them with this device and bluetooth has always been turned off.

**Comment by 5boro** [comment]
I've had the bluetooth icon bug since 3.0.3, I don't think it's related.

**Comment by Dyras** [comment]
Yeah I had that bluetooth icon thing for a while too. If I were to attempt to compile my own build of Signal then I'm afraid the world as we know it might come to an end, so I'll just sit here and patiently wait for a couple of days until the next beta.

**Comment by moxie0** [comment]
@2-4601 You can try again with 595bb08e2bfc521086fc3e7f52446e8483911157 but it's a long shot.

I tested with WhatsApp and a few other VoIP apps, and they also show the bluetooth volume thing. Not sure what's up with that.  If you could install WhatsApp and test the VoIP quality on that phone, it would help to know whether we're doing something particularly wrong or if there's a problem with supporting that device.

**Comment by 2-4601** [comment]
Unfortunately 595bb08e2bfc521086fc3e7f52446e8483911157 didn't help with the sound quality.

I can test with WhatsApp but I can't do it now. I have to go away for the next 16 hours.

One last thing... the bluetooth volume icon switches back to a phone icon after I tap the speaker on and off. :no_mouth:

**Comment by Joshfindit** [comment]
The symptoms described (cracking, and short stops every now again on sustained sound) sound like textbook redlining.

I've worked with symptoms like those hundreds of times (especially during the alsa days, but even on osx, ios, and RasPi). It usually comes down to one of the volumes in the chain being set to "max", which distorts the audio, then the user controls the volume on something further down the chain. (the quotes are a whole different rant about software volume levels and db)

This is just a theory based on previous experience.

**Comment by 2-4601** [comment]
Sorry, I'm unable to register with WhatsApp:
_"+1 (616) XXX-XXXX is not a valid mobile number for the country: United States"_ :crying_cat_face: 
That number worked fine when I just registered with Signal. I also tried another number but got the same error message. I will try to find some other VoIP app to test.

@Joshfindit That's interesting. Another way to describe the low quality would be to say that someone plays the voice so loud that it distorts and then records it and plays it again at a lower volume.

**Comment by 2-4601** [comment]
Tested with _LinPhone_ [1, 2]. Sound quality is as good as with Signal without the low volume fix commit.

[1] Android app: https://play.google.com/store/apps/details?id=org.linphone
[2] Source: https://www.linphone.org/technical-corner/linphone/downloads

**Comment by 2-4601** [comment]
Bad quality persists with Huawei (3.3.0 final).
Also bad quality voice on my Nexus 4, stock 5.1.1, final 3.3.0 release. The volume level is also too low which made it hard to recognize the bad quality at first.

**Comment by 5boro** [comment]
A friend reported the same behavior to me, and he's on a Huawei device as well.

**Comment by Safari77** [comment]
Would your problems be solved when #4359 is fixed?
Compared to csipsimple with opus codec, Signal voice quality is very poor and muddy.
Also, Signal could tell what codec (and bitrate) is being used.

**Comment by 2-4601** [comment]
@Safari77 This was more about a single commit that degraded call quality (for some devices). Before that commit the call quality was good even with the current codec.

**Comment by 2-4601** [comment]
> I will test tomorrow with other devices to rule out the crappiness factors of my Huawei device.

Testing a call between iPhone 4S, iOS 9.1, Signal 2.1.3 and Nexus 4, stock 5.1.1, Signal 3.1.1:
- there's also the issue with continuous sounds stopping intermittently (but now I'm convinced it has more to do with echo cancellation or the codec)
- call quality is otherwise quite ok

Conclusion: The commit did have a noticeable negative effect on call quality on my Huawei device. But hopefully it's just isolated to that. I will keep this issue open for a while after 3.3.x has been released on Play Store. If there are no other cases I will close this.

@5boro Which device does your friend have? Which version of Signal? How did your friend describe the call quality?

**Comment by AlfonsoMuskedunder** [comment]
This is wild guessing, and I haven't read the commits' code, but could it be that the low volume bug and the one leading to entirely corrupted calls (see https://github.com/WhisperSystems/Signal-Android/issues/4409) are related? In other words, could https://github.com/WhisperSystems/Signal-Android/commit/56a3c992891cbe5179521037afca9bb7327e7e99 solve the low volume problem along the way, making https://github.com/WhisperSystems/Signal-Android/commit/0e291a9509bb364b7595b88dae452df7c714ed7a superfluous, or could there be some other interaction?

I'm asking because when I suffered from apparently dead speakers and mics in some calls (see https://github.com/WhisperSystems/Signal-Android/issues/4267, perhaps the same as https://github.com/WhisperSystems/Signal-Android/issues/4409), the recipient would sometimes hear me very silently, so both problems were there at the same time.

**Comment by Dyras** [comment]
I can subscribe to "there's also the issue with continuous sounds stopping intermittently (but now I'm convinced it has more to do with echo cancellation or the codec)" happening. Not really sure what to say about it though. It's irritating? I've always thought it's because of my friend's shitty connection.

Galaxy nexus -> Galaxy S5 works just fine for me now. It's not quiet for me at all anymore.

**Comment by Norbert80** [comment]
I experience low volume (both hands-free talking enabled and disabled) and very poor quality.

Found with Signal 3.3.1 on Samsung Galaxy Note 4 device.

The competing open source app
https://www.simlar.org/en/
is louder and clearer on the same network conditions.

**Comment by Norbert80** [comment]
German c't magazine has tested Signal for Android. While praising the message part the are not very happy with the VoIP part.

- Usable, but...
- disconnections
- and poor quality.
- Not suited to replace conventional callings (due to this issues) but could be used to place a call on problematic topics.

http://www.heise.de/security/meldung/Edward-Snowdens-Messenger-TextSecure-und-RedPhone-sind-jetzt-Signal-2868645.html

**Comment by Dyras** [comment]
I don't think they tested the beta version though, did they?

**Comment by Norbert80** [comment]
@Dyras: There is no build number in their text. Nevertheless since the initial release I think there has been no QUALITY related patch. I only know of a VOLUME related patch that seems to have no effect on my device.

It would have been better if Whisper Systems would have integrated Simlar* instead of Redphone. Simlar is is way ahead of Signal's Redphone-based VoIP implementation.

* https://www.simlar.org/en/

**Comment by moxie0** [comment]
@Norbert80 This is not a discussion forum or a place to post links to random articles.  Please only comment on issues if you have specific information that is necessary for resolving the issue.  Every time you post here, you're sending all OWS developers an email, so please respect our time.

**Comment by Norbert80** [comment]
@moxie: I hope that looking at Simlar source codes could help in solving issues.

**Comment by motatuc** [comment]
I have to add that the problem still exists for me with cm12.1 from 20.11.2015 and signal from today. I still have the bluetooth symbol after placing a call with signal. I then cannot adjust volume anymore. So for me it is not fixed. 

Phone is S4 Mini.

**Comment by vuyibiran** [comment]
Hello. Still have the bluetooth symbol problem described in the first post.
Tried with Signal 3.5.2 and 3.6

Using htc one m7 and CM12.1

**Comment by bbinoy** [comment]
Me too I have the problem of the bluetooth symbol, along with a very low volume. I first thought it didn't work at all because I couldn't hear anything. Would be great if that could be fixed soon.

Also the call quality is not as good as for example WhatsApp voice call. It's possible to understand each other without problem, but it sounds not very clear, as if there were some noise added. Maye generally a higher volume would improve this already.

Using Fairphone with Android 4.2 and Signal 3.6.1.

**Comment by 2-4601** [comment]
For everyone reporting on this issue from now on:
Please test two builds:
1. master at 58406d6b37008af668d9e362daa652dad7ba025b
2. master at aade4c7af331fa7263b156e3b7a145f07ce85b46

Do you recognize a noticeable drop in **call quality** between 1 and 2?
This is the original point of this issue. Otherwise please post on the other issues. Thanks.

**Comment by halb9** [comment]
Test Nr. 1:

Phone: 		Samsung Galaxy S3 (GT-i9305)
Firmware: 	Stock Rom
Android:	v. 4.4.4


Phone: 		Samsung Galaxy S5 (SM-G900F)
Firmware: 	Cyanogenmod "cm-13.0-20160721-NIGHTLY-klte"
Android: 	v. 6.0.1


Test Environment: 

I've got Signal v. 3.16.0 on both phones. 

I initiate the signal-call from either the S3 or S5. The call is established. 

Whatever I say into the S5 comes out with very low volume on the S3. 
The other way around is fine. 
This only happens on a signal-call. Not with regular GSM calls. 

The provided debug logs were created right after the call is terminated. 

S5: https://gist.github.com/anonymous/461ae7efc92df0aecb05241344082062

S3: https://gist.github.com/anonymous/56ee2fbdf588f8d604f6baadf37fa662

I remember I had this problem with the same S3 phone a few months ago. At that time it was as well running Cyanogenmod. 

I will get another S3 in a few days and will do a comparison between the stock version and the CM version. 

If you want me to test something in the meantime, I'll do my best.
