### ISSUE TITLE
Texts to premium numbers such as charities don't work

### ISSUE THREAD

**Issue by sabret00the** [WhisperSystems/Signal-Android#4453]
You probably know of things like charities using numbers such as 85474 (made up number) to donate. Attempting to send a text to such a number from Signal results in the country code being added, so from where I live, it became +4485474 and thus failed.

**Comment by johanw666** [comment]
That was a known issue with SMSSecure, applying https://github.com/SMSSecure/SMSSecure/commit/d77fddd7e2f818251c9c95f196372888eaa9a86c might help.

**Comment by haffenloher** [comment]
@johanw666: I think whitespace tagging has been removed a long time ago, so that commit is about a separate, older problem.
It's not that the content of the SMS isn't being recognized by the receiver (due to trailing whitespace), it's the sending of the message that fails, because Signal tries to send to the wrong number.

**Comment by dcherian** [comment]
After https://github.com/WhisperSystems/Signal-Android/commit/21f04605c68a2e157cfe0da4e5a480635842f5ec, this should be closed too?

**Comment by mcginty** [comment]
yep, thanks
