### ISSUE TITLE
Make the "pull down contact list to refresh" mechanism discoverable

### ISSUE THREAD

**Issue by blinry** [WhisperSystems/Signal-Android#4470]
I think it's highly non-obvious that you can pull down the contact list to refresh it. After I understood this mechanism, I've had to explain it to every single person I introduced to Signal.

This mechanism should be made discoverable in the UI. For example, you could add a note to the top of the contact list that says something like "Pull down to refresh". It would disappear after the user does that once.

**Comment by jwittlincohen** [comment]
I would also like to see this.  I found it frustrating when helping new users to setup Signal because we were unable to use the software for messaging or secure calls for several hours, until it automatically refreshed.  The ability to pull down the contact list is not obvious, and there is no visible indicator or menu option to refresh the contact list.  I actually came on Github to discover if there was a way to manually refresh.  

I think this is an important issue because the long delay to update the contact list can result in a negative experienced immediately after the software is installed, potentially causing the user to abandon the software.  Users will expect to be reachable and to reach others that have just installed the software as this is their experience from using WhatsApp, Hangouts, iMessage etc.

Here are a few examples of real problems I ran into because of the lack of an obvious means of refreshing the contact list:

Failing to refresh the contact list can lead to an inconsistent state which is bewildering to users.  For example, after registering Signal on my girlfriend's phone, she could send encrypted messages to me and call me, but I did not even see her as a contact.  After she sent a single message, I was able to send encrypted messages and verify her key fingerprint.  Yet, she still did not show up as a Signal contact (I believe this is fixed in a recent commit but I'm on 3.1.1 - the lastest version on Google Play). However, even several hours later, I could not initiate a secure call despite being able to receive one.  Manually refreshing the contact list fixed this issue.

In another instance, after a user upgraded from Redphone to Signal, he was able to continue contacting me on Redphone but I could not call him for several hours until my contact list updated.  

In yet another instance, messages I sent a user were rendered unreadable because he had re-registered his phone number but my phone had not refreshed the contact list, so it continued to encrypt messages using his prior key.

In each of these instances, a simple and obvious means of refreshing the contact list would have avoided the problem behavior.

**Comment by Viperized** [comment]
I agree with this. Had a similar issue when all numbers in my region had a new added number, and I re-registered my number with Signal. However who had me previously with the old number now couldn't reach me. In one stance I needed to step by step painfully explain the steps for a manual refresh.

Even though I knew the procedure from some faq/tutorial I found on the website, it was still hard to assist the person and guide them to the new message and then pull down to refresh.

I don't know how other apps do it and the different architectures involved, but I'm sure Signal dev wizards will automagically find a way!
