### ISSUE TITLE
UX: Hide Grayed-out group conversation settings

### ISSUE THREAD

**Issue by mawed** [WhisperSystems/Signal-Android#4505]
![img_20151112_222304](https://cloud.githubusercontent.com/assets/11197868/11132413/1d51be5e-8990-11e5-93f2-830a06ebbabe.JPG)

I have a group, where the color for the conversation is shown, but not choosable because it's shown grayed.
Also the part Verify identity and block are shown, but not choosable.

If this is intended, why not hide the options.

Signal 3.3.1

**Comment by haffenloher** [comment]
Groups don't have their own color. You can change each member's color in their respective one-on-one conversation.
Maybe these grayed-out options should not be shown for groups at all.

**Comment by mawed** [comment]
The last two options should be hide as they do not work in group conversations.
But why shouldn't the color be choosable? 
Is there any reason for that?

**Comment by generalmanager** [comment]
@mawed Because the color indicates the sender of a certain message. In a group there are only messages by individual contacts, not by the group itself. Thus you should be able to choose the message color for individuals, but not for groups.

I agree with @haffenloher that the greyed out options should just be hidden/omitted from a UI experience. Otherwise users get the impression that they have to fulfill certain requirements to unlock those greyed out settings, when they can't do anything to change them.

**Comment by mawed** [comment]
@generalmanager Yeah the color of the messageboxes are choosen by the individual chats.

Only thing could be to choose the titlebar. But Hiding the options would also be ok to me.
