### ISSUE TITLE
Encrypted call not available.

### ISSUE THREAD

**Issue by JasperWeiss** [WhisperSystems/Signal-Android#4514]
My friend previously used a fork of signal and I told him to get the official version from the playstore.
Yet, while we both have the official signal from the playstore (Latest version). The encrypted call option is not available.
The option is available for other contacts so I guess the problem is on his end. What could be the problem?

**Comment by billie80** [comment]
I have a similar issue here. Encrypted call is only an option for some contacts using Signal. There seems to be a pattern however. It is available for German (+49) contacts but not for Austrian (+43) contacts.

**Comment by AlfonsoMuskedunder** [comment]
@JasperWeiss It's not uncommon that newly registered users don't appear immediately as Signal users. You and your friend might want to update the contacts list by tapping the 'compose message' button so that the user list appears; then swipe downwards. Usually that's it.

**Comment by moxie0** [comment]
Using multiple different signal clients can fuck things up. I'd recommend you contact support@whispersystems.org for help resolving any conflicts.

**Comment by billie80** [comment]
This is not the case here. Should I open a new issue or also contact the support?

**Comment by JasperWeiss** [comment]
@moxie0 as I said we both got the official app, but the problem seems to have resolved itself.
Both of us cleared app data and registered again after which it worked fine.

Not sure about about @billie80 though

**Comment by mpetri** [comment]
also having the same issue. both users have been using textsecure on android to chat securely for a while. after the upgrade to signal the "secure call" function is not available (secure chat still works).

**Comment by lrq3000** [comment]
I had the exact same issue and fixed it by forcing the secure call. Then the secure call was offered by default for my contact. I am not sure what was the culprit, maybe it was because the contact's number I registered in my phone didn't have the international prefix (which is by default prepended when registering to Signal's servers when first launching it).

How to force a secure call? By showing the contact's card, new Signal entries will be displayed (to access the contact card from Signal, open the discussion thread, then click at the top on the contact's name, then click on the bubble at the left of the contact name at the top, and now you should see the contact's card and you should see an entry "Signal Call XXXXXX").
