### ISSUE TITLE
Improve error handling if a member of a signal group unregisters

### ISSUE THREAD

**Issue by generalmanager** [WhisperSystems/Signal-Android#4550]
When creating a group with one or more contacts which aren't registered with Signal, there is a very clear notification that an MMS group will be created, which could lead to additional costs.

Current experience:
When someone unregisteres from Signal while s/he is part of a group, the other group members receive error messages saying the message couldn't be sent, even tough it is in fact sent to the remaining members of the group.
The error message is even more confusing, because the message has the same "click for more details" notification next to it like messages that failed to send because the server couldn't be reached.

In the latter case you can see to which members the message failed to send and just click "resend" to resolve the issue.
In the "a member of a signal group unregistered" case there are no more details and nothing to do for the user.

Proposed experience:
When Signal notices that a group member is no longer registered, there should be a notification that this member was removed from the group and has to be readded manually if they register again.

A fallback to MMS would probably be the worst option, because it could create huge intransparent costs e.g. for European users, leading to the immeadiate removal of the app.

I'm looking forward to your thoughts and improvement ideas!

Edit: The messages are usually delivered even if the error message is shown. But the constant error messages confuse users and make them loose faith in the app.

**Comment by kwantenmechaniker** [comment]
I fully second this. This kind of error handling has been the cause for several friends of mine to deinstall TS/Signal, often without deregistering which caused even more error messages in group chats.

Would it be possible to implement a script which  cleanly unregisters the user from Signal at deinstallation? If unregistered users are then handled correctly, then at least the remaining group members won't be as confused and annoyed.

**Comment by agrajaghh** [comment]
@kwantenmechaniker unfortunately it's not possible to detect deinstallation or run code before...

I have a lot of contacts as well who uninstalled Signal without unregistering. Imho they should be deleted from the server after some time...

**Comment by kwantenmechaniker** [comment]
@agrajaghh i feared as much... deleting them from the server sounds like a good idea though, maybe 4 weeks after the last message (including a warning from the app).

**Comment by kwantenmechaniker** [comment]
in deep hope that this issue will be addressed, i have a few proposals concerning the visual representation of a better error handling. the changes are minor, use well-known symbols and imho would help users to better understand what's going on.
unfortunately i can't code, so i'll have to leave the implementation to the experts here :innocent:

so, here they are:

1. **introduce grey check signs** as a representation for "only some of the messages were sent/delivered". 
  * in this example, a few messages were successfully sent but none are yet delivered:
![few-sent_none-delivered](https://cloud.githubusercontent.com/assets/10416356/11241976/45f79c70-8dff-11e5-9135-ecb51d8e16da.png)

  * now all messages were sent and a few were delivered, as it would be the case if one or more group members are currently offline:
![all-sent_some-delivered](https://cloud.githubusercontent.com/assets/10416356/11241987/505deb4c-8dff-11e5-95a1-910783254e4d.png)

  * if sending to one or more of the group members goes wrong (i.e. unregistered from signal or got a new key) it would look like this, with the error sign appearing after a few seconds:
![error_few-sent_few-delivered](https://cloud.githubusercontent.com/assets/10416356/11242014/67e71d6a-8dff-11e5-99ac-e67611bedd7c.png)

2. **make a similar representation in the "message details" view.**
  * mark the contact names with the current message status (sent, delivered, new key, error)
  * imho you omit the "via" detail (afaik mms is no longer supported anyway)
  * in this example xavier and joey are currently offline, and kate is no longer registered with signal:
![error_few-sent_few-delivered_details](https://cloud.githubusercontent.com/assets/10416356/11242028/77c30ca8-8dff-11e5-92fd-896484247535.png)

3. **display a dialog suggesting the reason for the irregularity** when the user taps on a name in the details view:
  * "This user may be currently offline. as soon as he/she is online, the message will be delivered."
  * "This phone number has probably unregistered from Signal. Do you want to keep it in the group for now or remove it? ->  Keep / Remove"
  * i'm aware that removing someone from a group is not (yet) implemented. it should be possible though, since adding one is. and this should probably be the only scenario where a group member can be removed (think cyberbullying)
  * sorry, no mockup...

**Comment by generalmanager** [comment]
@kwantenmechaniker Your proposals actually cover a bit more than what I intended with this issue. But it's basically all the things I have been hoping for UI-wise regarding groups anyways.
Thanks for spending the time to do a nice writeup with illustrations!

However I'm not sure if we should accumulate all those improvements in one thread/ticket, because doing so has lead to problems in other threads because people got a bit confused what a certain issue is about, when it can/should be closed or what closing means for the other features discussed (but not implemented at the same time).

I'd say if this doesn't blow up too much, or @mcginty chimes in and tells us he plans to implement all discussed improvements, we can keep the different additions in here. If only the initial request gets fixed (at first), we'll probably have to move the discussion about your additional improvements into a new issue.

**Comment by kwantenmechaniker** [comment]
@generalmanager you're welcome. i've also been hoping for them for a long time, but despite all my efforts telepathy delivered no satisfying results ;-)

fixing the issue you mentioned is the basis for my proposals to properly work, that's why i posted them here. i'd be honored if some of them find their way into the app, but of course bugfixing has to come first.

**Comment by agrajaghh** [comment]
see also this [comment](https://github.com/WhisperSystems/Signal-Android/issues/2642#issuecomment-78363087) by mcginty:
> Yes, unfortunately we don't store per-message group contexts as of now. This is probably a database change we would want to consider for the future, though, alongside a list of recipients that gave back delivery receipts rather than just a count.

**Comment by generalmanager** [comment]
@agrajaghh Very interesting insight, thanks!
But as far as I can tell, the problem of unregistered group members should still be solvable without those changes. All we need to know is if someone we try to send a message to unregistered and remove them from all Signal groups. 

So only the additional UI tweaks suggested by @kwantenmechaniker should be affected.

**Comment by kwantenmechaniker** [comment]
@agrajaghh interesting fact indeed, it explains all of the group chat misbehaviours i have encountered so far. implementing those additional database entries would really help, regardless of my ui tweaks.

but i guess we'll have to wait for @mcginty to clarify this...

**Comment by mr-gosh** [comment]
but should't be the "remove group member" option be enough to handle chenged phone numbers etc.?
