### ISSUE TITLE
On screen off, normal animation doesn't occur

### ISSUE THREAD

**Issue by instagibbs** [WhisperSystems/Signal-Android#4585]
When in the app and you turn the screen off, it immediately turns off instead of the typical fading animation.  

I'm using Nexus 5X, Android M.

**Comment by unrulygnu** [comment]
This is due to a privacy setting.

1. Menu > Settings > Privacy > Screen security (switch off)
2. Stop Signal (Recents > swipe Signal away)
3. Restart Signal
4. Turn off the screen (tap power button)
5. Observe the fade animation

Android needs the ability to capture the screen in order to run the animation.  When Screen security is turned on, Android can't capture the screen.

This issue can probably be closed.
