### ISSUE TITLE
Allow people to automatically join translations teams

### ISSUE THREAD

**Issue by jocelynthode** [WhisperSystems/Signal-Android#4586]
Hey,
I'm one of the translation maintainer. Each time a user wants to join a translation team I have to approve him/her manually, which is annoying and is not a good thing for people who want to translate right away.

Could @moxie0 tick the box to make it so users can automatically join a translation team without someone having to approve them (as it was in the earlier versions of Transifex).

I think you should be able to fix that by follow this link : https://www.transifex.com/moxie/teams/
and then clicking on TextSecure Team -> Gear icone -> ...

**Comment by moxie0** [comment]
done

**Comment by generalmanager** [comment]
Uhm except if there is supposed to be any control over the style of the translations. In the German team we've repeatedly had lots of problems with people who "barge in" and change lots of already done translations to their preferred style, completely ignoring the rules and reasons we agreed on in the forum. This leads to dozens of hours of unneccessary work for the current translation teams and is a huge factor of frustration, which in turn lead to the departure of team members who have been working on TS/Signal since the beginning.
Please try to keep this in mind when changing things like this.

**Comment by jocelynthode** [comment]
@generalmanager I still think that it's better this way. I have to remove multiple language proposal per week because people aren't accepted in their respective languages quick enough (I usually have to accept them myself in the end) so they ask for a new language.

What you could do is only put trusted members as reviewers. Then check each entries as reviewed when you think they are done.

This would at least fix the problem of altering already done translations.
