### ISSUE TITLE
A lot of translatable messages have linebreaks that seem unnecessary

### ISSUE THREAD

**Issue by amire80** [WhisperSystems/Signal-Android#4672]
A lot of translatable messages have linebreaks that seem unnecessary. As just a few examples:
* registration_progress_activity__your_device_needs_network_connectivity
* registration_progress_activity__no_network_connectivity
* registration_progress_activity__waiting_for_sms_verification
* registration_activity__your_country_code_and_phone_number

There are dozens of others.

Are these linebreaks actually useful for how the app runs, or are they there just to keep the line lengths in res/values/strings.xml under a certain limit? If it's the latter, then maybe they should be removed, because when translating in Transifex, they appear in a rather weird way, and the Transifex interface sometimes complains that they are not translated correctly, even when it appears completely artificial.

**Comment by RiseT** [comment]
In Sigal (I've seen examples where it's different in other software), they are just for strings.xml and don't appear in the app. So yes, generally I agree that these should be removed. The problem with removing them  is that all of those otherwise unchanged strings will then reappear on Transifex for translation. Personally, when I'm doing other changes on a string within strings.xml, I remove existing line feeds. But just changing those strings for the sake of removing those line feeds without changing anything else would cause too much unnecessary additional work for the translators imho.

**Comment by amire80** [comment]
So, I just did it myself at #4673.

Just 33 strings - less than I thought, actually. Took me less than 15 minutes to do it, and it should translators even less time to fix it, because it's nothing but removing linebreaks. As a translator I certainly wouldn't mind doing it.
