### ISSUE TITLE
Some group messages fail to sync to Desktop

### ISSUE THREAD

**Issue by lorenzhs** [WhisperSystems/Signal-Android#4859]
There is one particular group I'm in in which **no** messages I write on my Android phone sync to Signal-Desktop. As far as I can tell only this group has the issue. I also get an error when sending, but it doesn't show any particular problem. When I click on the error symbol in the message, there isn't an error next to any contact. When I go into the message detail view via long-press -> info, then it shows the "resend" button next to _every_ contact. Bit strange, really.

This group contains a user who unregistered from Signal.

adb logcat from when I pressed the send button until sending was completed and I got the error message on the phone: https://4z2.de/signal_faillog_ipahqu2Shoh6.txt (manually cleaned, because it's from adb logcat - I only anonymized the phone numbers)

**Comment by haffenloher** [comment]
> When I go into the message detail view via long-press -> info, then it shows the "resend" button next to every contact.

That's probably due to #3582, so not related to your issue :)

**Comment by lorenzhs** [comment]
Yes, thanks. I just thought that maybe this inconsistent behaviour was caused by the bug, potentially helping to track it down, so I mentioned it. Apparently it's not ;)

**Comment by liliakai** [comment]
Can confirm, sending to a group with an unregistered user will not sync that message to Desktop.

https://gist.github.com/anonymous/71a25c30a471db5dad2fd3627b951e8a

**Comment by haffenloher** [comment]
Just in case it helps anyone: this happens because the [call to `sendMessage()`](https://github.com/WhisperSystems/libsignal-service-java/blob/a1c93edc40e3ce201fa4e70339a3e6f4e197e319/java/src/main/java/org/whispersystems/signalservice/api/SignalServiceMessageSender.java#L155) in libsignal-service throws `EncapsulatedExceptions` so that [the following lines](https://github.com/WhisperSystems/libsignal-service-java/blob/a1c93edc40e3ce201fa4e70339a3e6f4e197e319/java/src/main/java/org/whispersystems/signalservice/api/SignalServiceMessageSender.java#L158-161) don't get executed.

**Comment by Trolldemorted** [comment]
working on it, gonna test it tomorrow. Let's see if we can get this merged before the issue gets 1year old :)

**Comment by Trolldemorted** [comment]
[PR is open](https://github.com/WhisperSystems/libsignal-service-java/pull/27)!

@moxie0 i understand that you are reluctant merge PRs into libsignal, but in this case it has to be done.

I have tested the PR on my nexus4 and on a friend's motorola, it works flawlessly.

**Comment by haffenloher** [comment]
Fixed in 3.31.0 by WhisperSystems/libsignal-service-java@e506464c!
