### ISSUE TITLE
README: Copyright wrong year

### ISSUE THREAD

**Issue by p4nci** [WhisperSystems/Signal-Android#4940]
@devs:
Can someone update README please?
We are already (nearly) in 2016 :-), but, in copytight it stands still 2014:
Copyright 2013-2014 Open Whisper Systems
Expected (at least):
Copyright 2013-2015 Open Whisper Systems

**Comment by p4nci** [comment]
@all Signal users
Happy New Year 2016!!!
Time again to update year of copyright in README.

@devs
Is there a possibility of "autoupdate"?

**Comment by p4nci** [comment]
@moxie0 time again for update: Copyright 2013-2016 -> ...2017

**Comment by ocram** [comment]
Leaving only the initial year of publication (e.g. 2011, 2012 or 2013) is fine. It's just for modified files that you *may* (and probably should) include the later year as well (by adding it to a range or listing the years).

If a file has not been modified in a given year, there's no need to touch it in order to update the copyright notice. And whenever you touch a file that has not been touched that same year, simply update the notice at that point.

**Comment by p4nci** [comment]
closing till 2018 :wink:
