### ISSUE TITLE
Feature Request: Ability to change maximum size of MMS

### ISSUE THREAD

**Issue by brettschulte** [WhisperSystems/Signal-Android#496]
I have seen this feature on other third party messaging apps it'd be great.  Thanks!

**Comment by devantoine** [comment]
:+1:

Currently it seems that the size is very low. I'm not able to send GIFs from Giphy with Signal but when using Textra to send the same GIF it works fine.

**Comment by brianpgrissom** [comment]
I still can't send most gifs because of the 300kb situation. I just reinstalled so I'll see if it's still a thing. I was hoping to have some time to finish a user preference (though that's kind of a no no) - because many US carriers have a much larger limit. However my tests have failed when setting the preference. I'll keep working, but hopefully Moxie gets the fix first.

**Comment by moxie0** [comment]
51d61445915e0a607742a46c60332e015f9559b6 uses per-carrier media constraints

**Comment by brettschulte** [comment]
unsubscribe
