### ISSUE TITLE
very loud "gong" when call connects

### ISSUE THREAD

**Issue by jontis** [WhisperSystems/Signal-Android#4988]
I think the "gong" that is played when a call successfully connects is VERY loud. I've had lasting pain in my ear from hearing it when all other volumes on my phone are normal. This in combination with Signal's frequent issues with low call volume, and the fact that this "gong" plays at a time when other call apps are done with connection signals have made me on several occasions position the speaker for max volume, hoping to hear my call partner, just to be surprised by the loud gong. Please lower this sound, or just double tap the sound that plays while it tries to connect.

**Comment by jontis** [comment]
It will of course help when you close the issues with low call volume, but the gong is still very loud. 
CM 12.1
Samsung Galaxy s4 mini
Signal 3.8.1

**Comment by janvlug** [comment]
I confirm this issue. The gong is indeed VERY loud, which is especially a problem because I have to set my volume to maximum related to issue #5004.

The gong is not always extremely loud, I have the impression that it is related to whether I have used my phone with a Bluetooth car kit or not, however, I've not been able to consistently reproduce the loud gong behavior.

**Comment by 2-4601** [comment]
The gong is gone from 3.29 onwards

**Comment by ghosted17** [comment]
I'm on 4.25.6 and having this issue. Hurts my ear
