### ISSUE TITLE
Remove "bell" in secure call

### ISSUE THREAD

**Issue by cyberc4t** [WhisperSystems/Signal-Android#5018]
Hi,
with the integration of Redphone in Signal, you have also integrated the bell, when the handshake completed.
I think that you should remove this "feature" because it's only "scares" new users who try the secure call.

**Comment by 2-4601** [comment]
Related #4988

**Comment by Dyras** [comment]
I think it should be replaced with something that doesn't pierce my ears. Maybe something similar to a violin, instead of a bell?

**Comment by cyberc4t** [comment]
I think the bell is nonsense. You hear when your call partner is speaking, no noise is needed.

But a quiet electonic "bing" would also be better than this horrible bell :-)

**Comment by moxie0** [comment]
thanks but we're not going to do this

**Comment by danielmackey1** [comment]
I would also appreciate an option to turn the bell off or reduce it's volume.

**Comment by valodiadeseynes** [comment]
Signal is supposed to be user-friendly but the "bell" presents two big issues:

1. It's so loud it's painful to hear when your ear is stuck against your phone and that will happen especially to new-users who are not expecting to hear anything but the voice of the person on the other end.
2. It scares non-techie users. Simple as that.

This may be an old issue and I'm sorry for bringing it up again but that "sorry we're not gonna do this" from you moxie is not satisfying at all. At least give us a few reasons because I can't understand your reasoning.

**Comment by Dyras** [comment]
I think making it quieter is what he has in mind, considering how this issue https://github.com/WhisperSystems/Signal-Android/issues/4988 is still open.

**Comment by danielmackey1** [comment]
"At least give us a few reasons because I can't understand your reasoning."

That request from Valodia De Seynes is not unreasonable. I wanted to use
Signal at my work as a replacement for Google Hangouts but one of the
issues people brought up was that Google Hangouts does not have a "loud
bell" which plays before it connects voice calls.

Kind Regards,
Daniel

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Daniel James Mackey Bogane
Founding Partner
Halicon Professional Services, Inc.
(619) 402 - 1337 x1
Fax: (619) 881 - 0039
Skype: daniel.james.mackey
