### ISSUE TITLE
No notifications show up until the app is manually open

### ISSUE THREAD

**Issue by annban** [WhisperSystems/Signal-Android#5085]
Hello! I've installed the Signal app just a few days ago on a Huawei P8 Lite device (Android 5.0.1) and sadly I'm experiencing a bug with notifications, namely: I don't see any notifications about new incoming messages. Only after I manually open the app, see if any new messages were sent. As you can imagine that's a pretty tough bug. Any ideas how to fix it? Other details: notifications for other messaging apps (Viber, What's App) are working all fine. The notifications are turned on in the Signal's settings. Signal is marked as a protected app in the device's settings + notifications for Signal are enabled in the phone's notification center. I was using a Wi-Fi connection to send/receive messages.

**Comment by edo0** [comment]
Are those notifications about traditional SMSs or Signal messages?

**Comment by annban** [comment]
Signal messages. So far I haven't used Signal for traditional SMSs.

**Comment by 2-4601** [comment]
There's a support article for this issue here:
http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-

I'm guessing it' because Huawei's Emotion UI is somehow restricting GCM messages. You need to exclude Signal from all "battery optimization" lists etc.

**Comment by edo0** [comment]
Then that happens to me as well, but only if I have received those Signal messages while offline, meaning that when I connect I have to open the app and I'll get the messages and the notifications altogether

**Comment by annban** [comment]
@edo0 @2-4601 thank you for your help! I went carefully through the threads and the thing that worked for me was unregistering and reregistering again (by default Signal was not marked as 'protected app' (allowed to keep running with screen turned off), I've changed that early on but looks like I needed to re-register after the change was made to make it work).

**Comment by 2-4601** [comment]
Good to hear it's working now!

**Comment by nzbart** [comment]
Just adding a new data-point regarding this issue. I had the same problem on a Huawei P9, and this was the only solution that worked. @annban's comment above (https://github.com/WhisperSystems/Signal-Android/issues/5085#issuecomment-172324636) about re-registering was an important step that I was missing before reading this discussion.

Maybe the app could help users overcome some of these problems by guiding them through these steps? Less persistent users may just give up and use another - easier - messaging app otherwise.

**Comment by agilob** [comment]
Just had the same issue where phone has a few battery saving modes, when phone is in:

![signal-attachment-2019-12-17-193121](https://user-images.githubusercontent.com/2544251/71028597-8483ba80-2105-11ea-8777-138f443a84ad.jpeg)


Messages from Signal don't arrive automatically, to compare WhatsApp and Telegram work fine.

**Comment by greyson-signal** [comment]
@agilob I can't say with certainty, but it's sort of an open secret that manufacturers have a secret whitelist of apps that they'll prioritize in power saving modes. It's very possible that Signal isn't on that list on your device, but other apps are.

**Comment by JulianOestreich90** [comment]
I have the same problem with osx on iphone8
