### ISSUE TITLE
Remove the Verify Identity for non-Signal users

### ISSUE THREAD

**Issue by TheNain38** [WhisperSystems/Signal-Android#5096]
Because they would not have an identity, if they don't use Signal

**Comment by ryaeng** [comment]
This is not necessary. When you attempt to verify the identity for someone you're communicating with via SMS Signal returns "Recipient has no identity key."

**Comment by TheNain38** [comment]
@ryaeng But it is better to remove it if this is a non-Signal user, as they won't even have an identity, it could confuse users who see: "Verify Identity" on their usual contacts and don't understand what it is

**Comment by FeuRenard** [comment]
To be more clear: we should hide the list entry "Verify identity" **if the recipient has no identity key**.

The following use case is imaginable:
A and B are both Signal users and exchange messages. Then one or both of them decides to unregister from Signal. So at least one of them is a non-Signal user by now. But as they chatted via Signal they both still have their identity keys and can still verify whether their conversation had a man-in-the-middle.

**Comment by FeuRenard** [comment]
This issue was solved by https://github.com/WhisperSystems/Signal-Android/commit/852634b2946e841fa986b76eb55ffe81a1926150 / #5646.

"Verify safety numbers" will only be shown if there are safety numbers to compare. It's even possible to compare safety numbers with somebody who unregistered from Signal.
