### ISSUE TITLE
SSL Certificate Problem

### ISSUE THREAD

**Issue by zero77** [WhisperSystems/Signal-Android#5100]
According to the Sift android app there is an error with Signals SSL certificate, I have posted a screen shot below.

https://s10.postimg.org/moih1hdux/Quick_Memo.png

**Comment by agrajaghh** [comment]
Signal uses a pinned self signed certificate, so this isn't a problem, but I'll leave this to @moxie0 to comment/close it...

**Comment by zero77** [comment]
o ok I see you use self-signed certificates. I think you can get trusted recognised certificates for free from hear but I haven’t looked into it.
https://letsencrypt.org

**Comment by mimi89999** [comment]
https://startssl.com also offers free SSL certificates.

**Comment by moxie0** [comment]
There is no reason to ever use a CA signed certificate in an app.  To do so would only enable additional points of compromise for zero additional value.  If you ever see anyone using a CA signed certificate in an app, they're doing it wrong.  See http://thoughtcrime.org/blog/authenticity-is-broken-in-ssl-but-your-app-ha/ for more information.

**Comment by kpcyrd** [comment]
@moxie0 is there a difference between pinning a signed certificate and a self-signed one?

**Comment by zero77** [comment]
I think you would be more open to MITM attacks if you didn’t pin it.

**Comment by mimi89999** [comment]
@moxie0 SHA1withRSA is very WEAK. The server also supports SSL 3 which is insecure.  :disappointed:

**Comment by moxie0** [comment]
@kpcyrd Yes, pinning a CA signed certificate is less secure.  The certificate you pin is the *signing* certificate, so while you've eliminated the ability for every other CA to forge certificates, the CA you've pinned still can.  Again, there is never any reason to use CA certificates from a mobile app.  It only weakens the app, and provides no value.

@mimi89999 For CA signed certificates, there is a concern that eventually SHA1 will lose collision resistance (hasn't happened yet, no collision has ever been found).  For a self-managed trust root, that is not a problem, since we don't issue certificates to anyone else from our root.
