### ISSUE TITLE
Option to show/hide images

### ISSUE THREAD

**Issue by morganw3** [WhisperSystems/Signal-Android#5103]
So, this is a messaging app and we all know that eventually you might send an image that is "sensitive". I propose a flag be introduced to the image picker that would cause Signal on BOTH sides of the conversation mask the image until tapped. Tapping the image again would re-mask it.

Implementation details could include a configuration option to always display images.

**Comment by moxie0** [comment]
thanks but we're not going to do this

**Comment by emk** [comment]
Signal is a lovely piece of software, and I've been getting as many people set up as possible lately. Thank you for all your work!

The new iOS 10 version of iMessage [is now advertising this as a significant new feature](https://mic.com/articles/146347/i-os-10-s-invisible-ink-feature-is-stealthy-af-here-s-how-to-send-a-hidden-message#.KvZVoWcqS). It sounds like the iMessage version might apply to both text and images.

I can think of two possible arguments in favor of this feature:

1. **The "popularity and adoption" argument.** It's worth keeping an eye on the most popular features of the major messaging clients, because if people are given a choice between secure communications and the features they're used to, many people will choose popular features over security. Will "invisible ink" be a popular iMessage feature? Only time will tell.
2. **The "security in public" argument.** When I'm messaging somebody, my messages often have mixed security levels. The vast majority messages can be read in public with other people around, and so recipients will inevitably tend to do so. But a small subset of messages are more sensitive, and should only be read in private.

For example, I might want to send the messages:

- _Low security:_ I made you a new login on the blog admin panel, username: jsmith.
- _High security, expiring:_ Your password is 12345.

Let's assume, for the sake of argument, that Signal is secure enough to send this particular blog password. In that case, the first message can be read anywhere, but the second message should really be read someplace without any prying eyes.

Of course, you could argue that (1) people should never send blog passwords, inappropriate images, etc., via electronic message, or (2) that people should always get in the habit of reading all messages in a private location, even if 99% of them are innocuous. But that's asking a lot of human nature.

IMO, none of the arguments in favor of this feature are really strong enough to justify devoting WhisperSystems resources to it in the near future. But I think the arguments in favor _are_ good enough to maybe reconsider sticking this on a long-term wishlist, especially if iMessage shows that this is a popular feature with a user-friendly UI.

**Comment by eazellou** [comment]
now that signal has native spoiler text support, it seems like a logical next step to also be able to spoiler / hide images. It would be so nice to know I won't be accidentally flashing a sensitive image in a public place.

**Comment by wizardofdocs** [comment]
and now that DOGE has [compromised ](https://techstartups.com/2025/03/26/elon-musks-grok-ai-joins-telegram-gaining-access-to-over-1-billion-users-a-new-era-for-search-and-chat/)Telegram, we're gonna see a lot of new potential Signal users who are accustomed to Telegram's image spoiler function, for whom Signal lacking that function is going to be a deal-breaker. The time has come.

**Comment by h7lv2** [comment]
Definitely feels weird not to include this since quite a few messengers out there have a way to mark an image as a spoiler, namely Telegram, Discord and iMessage.

This is certainly a dealbreaker for a lot of more casual folks.

**Comment by sinnom** [comment]
This is a necessary feature for myself and most of the folks I interact with. Being able to add a content warning and a spoiler to an image is important for safety reasons including: 
- avoiding or preparing for PTSD activators 
- avoiding or preparing for flashing lights
- avoiding or preparing for images that could otherwise cause nausea, headaches, pain, or other symptoms.

To expand on what wizardofdocs said, this is a deal-breaker of a missing feature for many folks. Especially folks most targeted by surveillance who are disproportionately disabled and survivors of trauma.

**Comment by slonkazoid** [comment]
this is really easy to implement please just do it

**Comment by wertzuz** [comment]
Feature requests belong in the [signal community forum](https://community.signalusers.org) Github is only for issues.
There are already multiple threads regarding the topic for example:
https://community.signalusers.org/t/ability-to-mark-messages-or-media-as-nsfw-confidential-spoiler/4358

**Comment by wesnm** [comment]
> Feature requests belong in the [signal community forum](https://community.signalusers.org) Github is only for issues. There are already multiple threads regarding the topic for example: https://community.signalusers.org/t/ability-to-mark-messages-or-media-as-nsfw-confidential-spoiler/4358

I believe this issue predates the discord, so the question of where it belongs is moot.

**Comment by wertzuz** [comment]
It does predate the forum (not discord) but it won't be reopened or revisited here, since it's not the place anymore.

**Comment by wesnm** [comment]
I guess the complaint probably belongs with Google, then. If only people had listened a decade ago, we wouldn't be here now.
