### ISSUE TITLE
Persistent notification icon

### ISSUE THREAD

**Issue by MyWay** [WhisperSystems/Signal-Android#5113]
Can you add an option for a persistent notification icon, like Viber and others?

**Comment by moxie0** [comment]
What is a persistent notification icon?

On 01/23/2016 02:26 AM, MyWay wrote:
> Can you add an option for a persistent notification icon, like Viber and
> others?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/Signal-Android/issues/5113>.
> 

-- 
http://www.thoughtcrime.org

**Comment by MyWay** [comment]
The icon on the notification bar.
Il 25 gen 2016 00:33, "Moxie Marlinspike" <notifications@github.com> ha
scritto:

**Comment by 2-4601** [comment]
I think this is one example of a persistent notification icon:
![screenshot_2016-01-25-16-24-47](https://cloud.githubusercontent.com/assets/174176/12553507/9fea9a0a-c380-11e5-808d-9e83fa8ef8bf.png)

But I don't know what would be the use case outside of that. What is it used for in Viber and other apps?

**Comment by MyWay** [comment]
Because if there is a background service running (linked to an activity)
the user should be aware of it, optionally, at least. If he does not
like the notification, he can unflag/disable it.

Il 25/01/2016 15:30, 2-4601 ha scritto:

**Comment by devdan** [comment]
There are tons of background services running on your device and almost none of them show a permanent notification icon. This makes sense because only background processes that need to run permanently (without any interruption) should display such an icon. Those permanently running processes tend to consume exceptionally much power and thus, it is important that the user is aware of them..

Signal, however, does not run permanently and can be suspended by the OS. Thus, a permanent icon does not make any sense.

**Comment by 2-4601** [comment]
Yeah, does not seem to make any sense to have it for that reason on Signal.
Also does not sit well with the [development ideology](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#development-ideology), so closing. (Moxie can reopen if this is wrong.)
