### ISSUE TITLE
Update Google Play Services error

### ISSUE THREAD

**Issue by andreicristianpetcu** [WhisperSystems/Signal-Android#5125]
Hi,
I just updated Signal for Android and I keep getting an error message: "Update Google Play Services/Signal won't run unless you update Google Play Services." The trick is that I pretty much disabled all Google stuff on my phone. The error also has an Update button that does nothing.Do I really need Google PS? It seems that I can send messages and receive messages but I get this error each time I start the phone.
My impression whas that other privacy minded people are like me and avoid Google stuff as much as they can.
What do do now? Downgrade? Is there a workaround for this?
Thank you!

**Comment by johanw666** [comment]
Google Play Services is used for 2 things: push messages and location messages. Push messages are used for a long time so I assume you have already some version of play services running. Since 3.9.0, the required version got updated to require at least 8.1.0 (was 6.5.87). See the changelog for build.gradle in https://github.com/WhisperSystems/Signal-Android/commit/bcf95e50aa38cae2dfe640ea1a1e26cbaa3a84b7 . I assume some used method required at least PS 8.1 but I didn't check them all.

To solve this, you can either install PS 8.1 or above and disable/block what you don't need with XPrivacy, Lucky Patcher or something else, downgrade Signal (apk's are easily available on Apkmirror but beware of database issues when downgrading), or build your own Signal version without location messages support (beware of the changed signature when installing a self-built version, Lucky Patcher can solve that issue).

**Comment by andreicristianpetcu** [comment]
It seems to work right now but I keep getting this message.

**Comment by cwmke** [comment]
Is there a way to leave the message popup, but allow people to go outside of it to continue using Signal without those services?  Wire, a similar app, also has a similar message pop up but you can continue to use the service.  With Signal, this is impossible since you can't register.
