### ISSUE TITLE
Verizon MMS Retrieval Extremely Slow

### ISSUE THREAD

**Issue by RichJeanes** [WhisperSystems/Signal-Android#5134]
I couldn't find an open issue that actually describes this other than #4474 which is about AT&T. Same thing happens here. When I receive an MMS message (eg. in a group thread), it takes upwards of one to two minutes to retrieve. I get a message bubble in the individual thread of the group member that I have an MMS message that is being downloaded and it just takes forever. Especially since it will only download one at a time, something that doesn't work well in a group thread of six people.

To quote @jabstone from the AT&T issue thread:
>When I comment out the following code below in the IncomingLegacyMmsConnection class, MMS messages are delivered immediately on Wifi or LTE on Verizon. Commenting this code appears to force the phone to connect over the MmsRadio connection and solves the problem for Verizon devices. I don't have my AT&T phone at the moment but I would suspect the AT&T phone won't follow this same code path since it's not a CDMA device. Do you know why the code below exists for CDMA devices...or Verizon in particular since Verizon doesn't allow MMS connections over Wifi? I feel like I might be hijacking this bug since it was originally AT&T specific. Let me know if I should create a new bug specifically for Verizon. Thanks.

>// if (isCdmaDevice()) {
// Log.w(TAG, "Connecting directly...");
// try {
// return retrieve(contentApn, transactionId, false, false);
// } catch (IOException | ApnUnavailableException e) {
// Log.w(TAG, e);
// }
// }

I don't know if this is the actual cause of the issue or not, but I though it would be relevant to include and to ping the other person having this problem. (@richteer, too, I assume from 6af1cea)

I've switched back to Hangouts to handle SMS for the time being, but I can switch back to test and get debug logs if those would be helpful.

Nexus 5X, Verizon
Android 6.0.1, January Security Patch
Signal 3.9.1

**Comment by jabstone** [comment]
I can only presume sms and mms bugs are being categorized as low priority since they never seem to get any attention. I switched back to google messenger for sms and mms messaging and use signal for signal native messages when possible. I'm a big signal messenger fan but I fear the numerous mms bugs are going to give the app a bad reputation. I have friends that have completely stopped using signal due to the mms issues on Verizon and AT&T. It would be great if there was a conscious decision to either resolve the mms issues or remove mms and sms capabilities all together like Hangouts is getting ready to do. I'd rather see signal focus on it's core competencies and be a great secure messenger app than be a good secure messenger app with terrible sms/mms support. My 2 cents. Either way, I'm a big fan of what these guys are doing.

**Comment by RichJeanes** [comment]
Yeah, that's totally fair. With the rumors of Hangouts having SMS support removed, I've re-enabled Messenger and started using it. But now I have Signal for the people that I can convince to use it, Hangouts for my family members that use that (and for video calls) (also Google Voice SMS), and then Messenger for everything else. Just kind of annoying swapping between three different apps.

**Comment by 2-4601** [comment]
Yes, it's frustrating to see bugs that directly affect you not getting attention. But remember that you can also contribute code yourself. Many people have done detailed research and posted useful comments on these various MMS issues which makes me wonder why they are not taking the next step and submitting a pull request? :) OWS currently lacks developers and Moxie can't fix everything by himself.
Also let's try to keep the discussion on the issue itself. For example high level discussion on general MMS support should go to the mailing list.

**Comment by agrajaghh** [comment]
just for completeness, it might be helpfull if you would post a debug log as well @RichJeanes 
I thought everything is better on marshmallow with the new MMS API :smirk:

**Comment by RichJeanes** [comment]
@2-4601 That's kinda rude. The point of the GitHub issue tracker is to track issues, is it not? Did I ever demand anyone's attention or that it be fixed immediately? No. In fact, I _just_ said that I would be understanding if SMS/MMS support was low priority and that using multiple apps was just a nuisance, not a big problem.
I'm normally happy to submit PRs, but Android is just not my thing. I'm working on it, but there's a lot to cell phone mechanics/APIs that I'm still figuring out. I haven't done much mobile development at all, let alone anything with the actual mobile part, so digging through the app code to fix SMS/MMS problems is rather difficult for me. You don't know what effort I have or have not put in, just that I'm trying to contribute what I can. I offered logs, I'm trying to help, I'm not here to whine and complain.
Keeping the thread on track is a fair and relevant point.

@agrajaghh  Will do on the debug log. :+1: 
Didn't know that was a thing. I'm very happy with the new Permissions system, though, when implemented well (if at all, yet).

**Comment by jabstone** [comment]
Here are the Verizon specific logs from issue #4474.
https://gist.github.com/0fed3adcfc7cbebe4e2e

**Comment by 2-4601** [comment]
@RichJeanes It was not a reply specifically directed at you and it was not meant to be rude. If I compliment people on writing good and helpful comments and the encourage them taking the next step I don't understand how that could be interpreted as being rude. There's even a smiley :)

**Comment by moxie0** [comment]
@RichJeanes it'd be cool if you could test this change, I don't have a verizon device.

**Comment by RichJeanes** [comment]
Will do.

**Comment by jabstone** [comment]
I just pulled the latest code with this fix and it works perfect on Verizon now. Much appreciated @moxie0.

**Comment by RichJeanes** [comment]
Testing with Signal v3.10.0 seems to work beautifully. Thank you very much!

**Comment by gartnera** [comment]
I don't think this code change fixed the issue, however it was fixed by #4474 (update apn database). I manually changed the apn database file on signal 3.9.1 and mms messages download in a reasonable time now.

If you want/need to make the change before the next release, grab [apns.db.zip](https://github.com/WhisperSystems/Signal-Android/files/110310/apns.db.zip), drop it in /data/data/org.thoughtcrime.securesms/databases, and chown/chmod to match the other permissions in the directory
