### ISSUE TITLE
Can recieve calls but not make them

### ISSUE THREAD

**Issue by vernal5150** [WhisperSystems/Signal-Android#5242]
https://gist.github.com/1799b056d685efc3f6f5 - I stopped the call when it wouldn't work.
android 5.1.1
LG Leon lmy47v
Signal v 3.10.0
https://gist.github.com/ac01de5814a9b7d4bc65 - I let it go until it stopped itself

It used to make calls fine to another Signal user, but within the last update or two (I don't use it often) the calls stopped working correctly.  It still sends texts fines.  Someone with the identical phone can make a call to me that works fine, but when I call out it simply rings and won't connect.

**Comment by moxie0** [comment]
The person you're calling isn't answering.  Chances are their phone isn't even ringing, most likely because they're not receiving push messages.  If they're on android, have them check this:
http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-

In the future the best place for support questions is support@whispersystems.org thanks!
