### ISSUE TITLE
Text does not wrap when "Enter is send" is enabled

### ISSUE THREAD

**Issue by forabi** [WhisperSystems/Signal-Android#5264]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports
### Steps to reproduce
- Enable "Enter key sends" in Settings > Advanced
- Type a long message
- Text does not wrap

From a UX perspective, these two things have nothing to do with each other, text could still wrap even if the input field does not allow "multiline" text, otherwise it becomes quite difficult to send long messages and the user has to break it into smaller ones, which might be annoying.

 **Signal version:** 3.11

This is _not_ a duplicate of #4219.

**Comment by zaprice** [comment]
I spent a little bit of time splitting this into two different settings: one for "Enter key sends" and one for "Enable text wrap". When you do that, you end up with some weird interactions:

* *Enter key sends & Enable text wrap* --> makes sense, but now there is no way for a user to input a newline character when typing; this is what @forabi requested
* *Enter key sends & ! Enable text wrap* --> weird; this lets the user input newline characters that don't render until the message is sent
* *! Enter key sends & Enable text wrap* -->  makes sense; this is the default
* *! Enter key sends & ! Enable text wrap* -->  makes sense; this is what "Enter key sends" already does

It would be nice to be able to have *Enter key sends & Enable text wrap*, but this enables some weird UX as above. It also adds another setting, which I know we don't like doing.

What are everyone else's thoughts?

**Comment by zaprice** [comment]
I spent a little bit of time splitting this into two different settings: one for "Enter key sends" and one for "Enable text wrap". When you do that, you end up with some weird interactions:

* *Enter key sends & Enable text wrap* --> makes sense, but now there is no way for a user to input a newline character when typing; this is what @forabi requested
* *Enter key sends & ! Enable text wrap* --> weird; this lets the user input newline characters that don't render until the message is sent
* *! Enter key sends & Enable text wrap* --> makes sense; this is the default
* *! Enter key sends & ! Enable text wrap* --> makes sense; this is what "Enter key sends" already does

It would be nice to be able to have *Enter key sends & Enable text wrap*, but this enables some weird UX as above. It also adds another setting, which I know we don't like doing.

In addition, there's [this](https://developer.android.com/reference/android/view/inputmethod/EditorInfo.html#IME_FLAG_NO_ENTER_ACTION); by default, `TextView` will not let you change the enter key on multiline views. This can be overridden since we have extended `TextView`, but it would conflict with how text boxes normally behave in Android.

> Note that `TextView` will automatically set this flag for you on multi-line text views. 

What are everyone else's thoughts?

**Comment by FeuRenard** [comment]
I think you mixed up two options.

- _Enter key sends & ! Enable text-wrap_ is what "Enter key sends" currently does
- _! Enter key sends & ! Enable text wrap_ is weird

I checked out your code and I think _Enter key sends & Enable text wrap_ is the way to fix this issue. By enabling "Enter key sends" you agree to have no way to input a newline character.
I encourage you to put in a pull request! But please leave out the text wrap option and let "Enter key sends" switch between `! Enter key sends & Enable text wrap` and `Enter key sends & Enable text wrap`. If you don't have time, notice me here. Then I will make a pull request that would be heavily inspired by your changes :wink:.

**Comment by FeuRenard** [comment]
cc @zaprice

**Comment by zaprice** [comment]
@FeuRenard I made the change you suggested, commit can be found [here](https://github.com/zaprice/Signal-Android/commit/25392086524217b103d7365658f969e9316fb6a4). Will submit a pull request.
