### ISSUE TITLE
Secondary phone numbers of Signal users not shown in contact list

### ISSUE THREAD

**Issue by billie80** [WhisperSystems/Signal-Android#5311]
Additional phone numbers of Signal users are not shown in the contact list. For non Signal users all phone numbers of the contact are available as expected.

**Comment by 2-4601** [comment]
@billie80 Which device, ROM, Signal version, contact app? (The issue template is there to remind the reporter to add these by default. Please use it in the future.)

**I can reproduce this with my Nexus 4:**

1. I have a Signal contact `+1 555 666` with whom I have exchanged messages for weeks but who is not in my system Contact app (Google contacts)
1. I open the Contact app to add
 * `+1 555 666` as the main number and
 * `+1 555 616` as an additional number
1. Signal shows both numbers as SMS only in Signal's contact list
1. I pull-to-refresh Signal contact list
1. Main number `+1 555 666` is now shown as Signal contact
1. Secondary number `+1 555 616` is not in the list at all

Nexus 4, stock Android 5.1.1, Signal 3.13.1, Google Contacts 1.1

Related #2257, #2531

**Comment by billie80** [comment]
I know that there are now templates for bug reports and pull requests but where do I find them? After a quick search I found nothing about it in Readme.md or elsewhere.

Device + App info:
Samsung S5 mini, Stock Android 4.4.2, Signal 3.12.0, Default Contact App

**Comment by FeuRenard** [comment]
Relevant lines in the code:

- https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/contacts/ContactsCursorLoader.java#L63
- https://github.com/WhisperSystems/Signal-Android/blob/0a569676f7a57144374a24faef566b2ca3233290/src/org/thoughtcrime/securesms/contacts/ContactsDatabase.java#L131

It seems like https://github.com/WhisperSystems/Signal-Android/commit/ff123943cb924955e9f4968b4a58e7ec953a1465 introduced this issue. That commit excludes those contacts while loading from the system contact database, which have one of their numbers registered with Signal. As those users are ignored completely their secondary numbers aren't shown.

There is [`filterNonPushContacts(cursor)`](https://github.com/WhisperSystems/Signal-Android/blob/master/src/org/thoughtcrime/securesms/contacts/ContactsCursorLoader.java#L95) which excludes push registered numbers from the contact list. This method could be used to fix this issue in combination with `querySystemContacts(filter)` before https://github.com/WhisperSystems/Signal-Android/commit/ff123943cb924955e9f4968b4a58e7ec953a1465. But maybe performance wise a new query method returning all non-Signal numbers (instead of non-Signal contacts) is preferrable?

**Comment by FeuRenard** [comment]
Fixed by dc18f73594cc95c7a65db38fe65b22d7e261dd0b / #6475
