### ISSUE TITLE
Key not synced properly

### ISSUE THREAD

**Issue by Coecoenut** [WhisperSystems/Signal-Android#5344]
Hi,
I have a problem with two devices (both Android) which do not sync their keys properly.
When communicating with the other device, I can receive messages with Signal, but not answer them. Instead I just get "Recipient has no identity key".
I also cannot view the key of the other person, while my key is synced to the other device.
This seems to be a copy of this issue involving iOS:
https://github.com/WhisperSystems/Signal-iOS/issues/1048

Removing and re-installing the app did not change the situation.

**Comment by 2-4601** [comment]
To help with this issue, please answer the following questions:
- What browser / app do you use for GitHub?
- Have you searched open and closed issues for duplicates?
- Have you read [Submitting useful bug reports](https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports)?
- What is your Android and Signal version?
- What are the Android and Signal versions of the other parties?
- What happens when you try to send a Signal message to a contact that has the issue?

And please post a debug log after you try sending a message.

**Comment by agrajaghh** [comment]
> I also cannot view the key of the other person, while my key is **synced** to the other device.

what do you mean by that?

**Comment by Coecoenut** [comment]
I'm using GitHub via Iceweasel on Debian
I searched for similar reports, both open and closed (see the link to the iOS issue above), and also red the respective link on useful bug reports.
I run LibreSignal from F-Droid in the most recent version (3.13.0), the other person is running Signal in the most recent version from Google Play.
A third person (mentioned in the iOS issue) who can communicate without any issue with both involved devices runs LibreSignal (also 3.13.0).
When I try to send a message to the respective contact, a regular SMS is being transmitted.
Log file: https://gist.github.com/Coecoenut/389be573ba515d0b96be

**Comment by moxie0** [comment]
"LibreSignal" is not our software. Please open issues on their issue tracker for support with their product.
