### ISSUE TITLE
Add some sort of ability for signal to track which peer's keys are verified

### ISSUE THREAD

**Issue by alex** [WhisperSystems/Signal-Android#5492]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature description
Right now if I do the QR code dance, and verify that my peer is who I think they are, there's no UI element which indicates that that this has happened. As a result, I have some contacts who I _forget_ we've verified keys, and so we do it a second time. This isn't harmful, it's just stupid on my behalf :-) If I'm the kind of person who cares about verifying keys (which is rare I grant!) this could also make it easy for me to see whose keys I haven't verified yet.

**Comment by skulumani** [comment]
This idea has already been discussed in #910 and #5443 

The fingerprint notion will eventually be replaced with something better

> trust management isn't in the near-future plans. There will be changes to how we encode fingerprints and possibly some trust indicators to show you've verified, but those aren't solidified and there are other higher-priority tasks compared to this.

**Comment by chronometric** [comment]
There's lots of more useful and sophisticated ways to implement some kind of identity verification, but what this large project should realize is that by the time that perfect outcome occurs, this issue will have been under heavy discussion for....three years? Something like a checkmark in the settings window next to where one clicks "verify keys" would seem intuitive, useful, and unlikely to encroach on any newer systems.

**Comment by 2-4601** [comment]
Closing as duplicate.

**Comment by glyph** [comment]
@skulumani What is "something better"?  Since #910 and #5443 (and about a hundred other duplicates) have been closed, is this still slated to come in some form?

Right now I'm resorting to sending the other person a message that says "safety numbers verified", but that doesn't work for folks who set the timer.

**Comment by wmbr** [comment]
So I guess the announced change to the verification UI is now complete (https://whispersystems.org/blog/safety-number-updates/).

Is there any news on a trust level indicator? Currently users not only have to manually track who they verified but also whether their key changed since then - a real hassle for what seems to me like a simple feature.
