### ISSUE TITLE
Can't verify - Hangouts steals the SMS message and Signal can't see it

### ISSUE THREAD

**Issue by BustedSec** [WhisperSystems/Signal-Android#5593]
I have:
- [ x] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

After signal installation, when attempting to verify the account it gets the SMS message, however hangouts is what grabs it and somehow despite signal being set as default SMS app it doesn't get it. 
### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
### Device info

**Device:** Manufacturer Google Nexus 5x
**Android version:** 6.01
**Signal version:** latest

**Comment by zoff99** [comment]
an option to manually enter the code from the SMS would be great. (now only other option is call)

**Comment by thatrez** [comment]
was able to verify with the phone call. Where is the location of the debug log, I'll post itt

**Comment by zoff99** [comment]
still, how about an option to manually enter the code from the SMS ?

**Comment by FeuRenard** [comment]
@zoff99 #2410 & https://github.com/WhisperSystems/Signal-Android/issues/4354#issuecomment-153441706 (source: https://github.com/WhisperSystems/Signal-Android/issues/4956#issuecomment-167081739)

**Comment by nrizzio** [comment]
@thatrez Have you enabled SMS/MMS read/send permissions? Android 6.0 will prompt you for each permission, I believe.

**Comment by zoff99** [comment]
@FeuRenard yeah moxie has only one answer, to almost any inquery :-(
without explanation or reason.

"thanks but we're not going to do this"

**Comment by siddarthramesh** [comment]
Yo same issue!!

**Comment by karshan** [comment]
Workaround: Go to hangouts.google.com More (...) -> Settings -> Uncheck "Receive SMS and voicemail in Hangouts"

**Comment by ucladev** [comment]
There are two annoyances here:

1. The user has to wait the full 2 minutes when they can clearly see that the verification SMS has landed (but is inaccessible to Signal due to third party SMS, e.g. Google Hangouts). 
2. After the two minute wait the user isn't allowed to enter the code from the SMS and instead has to initiate the phone verification to get a second code.

It seems the UX can be improved by:

1. Add text warning the user that third party SMS apps may cause Signal to be unable to find the verification SMS automatically.
2. Add a button that allows the user to cancel the 2 minute wait and input the code manually.

**Comment by oxapentane** [comment]
This issue is over the year old and only progress is that you have added recommendation to turn off other SMS app on the phone after verification fails.

Is there's some deeper motivation beyond "We won't" that was stated in referenced comments that I don't see?

FYI: It fails while using Android Messenger app by google on MIUI 8.5.3.0

**Comment by moxie0** [comment]
@oxapentane Please read the contributing guidelines before posting here again: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md

Looks like this should  be fixed in 4.13.0
