### ISSUE TITLE
Protection against Retroscope

### ISSUE THREAD

**Issue by vanitasvitae** [WhisperSystems/Signal-Android#5618]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

App seems vulnerable against Retroscope forensics tool: http://www.theregister.co.uk/2016/08/15/retroscope/

Are you going to do something against this?

**Comment by nrizzio** [comment]
I don't think there's anything they can do. Protection against this would probably have to come from the operating system - if we encrypted all data before storing it in RAM, we have to store **that** key somewhere in RAM, too.

Besides, this is a highly targeted attack, requiring someone to take your phone from you and image your RAM. I would presume that the people most vulnerable because of this kind of attack would also be aware of it and how to mitigate it.
