### ISSUE TITLE
Trying to link my device, but it keeps loading forever

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#5753]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I press "Linked devices" in Settings and it just keeps loading

### Steps to reproduce
1. Update to the latest version
2. Remove your old desktop device
3. Try to add a new one

**Actual result:** It keeps loading seemingly forever.
**Expected result:** The QR-code scanner should appear, allowing me to add my Signal-Desktop device.

### Device info
Device  : motorola MotoG3 (osprey_reteu)
Android : 6.0.1 (33, MPI24.107-55)
Memory: 25M (11.82% free, 96M max)
Memcla: 96, low-mem device
OS Host : ilclbld28
App:        Signal 3.20.0

### Link to debug log
https://gist.github.com/anonymous/19dd89f92134651e552133701f9bf163

**Comment by FeuRenard** [comment]
This is very likely introduced by https://github.com/WhisperSystems/Signal-Android/commit/d00441e20d4818200eb1e012488daf0e9ebe6b1b .
Unfortunately I won't have time to look into this until Sunday.

Can you try disabling network (airplane mode, check that Wifi is off too), then enter "Linked Devices" screen. You will get an error dialog. Enable network and press "Retry" or whatever the dialog offers instead of "Cancel". Maybe this could help. Nevertheless this needs to be fixed (or reverted for now) :/

**Comment by haffenloher** [comment]
@FeuRenard The dialog you mentioned ("Network connection failed...") also comes up if I just wait for a couple of minutes without disabling my network connection. *Try again* just shows the same dialog again immediately.

**Comment by Dyras** [comment]
Yup, seemed to have been a server issue.
