### ISSUE TITLE
Does not see SMS sent by other apps on the same phone

### ISSUE THREAD

**Issue by sparr** [WhisperSystems/Signal-Android#5903]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When I send an SMS with MightyText, it appears in the conversation with that contact in Messages, but not in Signal.

### Steps to reproduce
- Send a message to an SMS contact using the MightyText desktop or web app

**Actual result:** Message is sent. Sent message appears in conversation in Messages, not in Signal.
**Expected result:** Sent message should appear in Signal. (no comment on expected behavior re Messages)

### Device info

**Device:** Samsung Galaxy S7
**Android version:** 6.0.1
**Signal version:** 3.22.2

**Comment by sparr** [comment]
I believe this indicates that Signal is not importing new messages from the system SMS database as they arrive. It should.

**Comment by sparr** [comment]
Note that this is the opposite of #5491.

This is likely the same problem as #5803, and related to #4037

**Comment by jeremymasters** [comment]
Wouldn't it make more sense to just use Signal as the default SMS messenger in this case?

**Comment by 2-4601** [comment]
In addition to the other issues #5211 looks like a duplicate. Signal's database is separate from the system database for security reasons. Yes, it would be possible to read from the system's message store and in fact you can manually import from it, but displaying messages from two separate databases in the Signal conversations would probably be just too tedious a thing to maintain in the long run.

**Comment by sparr** [comment]
@jeremymasters I do use Signal as my default SMS messenger. That doesn't stop other apps (like MightyText, Google Now, etc) from sending SMSes.

**Comment by sparr** [comment]
@2-4601 there are plenty of issues here for users wanting Signal to read from and/or write to the system database. Other apps like MightyText have no problem keeping two databases. This doesn't seem "tedious" at all.

**Comment by 2-4601** [comment]
You could be right, Moxie will re-open if he sees that this should be implemented.

**Comment by nrizzio** [comment]
The reason why Signal doesn't use the system database is because the system database can't be encrypted. Since Signal offers app-level password protection, and in fact encrypts texts at rest by default (but leaves the encryption password blank on disk until it is set by the user), using two databases would defeat the whole purpose of at-rest encryption - the attacker could simply read the unencrypted system database.

**Comment by sparr** [comment]
@nrizzio I think you're in the wrong issue. This issue is about *reading* messages put into the system database by other apps, not about writing messages into the system database.

**Comment by moxie0** [comment]
@sparr That'd be cool, but it is tedious.  There are a bunch of edge cases, like we support importing your SMS database (so that it can be encrypted and you can delete messages from the system SMS database), but if people import it and don't delete those messages from the system database, then they'd see duplicate messages.

We could drop import all together, but we also have a pretty different database schema now, so merging the two cursors together would be non-trivial, and it would at minimum mean *four* DB queries every time you open a conversation.  MMS would probably be an absolute nightmare.

It seems like it'd be worth it if we wanted to go back to a world where all SMS/MMS is stored in the system database, but it'd be a lot of work just to catch an edge case like this one that doesn't affect most people.

**Comment by sparr** [comment]
Duplicates are a trivial problem to solve. Every major SMS backup/restore program does it automatically.

I think querying the DB every time you open a conversation is a poor approach. Rather, the app should register an intent to be notified of SMS entries being added to the system database, and catch them one at a time that way. That's how all the other "do something when I get an SMS" apps work, as mentioned in the other related issues here.

**Comment by moxie0** [comment]
Go for it!

**Comment by sparr** [comment]
That's all I needed to hear :)

**Comment by sparr** [comment]
It looks like we're going to need to use a ContentObserver pointed at content://sms/sent

something like this, but updated for newer Android APIs:

https://stackoverflow.com/questions/9520277/practical-way-to-find-out-if-sms-has-been-sent/9659025#9659025

I've got to figure out how to compile and test the app, then I'll take a crack at making this work.

**Comment by moxie0** [comment]
ContentObserver isn't going to work while the app isn't running

**Comment by sparr** [comment]
While the app isn't running we don't much care what it can't do, right? The observer will pick up recent additions to the database as soon as the app is opened... I think.

Sadly I might be abandoning this idea. I was very motivated to get it working, but installing a self-compiled version of the app resulted in all my messages getting deleted and my keys being lost, so I've lost most of my desire to keep using Signal at this point.

**Comment by moxie0** [comment]
A ContentObserver will not tell you about things that happened when the observer wasn't registered.

**Comment by sparr** [comment]
Good to know. I guess that means polling the ContentProvider ourselves, maybe when the app starts up, maybe when a conversation is loaded?

**Comment by moxie0** [comment]
You could do that, but now you're full on into de-dupe territory or two extra queries per conversation load. You think that's trivial, so I'll be looking for your PR.  =)
