### ISSUE TITLE
Encrypted backup update?

### ISSUE THREAD

**Issue by jvilhuber** [WhisperSystems/Signal-Android#5931]
I realize that https://github.com/WhisperSystems/Signal-Android/issues/1705 exists, but it's locked and has been there since 2014, locked in 2015, and now we're nearly to 2017. Is there an update? Is there a design document on how to implement this (I'd give it a go), or a description with what was/is wrong with the code that's commented out in the export fragment (et al)?

Status please?

jan

**Comment by sigenc** [comment]
I would love to see this implemented. Please read this pull here: [#5907](https://github.com/WhisperSystems/Signal-Android/pull/5907)


> We've been down this road and it doesn't work. If you want encrypted backup, here are the steps you need to take:
> 
> Make plaintext backup complete. It should export media, groups, preferences, block lists, etc... in addition to just text messages. All in a format compatible with SMS Backup & Restore.
> 
> Wrap the now complete plaintext backup in an encrypted stream.
> 
> Include the identity key in the encrypted stream.
>

**Comment by jvilhuber** [comment]
Ah I see @moxie0's comment there. That does make sense, but leaves open the question of "Make plaintext backup complete". I can see the idea here, i.e. "don't reinvent the wheel with yet another backup, and instead reuse the plaintext one, and wrap it in encryption". However, can the two be done in parallel? Is there a design document of some kind that outlines the format of the backup?

**Comment by johanw666** [comment]
Design document? Does OWS look like a large consulting firm to you? :-)

It will probably require reverse engineering the export code of SMS Backup and Restore (maybe throwing that app through a decompiler might give some usefull data). Then expanding the number of fields, export other information (identity key, app settings) and test that SMSBR doesn't barf on the resulting file. Then you might start to work on the import function.

All that work because the straightforward approach (just copy all files from and to /data/data/org.thoughtcrime.securesms), that Moxie had implemented originally, "does not work" without any further explaination.

So unless I see an explaination WHY it does not work despite my testing (and real life experience, I had a device crash recently and had to restore, reset some sessions and had no further problems) and WHY it can't be made to work with some small changes (like automatically reseting all open sessions) I'm not going to do that work. If I'm going to do in a lot of work I like to know why I'm doing it.

**Comment by moxie0** [comment]
We do not use GitHub for discussion or Q&A.  Please do not open issues here just to ask questions or bump topics.  If an issue is locked, it's generally because there has been too much discussion or people have been too verbose.

For this issue, the work to be done is very straightforward:

1) Make plaintext backup complete. It should export media, groups, preferences, block lists, etc... in addition to just text messages. All in a format compatible with SMS Backup & Restore.

2) Wrap the now complete plaintext backup in an encrypted stream.

3) Include the identity key in the encrypted stream.

I wish I had enough time to discuss at length why this is the only approach that will work for us, but sadly I don't have the time to do that for every issue.  I also wish I had enough time to do this work, along with all of the other open issues here, but I have to make choices.  If this is an issue that's important to you, I think step 1 would make a great PR.  Please see the mailing list or the online forums for further discussion, thanks.
