### ISSUE TITLE
Building Signal 3.28.0 fails: testGetItemIdEquals FAILED

### ISSUE THREAD

**Issue by motatuc** [WhisperSystems/Signal-Android#6088]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
The build process does not finish, it stops with giving errors.

### Steps to reproduce
- Fetch the latest source from github
- ./gradlew build

**Actual result:** The build process stops due to errors.
**Expected result:** The build process should finish fine.

**Log**

> org.thoughtcrime.securesms.ConversationAdapterTest > testGetItemIdEquals FAILED
    java.lang.AssertionError at ConversationAdapterTest.java:32
23 tests completed, 1 failed
:testDebugUnitTest FAILED
FAILURE: Build failed with an exception.

**Comment by RichJeanes** [comment]
I build from source on new version bumps and this started occurring for me with the most recent, v3.28.0.
Full stack trace and debug output available upon request. 
Building on Ubuntu 16.04.1.

**Comment by Stuie** [comment]
Looks like it was broken by this commit: 7286fd9b06ec582bfd4ed83dd81a461564806250

Both assertions in the test are failing because the mocked `Cursor` is being set up to handle getString(), but that's no longer being called. No `when()` is set up for the new methods being called on the `Cursor`, and so all the results are defaulting to 0.

I'll try to get a fix for the tests tomorrow, it's a bit late to make the change and create a PR at this point.

**Comment by Stuie** [comment]
It might make most sense to delete the unit test. It is of very little value after modification. We would essentially have to mock `cursor.getLong()` and all the assertion would do is confirm that the mock returned the correct value each time.

It's basically guaranteed to pass forever in the form I have below. Please provide feedback if you think it can be modified to be useful.

```java
  @Test
  public void testGetItemIdEquals() {
    when(cursor.getLong(anyInt())).thenReturn(1234L);
    long firstId = adapter.getItemId(cursor);
    when(cursor.getLong(anyInt())).thenReturn(4321L);
    long secondId = adapter.getItemId(cursor);
    assertNotEquals(firstId, secondId);
  }
```

**Comment by motatuc** [comment]
@Stuie, thanks for addressing this issue.

However, unfortunately your patch does not fix the problem.
The build process stops with this error:

> test/unitTest/java/org/thoughtcrime/ConversationAdapterTest.java:14: error: duplicate class: org.thoughtcrime.securesms.ConversationAdapterTest

**Comment by motatuc** [comment]
@Stuie, your posted code-snipped creates another error. Build still fails.
>test/unitTest/java/org/thoughtcrime/ConversationAdapterTest.java:14: error: duplicate class: org.thoughtcrime.securesms.ConversationAdapterTest

**Comment by Stuie** [comment]
The error you're posting now suggests you've got a duplicate class name, not a failing unit test.

As I mentioned, the unit test is very low-value, so I'm proposing deleting it instead of replacing it.

You can fix your build by just deleting your duplicate class and deleting the failing unit test with basically no risk that anything will break.

**Comment by motatuc** [comment]
Found it. Thanks for the comments and thanks for you fix. It works just fine (we of course need to wait until it's accepted to master).

**Comment by rejhgadellaa** [comment]
@Stuie thanks your suggestion worked, I didn't get the second error @motatuc pointed out.

Replacing the `testGetItemIdEquals` function in `test/unitTest/java/org/thoughtcrime/ConversationAdapterTest.java` with your code seems to solve the issue for now.
