### ISSUE TITLE
Crash after tapping "Enable Signal for SMS" bar

### ISSUE THREAD

**Issue by riyapenn** [WhisperSystems/Signal-Android#6135]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal crashes after tapping "Enable Signal for SMS" bar

### Steps to reproduce
- Do not have Signal as the default SMS app
- Open conversation thread where the "Enable Signal for SMS" banner is over the message input field 
- Tap on bar

**Actual result:** Crashes
**Expected result:** Pop up to confirm Signal as default messenger appears

### Screenshots

N/A

### Device info

**Device:** Sony Xperia L
**Android version:** 4.2.2
**Signal version:** 3.28.3

### Link to debug log

https://gist.github.com/b4f3f7e4f2594b6729060bf9c352df7d

**Comment by moxie0** [comment]
Very strange, this is a pre-kitkat device, so there is no concept of "default" SMS app.  This "Enable Signal for SMS" button should not be displayed at all.

If this is reproducible, can we get another debug log? This one starts right at the crash, I'd like something that covers the period before the crash.

**Comment by moxie0** [comment]
Alright, I see what's happening.  This user has somehow done some weird shit and gotten themselves into a state where they aren't able to communicate with the server (backup and restore or something?), which is why this call is failing.

I can fix it, but in the mean time if they re-register it should resolve what they're seeing.
