### ISSUE TITLE
One phone is silent in WebRTC call

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [WhisperSystems/Signal-Android#6140]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Repeatedly established a call with video calls enabled on both devices. Everything works fine, except that on the Android 4 device, one can't hear anything.

### Steps to reproduce
- Establish call between both devices (doesn't matter who)

**Actual result:** Can't hear a thing on Android 4 device (video functionality works, and I can hear just fine on Android 6 device).

(Edit: Regular, non-WebRTC Signal calls work just fine with the same devices.)

### Device info 1
**Device:** Samsung S III Mini
**Android version:** 4.1.2
**Signal version:** 3.29.1

### Link to debug log
https://gist.github.com/2c2abf3abb689ca0a4db2607a54fe84a

### Device info 2
**Device:** Motorola Moto G 2014
**Android version:** 6.0.1 (CM 13)
**Signal version:** 3.29.1

### Link to debug log
https://gist.github.com/2b7b458444a78db6d9f6028333e4088e

**Comment by halb9** [comment]
Cyanogenmod -> Stock ROM comes out silent. 

This is very similar to my experience. I have this problem with all my Signal Calls coming from an Cyanogenmod Device. I tried to give some useful information here: #4382 . 

What happens if you put your S III Mini on speaker? Can you hear something? 

As far as I can tell this is not Signal specific. I would say it has something to do with CM. Although they claim they are not doing anything different than Stock ROM regarding voice/microphone handling. 

However there is an entire thread (with a lot of postings :( ) about this issue. take a look. 
https://forum.xda-developers.com/galaxy-s5/development/how-to-microphone-gain-increase-s5-t3190613 

If someone like to tackle this, I will do my best to help.

**Comment by AlfonsoMuskedunder** [comment]
> What happens if you put your S III Mini on speaker? Can you hear something?

No, I can't hear anything on speakers as well.

> I have this problem with all my Signal Calls coming from an Cyanogenmod Device.

"Oldschool" Signal calls still work perfectly between the same two devices, I haven't had problems ever.

**Comment by halb9** [comment]
Somewhere in the other issues it was mentioned that a headset could help. Because the mic jack is used rather than the regular. 

If that doesn't help I'd say similar symptoms but different cause.

**Comment by AlfonsoMuskedunder** [comment]
Well, as I said, regular Signal calls work just fine. And since everything else is held constant, I believe in _my_ case the WebRTC implementation is responsible.

**Comment by moxie0** [comment]
@AlfonsoMuskedunder do you have the ability to build/test from source?

**Comment by AlfonsoMuskedunder** [comment]
I'm afraid I don't.

Moreover, unfortunately I think I could test a new build only by the end of next week, not before. But if it was possible that someone provided me with a build, I'd be happy to test it then.

**Comment by 2-4601** [comment]
I have one shitty Ice Cream Sandwich device (4.0.4) that is silent in webrtc calls but works with legacy redphone calls.

**Comment by 2-4601** [comment]
I'll have to hit the gym now but I'll test that when I get back

**Comment by 2-4601** [comment]
With these changes the ICS device is still silent during a webrtc call.
But now I'm hearing an annoying staccato noise on the receiving device during the call.

So it got a bit worse :)

Sample audio of the noise: https://dropfile.to/cvyZNMW

**Comment by moxie0** [comment]
dang. can you try the apprtc APK and see if you get audio with it on this device?
https://mega.nz/#!YtVUwACL!1sIjpZAsmYAnn8nN0wGvIAVURzUZpcmW7hi9QPEZG5I

**Comment by 2-4601** [comment]
That app does not seem to work with ICS?
```
$ adb install -r AppRTCMobile.apk 
[100%] /data/local/tmp/AppRTCMobile.apk
	pkg: /data/local/tmp/AppRTCMobile.apk
Failure [INSTALL_FAILED_OLDER_SDK]
```

**Comment by AlfonsoMuskedunder** [comment]
I just installed and tested the App with both devices. The outcome is absolutely the same. Video and microphone work on both devices, but the Samsung device's speaker is dead.

**Comment by moxie0** [comment]
@AlfonsoMuskedunder bummer, that's the webrtc reference implementation, so it'll probably be hard for me to do better than that, but i'll try

**Comment by AlfonsoMuskedunder** [comment]
@moxie0 How about I file an issue at AppRTC's GitHub repo? This could potentially take work off of you, and other WebRTC apps might benefit as well, who knows.

(And if you agree: Do you think their developers could learn something from the _Signal_ log files above? Otherwise I'd have to install Android Studio first etc.)

**Comment by digititus** [comment]
I'm having a similar issue with one device. Seems like the microphone isn't working in Signal for this device as it is the same in WebRTC and ZRTP calls. [cat.log](https://gist.github.com/anonymous/81f2eb175fe587fda1fb678b32c3f807)

**Comment by AlfonsoMuskedunder** [comment]
@digititus If your microphone is affected, it's probably a different bug. The one in this here thread affects speakers in very old Android 4 devices.

In order to keep things tidy (and raise the chance that your issue will be adressed) I suggest you file a separate issue with your debug logs.

**Comment by Cormak** [comment]
Android 4.1 is a mess compared to how Android 6 and 7 are and we need to either upgrade to better devices or install a custom ROM on these 5 year old devices. I see people using Android 6.0 on their GalaxyS3 and Signal works fine. 

Just because Samsung has abandoned these devices after 2 years doesn't mean you should continue to suffer with it. 

I also suggest that Signal stop supporting Android 2.3 devices and instead make 4.4 the minimum.

**Comment by 2-4601** [comment]
Dropping support might be ok if calling has never worked on some older marginal device/Android API level. However in my case the ICS device does work with RedPhone calls but not with WebRTC calls. (But personally I couldn't care less if that device stopped working with Signal because I don't even use it.)

**Comment by AlfonsoMuskedunder** [comment]
@moxie0 It seems that the AppRTCMobile.apk you uploaded above is outdated. I have tried the latest version of the demo app, and it works on the Samsung device!

There could be lots of reasons for that, but one might lie in recent changes to the WebRTC libraries, no? (And who knows, maybe these changes might benefit Signal as well. Just dreaming here.)

**Comment by moxie0** [comment]
@AlfonsoMuskedunder thanks good to know, I'll update to M57 in the 3.31.0 release and see if that helps

**Comment by chrihu** [comment]
Just tested the 3.31.0 branch and can confirm that this issue is fixed on my old ICS device!

**Comment by moxie0** [comment]
closing with the assumption that M57 did fix things
