### ISSUE TITLE
[Beta call system] Button to end call disappear when video is on

### ISSUE THREAD

**Issue by ruicruzpt** [WhisperSystems/Signal-Android#6225]
### Bug description
When video is on on the new beta call system, the red button to end the call does not appear. However if I click on it's place it will end the call.
(sugestion: if video is on, put the button on the top screen)

### Steps to reproduce
- enable beta calls fom advanced menu
- call any user who can did the same
- enable video and see no red button

### Device info

**Device:** Sansumg S6
**Android version:** 6.x

### Link to debug log
https://gist.github.com/anonymous/66f22ef80d2cd8441c5aa9c855ddf9ea

**Comment by Shenkaa** [comment]
That is related to https://github.com/WhisperSystems/Signal-Android/commit/f3e47f7b608a6beb77b6732d676b47c56184248c and shouldn't be a bug.
If you tap somewhere on the screen, the button and the info on top should appear again.

**Comment by ruicruzpt** [comment]
The info on top is always visible. But the button is not. Even if I tap on the top bar with the name of the person I'm calling.

Is this a diferent behavior that what you've posted, I assume?

**Comment by Shenkaa** [comment]
During a call (without video) it should look like this:
![signal_call](https://cloud.githubusercontent.com/assets/25299821/22987552/7b7a808a-f3af-11e6-8483-bae15150b765.png)

And if the person on the other site of the call enables the video, the button + info disappears (minimizes) and it should look as follows:
![signal_video_call](https://cloud.githubusercontent.com/assets/25299821/22987615/b1327fa2-f3af-11e6-92be-72625c290a58.png)

To get the button + info back, you just tap on the screen (video). With another tap they minimizes again.

**Comment by moxie0** [comment]
Thanks @Shenkaa can you include anything more about how you're able to reproduce this?

**Comment by ruicruzpt** [comment]
Hi,

@Shenkaa  thanks! I was feeling a bit alone here. :)

@moxie0 basicly I just made a call as I submit on my initial bug report. I tested this with two contsts and they bot have Android. I don't have any Signal-iOS persons who I do videos with. So I'm not sure if this is an Android only bug.

**Comment by tsdmgz** [comment]
I'll add a "me too!" here. Call controls disappear when other party turns on video and taping the screen pulls the top bar up but doesn't show the end call button at the bottom. To get the controls to properly show up, I have to go to another screen line home then reopen the call from the notification bar.

Also on a Samsung Marshmallow device.

**Comment by Shenkaa** [comment]
@moxie0 I've tried it on four devices (Samsung Galaxy Ace 2, Wileyfox Swift, OnePlus One & OnePlus 3) now and can reproduce it on three of them. I noticed that the only device, on which the bug does not appier, has software buttons.

After that I aktivated the software buttons on the two OnePlus devices. And lo and behold.. the bug no longer occurs! Swiched back to hardware buttons and the bug is occuring again..
@ruicruzpt and @tsdmgz both have a Samsung device, so both with hardware buttons and this bug.

I also noticed, that when the call button minimizes, it disappears behind the software buttons.
On devices with hardware buttons, there is a small gap between the bottom of the screen (slightly smaller than the height of the software buttons) behind which the button disappears.

**Comment by Shenkaa** [comment]
@moxie0 I've tried it on four devices (Samsung Galaxy Ace 2, Wileyfox Swift, OnePlus One & OnePlus 3) now and can reproduce it on three of them. I noticed that the only device, on which the bug does not appier, has software buttons.

After that I activated the software buttons on the two OnePlus devices. And lo and behold.. the bug no longer occurs! Swiched back to hardware buttons and the bug is occuring again..
@ruicruzpt and @tsdmgz both have a Samsung device, so both with hardware buttons and this bug.

I also noticed, that when the call button minimizes, it disappears behind the software buttons.
On devices with hardware buttons, there is a small gap between the bottom of the screen (slightly smaller than the height of the software buttons) behind which the button disappears.

**Comment by moxie0** [comment]
@Shenkaa nice investigation! i'll see if i can find a phone with hardware buttons

**Comment by moxie0** [comment]
@Shenkaa I just made a call on a OnePlus One, enabled video, and when I tap on the screen the end call button animates up and down without incident. Is there a step I'm missing? (I do notice the small gap between the bottom of the screen and the height of the would-be software buttons that it disappears behind, though.)

**Comment by Shenkaa** [comment]
@moxie0 If you call the OnePlus One, activate the video firstly on the other device. After that activate the video (tap the minimized camera button) on the OnePlus and tap on the screen to maximaze the info + button. The bug should occure now.

**Comment by moxie0** [comment]
Thanks @Shenkaa , definitely an Android bug. That should work around it

**Comment by Shenkaa** [comment]
Jep, I tested it on my 4.4.4 test device and the error did not occur (just a little unsmoothed animation)! Thanks!

**Comment by moxie0** [comment]
@Shenkaa yeah it's gonna be glitchy on affected devices, thanks for confirming!
