### ISSUE TITLE
Add an f-droid repo signed by WhisperSystems

### ISSUE THREAD

**Issue by leedoyle** [WhisperSystems/Signal-Android#6292]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### f-droid repo signed by WhisperSystems
Please add an f-droid repo, so people without Google Play Store could have Signal updated on a regular basis.  I totally understand and partly agree with @moxie0 's critcism of f-droid security. However, one can address those issues by creating his own f-droid repo and sign it with his own key.
Projects that did so include [Guardian Project](https://guardianproject.info/fdroid/). Information on how this can be done can be found [here](https://guardianproject.info/2013/11/05/setting-up-your-own-app-store-with-f-droid/)

### Why this is important
Recently, a very important change has been made -  [it is now possible to use Signal without Gapps](https://github.com/WhisperSystems/Signal-Android/commit/1669731329bcc32c84e33035a67a2fc22444c24b), and that also means that  many new Signal users have to download the Signal apk off third party services, like apkpure, which is insecure and makes it impossible to update in a timely manner, which contradicts fundamental believes shared by WhisperSystems team in general and @moxie0 in particular.

**Comment by nrizzio** [comment]
Duplicate of #127.
There's discussion on the forums about this at https://whispersystems.discoursehosting.net.

**Comment by leedoyle** [comment]
@nrizzio Thanks for referencing, very interesting. 
However, I believe that the issue you referenced **doesn't reflect the changed situation** — the possibility to use Signal without GApps and new users' needs, which manifests itself e.g. in it's being locked and limited to contributors only.

**Comment by piratenpanda** [comment]
Seems somewhat similar is coming https://github.com/WhisperSystems/Signal-Android/commit/9b8719e2d56a098502475bb5b2295c7a376d4caa

**Comment by strk** [comment]
Is this an official build fron whisper systems ? Only way I found to download a binary w/out a goigle account... https://signal.org/android/apk/

**Comment by mawed** [comment]
https://signal.org/android/apk/ is an officially build and signed by OWS!

**Comment by moxie0** [comment]
Yep, that's an official non-play self-updating build

**Comment by Korb** [comment]
>  Projects that did so include `Guardian Project`

The Guardian Project has its own repository with the `Signal Private Messenger by Signal Foundation` app. You can connect this repository in the `F-Droid` mobile app and use all the features you've requested to find, install, and update this messenger through an alternative app store.

NB. Recently, when I update the repository, I get the following error:

```
Download failed! io.ktor.client.plugins.ClientRequestException: Client request(GET https://raw.githubusercontent.com/uardianproject/fdroid-repo/master/fdroid/repo/Signal-Android-website-prod-universal-release-7.58.2.apk) invalid: 404. Text: "404: Not Found"
```

Perhaps if the application was built for F-Droid or IzzyOnDroid directly from the current repository, everything would be simpler and more stable.

I'd be curious, at the very least, to hear what @IzzySoft himself has to say about F-Droid's fundamentally unacceptable insecurity compared to Google Play for all messenger users, something the app's developers have repeatedly cited in this issue tracker. Is it that bad?

**Comment by greyson-signal** [comment]
There's multiple ways to get a Signal-signed APK these days. First, as previously mentioned, you can use https://signal.org/android/apk/, which has a self-updating mechanism. Alternatively, you can use Obtainium and point it to our Github repo, where we also publish signed releases, and you can have it manage your updates. We provide instructions on [the forum](https://community.signalusers.org/t/get-the-latest-android-releases-even-faster-with-obtainium/65274). 

Regarding the security model, historically F-Droid required that it signed the builds themselves. This honestly never felt great, because if they're in charge of signing, they could change the APK however they wanted. Since then, F-Droid allowed the ability to self-sign, so long as your builds passed their reproducibility rules. That's pretty cool, but honestly not the most fun thing to setup. 

Of course, in the meantime, Google Play has required the ability to sign our APK too, so in that way it's sort of a wash. There is a new [Code Transparency](https://developer.android.com/guide/app-bundle/code-transparency) certificate system that's a pseudo-replacement, but you have to manually check it. 

But F-Droid is also in a lot of trouble in general with the new requirements Google is pushing around developer registration. You can read F-Droid's latest stance on [their blog](https://f-droid.org/2025/09/29/google-developer-registration-decree.html). They have a few options, but they're all bad. It goes without saying that the new developer registration rules are really terrible for many reasons, and it sucks that F-Droid is in a weird spot.

**Comment by wertzuz** [comment]
https://community.signalusers.org/t/make-signal-available-in-f-droid/2808/162
Seems to be the feature request for this.
Sad that its not so easy right now but maybe at some time it will be possible.

**Comment by nar001** [comment]
I'm curious, how hard would it be to set up the reproducible system now? Since your builds are already reproducible anyway, wouldn't it already be a done deal?
