### ISSUE TITLE
Messages from Signal-Android appears twice on Signal-Desktop on latest beta

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/Signal-Android#6331]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
For a week or two almost every message I send from Signal-Android appears twice on Signal-Desktop. This includes pictures. **Now before you tell me to go to Signal-Desktop instead, Lilia Kai said this might be a Signal-Android issue.**
https://github.com/WhisperSystems/Signal-Desktop/issues/1038#issuecomment-283771734

### Steps to reproduce
1. Send a message with Signal-Android, it doesn't matter if Signal-Desktop is online or offline. At first it only consistently happened when Signal-Desktop was offline, but now it happens every message regardless of what I do.
2. The message will appear twice on Signal-Desktop.

**Actual result:** Messages appear twice in a row
**Expected result:** Every message should only appear once

### Screenshots
https://nup.pw/FARUE2.png

### Device info
Device  : motorola Moto G (4) (athene)
Android : 6.0.1 (64, MPJ24.139-63)
Memory  : 52M (13.54% free, 384M max)
Memclass: 192
OS Host : ilclbld87
App     : Signal 3.30.4

### Signal-Android debug log
https://gist.github.com/anonymous/4f0973a66b7fb88ecf575e8e178bc40d

### Signal-Desktop debug log
https://gist.github.com/833edff1008c4197cf41e9bfb9f0a5bf

**Comment by petcap** [comment]
I can confirm this behaviour for the past few weeks. Some (not all) messages sent by me on my Nexus 5x appears twice in my desktop client. The people who I send messages to only receives each message once, on both their mobile and desktop clients.

For me, there is a much higher probability that messages comes in twice if the desktop client is closed when a message is being sent from my phone. It seems that messages that come in just right after the desktop client has started are more prone to be affected by this bug, it happens to almost all messages in my case.

As I can see a correlation between how often this bug shows up depending on how I start the desktop client, I believe this bug is not related to the Android code but rather to the desktop client code.

**Comment by liliakai** [comment]
I experienced this last night with an image sent from my Android device. On desktop, the message was received and the image downloaded twice. I notice that the messages have the same timestamp, but the two image downloads have different attachment id's, which means Android is definitely uploading the image to the attachment server twice.

This occurred in a group chat. Messages I sent in one-on-one conversations during the same time period were not duplicated.

Desktop log starting just before the dupe messages:
https://gist.github.com/83becbc4c707ef5a56e7af662f0740dd

Android log:
https://gist.github.com/b9a6ce388c3c7442270cf37c93cb6015

**Comment by Trolldemorted** [comment]
@liliakai does the android log contain the timeframe in which you sent the message?

**Comment by liliakai** [comment]
@Trolldemorted Doesn't look like it. 😞

**Comment by Trolldemorted** [comment]
Maybe we should open an issue for bigger debug logs (i'd *really* appreciate bigger ones, as most users do not have the GRAB DEBUG LOG IMMEDIATELY-reflexes), but why is yours spammed with `Got local CC: US`-warnings?

**Comment by liliakai** [comment]
I don't know but I've seen that spam in many an Android log. :+1: longer logs. In this case I didn't even notice the issue had occurred until ~12hrs later.

**Comment by m3ki** [comment]
I am having the same issue, not sure if this [log ](https://gist.github.com/a2f30a3cffd0cc3fa2ed7c43af4c4965)will help 

Signal desktop is on windows 10, chrome.
Signal mobile is on Latest Android, Nexus 6P

I can provide more info if needed.

**Comment by malkhamis** [comment]
I confirm the same issue is happening here.. This happened when I sent an image from the mobile device while the Desktop app is also open.

Device:
Android Nexus 5X 7.1.1

Computer:
Linux, Ubuntu 16.04

Browser: Chromium Version 56.0.2924.76 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by Trolldemorted** [comment]
is anyone of those affected NOT using disappearing messages?

**Comment by rainerzufall** [comment]
Yes, this happened recently to me twice without disappearing messages. But it seemed random and not reproducible. I will upload logs the next time it happens again.

**Comment by gordon-morehouse** [comment]
This is 100% reproducible for me. It requires nothing special or weird to happen other than (presumably since I always use them) disappearing messages. It has been constant across multiple installs of Desktop and on two phones over a period of months. I don't use the group chats feature, it happens to me in private conversations. See https://github.com/WhisperSystems/Signal-Desktop/issues/1138. Will more logs help?

**Comment by Trolldemorted** [comment]
@rainerzufall random and poor-network-related? That would be working as intended on the sender side.

**Comment by rainerzufall** [comment]
It was random and I did not see it again. (Although I am not re-readig my conversations on the desktop just to find this bug). I really don't know if it was poor network related. But since the rest here has this issue with disappearing  messages, I would say let's attribute it to that... Therefore my initial report does not belong here. Sorry.

**Comment by deutrino** [comment]
This is fixed for me as of a few weeks ago.

**Comment by Dyras** [comment]
It's not happening on Electron for me, so I guess this is fixed? Anyone else can chime in on whether this is happening or not?

**Comment by petcap** [comment]
I can confirm that this issue seems to be resolved, I used to have a lot duplicate messages but I haven't seen a single one during the last couple of months.

**Comment by moxie0** [comment]
Thanks, this was a desktop issue anyway
