### ISSUE TITLE
Enabling Video changes bottom mic to top mic. Disabling does not change it back

### ISSUE THREAD

**Issue by halb9** [WhisperSystems/Signal-Android#6345]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Enabling Video Call seems to use the mic on top of the phone instead of the bottom (might be intended). However if Video Call is disabled it should go back. 

### Steps to reproduce
1. Start Signal Call
2. Tap against the top and bottom mic hole on your phone. On the other phone, you should only hear the tapping from the bottom hole. 
3. Enable Video
4. Repeat 2. But now top mic is active. Bottom mic is disabled. 
5. Disable Video
6. Repeat 2. Top mic is still active. Bottom mic is disabled. 

**Actual result:** Mic does not change back. 
**Expected result:** If the switching is intended behavior it should switch back to where it came from. Be consistent ;)

### Device info

**Device:** Galaxy S5
**Android version:** see log
**Signal version:** see log

### Link to debug log

https://gist.github.com/anonymous/57fcc910aaf64b9be8cfc7e0676cde9f

**Comment by moxie0** [comment]
I think this is the intended behavior.  If you enable video, we auto-enable speakerphone for you (unless you have a headset in), since it is pretty much impossible to have a video call otherwise.

When you disable video, we leave the speakerphone on, since it's not clear that you want to switch to your earpiece in that moment. You might want to continue to use the speaker as you have been doing, just without video.
