### ISSUE TITLE
Change New Signal Contact Behavior - "XXX is on Signal, say hey!"

### ISSUE THREAD

**Issue by ryanohoro** [WhisperSystems/Signal-Android#6423]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
When a new user installs Signal, Signal notifies all of their contacts who have Signal that Signal has been installed. This is an invitation to communication which may be unwanted or long outdated.

### Steps to reproduce
- Install Signal
- Get messages from ex-lovers or business associates you have no interest in communicating with

**Actual result:** Signal, without advising me, tells everyone with my phone number stored in their phone that I have installed Signal.
**Expected result:** When I install Signal, it should be my choice if Signal tells everyone who has my phone number, intentionally or not, that I've done so.

### Screenshots
![screenshot_20170321-125045](https://cloud.githubusercontent.com/assets/10855297/24168062/3b15678e-0e36-11e7-9d83-26794a2962cf.png)

Notification from an OKCupid date 8 years ago.

Two suggestions:

- Allow the new user to choose if these notifications are generated.
- Only notify a contact that Signal is available when composing a new message to a contact with Signal installed.

**Comment by moxie0** [comment]
Hey @ryanohoro, right now what we support:

1) If you don't want to see these notifications, you can turn them off (Signal Settings -> Notifications).

2) If you don't want to hear from someone at all, you can block them.

For some technical background, the notifications you're referring to are locally generated. The Signal service isn't sending everyone in your contacts list a message to inform them that you've registered or anything like that (because the Signal service doesn't have a record of who's in your contact list).

If a contact has you in their address book, the next time *their* app notices that you're registered, it will locally generate that notification. It's all happening local to them.

However, pretty fundamentally, anyone who knows your number will be able to see that you're a Signal user.  That's really by design: we want private communication to be simple and frictionless, it's one of the primary objectives of this project. Being a Signal user isn't intended to be a "secret," just the opposite -- we want anyone who knows your number to be able to easily communicate privately with you.

Anything that makes private communication more difficult is unlikely to align with what we're trying to accomplish. Changing Signal so that it didn't show you who you could communicate with using Signal until you explicitly tried to initiate a conversation with them using Signal (which may or may not succeed?) would in my opinion make Signal much more difficult to use. Not everyone is using Signal on Android as their default SMS app, and Signal on iOS can't support using Signal for SMS, so it would be particularly awkward in those cases.

If you'd like to discuss this further, please see the online forums linked from the README, we try not to use GitHub for discussion. Thanks!
