### ISSUE TITLE
Contact list: Contact entries swap names and avatar pictures

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#6488]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
For a rather long time now (at least months), I've noticed a strange phenomenom in Signal's contact list.

~~When launching Signal from scratch (not from RAM)~~, the **names** and the **avatar pictures** (**not** the phone number) of two of my contacts (always the same ones) either a) swap places within the contact list, or b) one of them is displayed for both contacts. Refreshing Signal's contact list manually always corrects the situation. This happens pretty often, i. e. > 25 % of the time ~~when Signal is not in the RAM anymore~~.

Again, the phone numbers aren't swapped. They stay at their "correct" places all the time. Which with the swapped names/avatars of course means that e. g. under the letter "M", you have an entry with name and avatar of "Jxxxxx", while the corresponding phone number is "Mxxxxx"'s.

PS: Don't know if this is important here, but "Mxxxxx" used to have dual SIM.

Edit: As pointed out by @AndHell , the affected contacts are always **the 6th and the 8th contact of the list**.
Edit: As an alternative to refreshing the contact list, leaving and re-opening it seems to work as well.

### Steps to reproduce
1. Launch Signal when it's not pre-loaded into memory
2. Open contact list & dismiss keyboard
3. Notice issue
4. Refresh or leave and re-open contact list
5. Notice everything's correct now

### Screenshots

**Screenshot at step 3:**
![screenshot_20170403-034953 markup small](https://cloud.githubusercontent.com/assets/12624674/24654170/de25fbc0-1938-11e7-97b6-3d60281f9f9a.png)

**Screenshot at step 5:**
![screenshot_20170403-035024 markup small](https://cloud.githubusercontent.com/assets/12624674/24654180/e81ff702-1938-11e7-85ed-8527de1ea7bb.png)

### Device info

**Device:** Nexus 5X
**Android version:** 7.1.1
**Signal version:** 4.2.2

### Link to debug log

Taken at step 5, i. e. after refreshing the contact list.
https://gist.github.com/anonymous/cb0f2786a618aae220e2fdbc613a59df

**Comment by jeremymasters** [comment]
Not sure if this is related, but I'm getting some contacts that have no avatar letter and some cases where sorting is clearly not by what's shown in the list.  Is there some non - determinism in the query or display output?

**Comment by AndHell** [comment]
I had the same issue once. 
But I'm not able to reproduce it right now. The swap happens between a Signal and a SMS contact like you can see in the screenshot.
Like in your screenshot it's the 6 and 8 contact in the list. 

![screenshot_20170324-173145](https://cloud.githubusercontent.com/assets/11991279/24671955/7ce4877e-1973-11e7-98af-a35e21c2455e.png)

**Comment by RiseT** [comment]
> Like in your screenshot it's the 6 and 8 contact in the list.

That might be an interesting coincidence.

**Comment by RiseT** [comment]
@AndHell Thanks, confirmed. I've just reordered my  contacts by changing their names, and it's always the 6th and the 8th contact.

**Comment by FeuRenard** [comment]
I open the contact list via pencil button in conversation list. The contact list is displayed and the keyboard is shown. You don't mention the keyboard in your "Steps to reproduce". Doesn't it open for you @RiseT ?
On my phone (5 inch screen, full HD) the first four contacts in the list are shown completely, the fifth one is partly covered by the keyboard. Contacts 6,7,8 will be shown, if I dismiss the keyboard. Maybe the fact that these contacts are not visible and covered by the keyboard messes something up in the recycler view?

What will happen if you scroll down so that contact 6 and 8 are outside of the screen area and then scroll back to them? Sometimes a contact's picture is not displayed for me and it will be shown after scrolling away and back again.

**Comment by RiseT** [comment]
@FeuRenard Sorry, I forgot to mention dismissing of the keyboard.
On my phone it's exactly as on your phone, i. e. for the 5th contact, only the first couple of pixel rows are displayed. I'd say 90% of the 5th contact are covered by the keyboard. And of course 100% for contacts 6+.
After dismissing the keyboard, it looks like on the posted screenshots.

I will try scrolling down as soon as it happens the next time (won't take too long I guess).

**Comment by RiseT** [comment]
@FeuRenard Yep, you're correct. Scrolling the affected contacts off screen and back again fixes things.

Slightly off-topic: While testing this, I've noticed that when renaming a contact (from Android's address book), in Signal's contact list that contact is instantly displayed at the correct new first letter, but the name itself is only updated after refreshing the contact list (scrolling off screen etc doesn't help in this - most likely unrelated - case). Just an observation.

**Comment by scienmind** [comment]
Facing this issue as well, quite often (not 100%, but > 50%). The basic steps that usually reproduce it:
1. Open Signal
2. Tap "new message" (pencil icon)
3. Pull down to refresh
Result: after refresh, some contact "duplicate themselves" showing up in wrong places
(i.e. "Jane" shows up in a proper place alphabetically, AND instead of "Anna" as well)

Log: https://gist.github.com/anonymous/7ceed5cb4dcacfc28789be3f111aca18
Device: OnePlus 3T, OxygenOS 4.1.3 (Android 7.1.1)
Signal version: 4.5.3

**Comment by FeuRenard** [comment]
Did 99b2149deb184f73128f093a8ec58379b674b08f change something?

**Comment by RiseT** [comment]
Oops. I've somehow missed that commit. Will report back.

**Comment by RiseT** [comment]
Looks promising so far, haven't been able to reproduce. I guess I'll need a couple of days for the final verdict, though.

**Comment by jeremymasters** [comment]
This seems fixed for me in 4.11.2

**Comment by RiseT** [comment]
I'll close this for now as it appears to be fixed. If I or someone else sees this happening again, I'll reopen.
