### ISSUE TITLE
Creating images instead of ogward numbers

### ISSUE THREAD

**Issue by Peda1996** [WhisperSystems/Signal-Android#6489]
Hello,

![grafik](https://cloud.githubusercontent.com/assets/1789749/24629895/f06d1e2c-18ba-11e7-8ccc-eacb857f891c.png)

It would be nice, if anybody of the developer team could implement some gravatars (like in wordpress :P) instead of this ogward numbers, which are hard to compare.

Lg

**Comment by moxie0** [comment]
We're happy with the safety number format. It seems as if you've found the blog post, but here it is just the same: https://whispersystems.org/blog/safety-number-updates/

If you're referring to an auto-generated image for visual comparison instead of the QR code, it's fairly easy to make similar-looking images with different keys, so we consider them unsafe.
