### ISSUE TITLE
"Don't submit WIP PRs" is a bad contributor experience

### ISSUE THREAD

**Issue by strugee** [WhisperSystems/Signal-Android#6524]
https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#submit-only-complete-prs-and-test-them states that folks shouldn't submit work-in-progress PRs. That seems like a very bad idea to me. WIP PRs are very useful for answering questions like:

* Am I heading down the right direction with respect to this code's design?
* I implemented part of this change, if I finish the rest would it be accepted?
* I'm stuck with such-and-such an error, how can I solve it?
* I've made a change on this line but I'm not 100% sure it's correct, can someone confirm?

All of these questions have to go _somewhere_. It might as well be somewhere where it's easiest to answer - in a Pull Request where you have the full diff available to contextualize all discussion.

Does this requirement exist because people would submit incomplete PRs that made tests fail, etc.? In that case, I propose the text be amended to say something like "if submitting a Pull Request that's not ready for merging, prefix its title with `[WIP]`."

**Comment by moxie0** [comment]
Hey @strugee, the contribution guidelines are set up based on our capacities and needs.

> Am I heading down the right direction with respect to this code's design?

My preference is that new contributors start by submitting small PRs where most of the work goes into figuring out which 5 lines needed to be changed. Over time, contributors who do this seem to get a feel for the project, which directions make sense, and the overall design.

> I implemented part of this change, if I finish the rest would it be accepted?

My preference is that contributors get some certainty around the answer to this question before they even begin, either through addressing open issues or through discussion on the forums.

> I'm stuck with such-and-such an error, how can I solve it?
> I've made a change on this line but I'm not 100% sure it's correct, can someone confirm?

These are, unfortunately, problems that we can not help with.  I would love to be able to spend more time doing mentorship and providing feedback, but I can't. We need contributors to take on these challenges themselves. 

I am the only full-time contributor to this repository, what's most useful to me given my time constraints are PRs that are easier to review than to write myself. That is almost always going to be small contributions where the bulk of the work is in answering these very questions rather than in writing the actual code.
