### ISSUE TITLE
Emoji interpretation depends on emoji set pref

### ISSUE THREAD

**Issue by cascheberg** [WhisperSystems/Signal-Android#6640]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Different emoji settings potentially lead to different communication experiences for sender and receiver, see screenshots below for a random example. I suggest to remove the preference to use system emoji.

The screenshots below show the exact same message on the same phone.

**Actual result:** Emoji interpretaton depends on user pref
**Expected result:** Emoji depiction should essentially be identical

### Screenshots

![emojiset](https://cloud.githubusercontent.com/assets/3845150/26033430/a1ca2d70-38ac-11e7-8ebe-61a4d76aa3e7.png)
*Built-in emoji set*

![system](https://cloud.githubusercontent.com/assets/3845150/26033431/a3db6b2e-38ac-11e7-9028-7b4bbb8d6db6.png)
*System emoji set*

### Device info
**Android version:** Android 5.1.1
**Signal version:** 4.6.0

**Comment by rainerzufall** [comment]
On Marshmallow:
![on android 6](https://cloud.githubusercontent.com/assets/12666598/26033945/1060708e-38b5-11e7-9559-58501cf23a05.png)
**Device info**
Android version: Android 6.0.1
Signal version: 4.6.0

I agree Emoji depiction should essentially be identical. Maybe instead of removing the option to use system emoji completely, it could only be enabled for the Android version which can depict the most current emoji set Signal uses. Recently Signal updated to Unicode 9 / Emoji 4. AFAIK only Android 7 does support all of these, therefore system emoji could/should only be optional for Android 7.

**Comment by moxie0** [comment]
We started with built-in emoji only when we introduced emoji, but people feel very strongly about this, so we introduced the option to use the system emoji after much demand. I agree that it's not optimal, but I don't think I'm prepared to receive death threats over removing this option again. =(

**Comment by FeuRenard** [comment]
We could add a line of text to the description of the setting. Like "Your friends may not see the same emoji like you."

**Comment by fencepost-error** [comment]
Unfortunately this is still an issue today, and the change in #6659 was never made, the only text is "Disable Signal's built-in emoji support", no mention that this can break emojis.
