### ISSUE TITLE
Register button is broken

### ISSUE THREAD

**Issue by Paviluf** [WhisperSystems/Signal-Android#6649]
### Bug description
Register button is broken

### Steps to reproduce
Start the app for the first time (it's the register button of the first screen)

**Actual result:** 
Register button is a rounded white square

**Expected result:**
Register button is shown

### Screenshots
The screenshot doesn't work on that screen it seem. So here is a screen from internet with a working register button
![26934a_c55b769167ac45bdafc334b3936323d1 png_srz_255_452_85_22_0 50_1 20_0 00_png_srz](https://cloud.githubusercontent.com/assets/17159065/26083684/7fec4338-39d7-11e7-8355-72a41eb5911d.png)

### Device info
**Device:** Motorola Razr i
**Android version:** 4.4 (CM11)
**Signal version:** 4.5.3

### Link to debug log
Don't have one now but can provide it if needed.

**Comment by p4nci** [comment]
@Paviluf 
a) for "screenshot doesn't work" please see [Support page: Can I take a screenshot?](https://support.whispersystems.org/hc/en-us/articles/213191027-Can-I-take-a-screenshot-)
b) "Register button is a rounded white square" will be fixed with Signal v4.6.x (see https://github.com/WhisperSystems/Signal-Android/pull/6605)

**Comment by Paviluf** [comment]
Thanks !
