### ISSUE TITLE
No notifcations

### ISSUE THREAD

**Issue by erikstenhammar** [WhisperSystems/Signal-Android#6684]
I have:
- [ ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by erikstenhammar** [comment]
I'm using a OnePlus 3T and I can't seem to get notifications sometimes.
If the phone has been idling for some time then it just won't show any notifications.
Mostly, it won't show any notifications, but sometimes it will display that just fine.
I have no problems and can receive notifications from apps like WhatsApp, Wickr and Viber.
It seems like only Signal is having problems with notifications. It used to work flawlessly for several months until right after I updated Signal like a month ago.
I have read about similar problems among consumers regarding this issue and I'm now pretty sure the problem started right after a certain update.

Here is what I have tried:
I have tried to re-install Signal, re-register.
To make sure I didn't do anything wrong, I have also tried by resetting the phone to factory settings, with no luck.

**Comment by jeremymasters** [comment]
@erikstenhammar You should probably fill out the details in the intial post.  You also need a debug log right after the observed issue occurs.

**Comment by erikstenhammar** [comment]
The thing with submitting the debug log from my phone is that every time I open it up, there is not actual debug data, but only 6 lines of information always being the same:

Device: OnePLus ONEPLUS A3003 (OnePlus3)
Android: 7.1.1 (53, ONEPLUS A3003_28_170411)
Memory: 40M (12.21% free, 512M max)
Memclass: 256
OS Host: ubuntu-55
App: Signal 4.6.1

There is nothing more in the text-field than the above info, so I can't really see how that would be helpful.

**Comment by bme13** [comment]
I've noticed a similar behavior. Phone was idle during the night. This morning it did not show a notification however after opening Signal a notification popped up. Here's the debug log
https://gist.github.com/anonymous/71a48423dea28d2f707687e78fb6e5ab
Unlike the original description however most of the time notifications seems to work correct.

The message details show:
send 28 may 2017 09:40:28  CEST
received 28 may 2017 09:55:54 CEST
via data (Signal)
Also note there is no connected device configured.

**Comment by 2-4601** [comment]
Check out this support page: https://support.whispersystems.org/hc/en-us/articles/115005547088-Why-do-I-only-see-new-messages-when-I-open-Signal-Android-

**Comment by bme13** [comment]
@2-4601 Thanks for the response. I thought I checked that page before however just did that again. It appears only the priority mode was not on. I'll enable that. Samsung also has the smartmanager. In this app I did already disabled energy saving for Signal. So that should not be the problem. 
I thought most of the notification issues were about gcm not working correctly. In the debug log however that seems to work (although I don't have any experience in analyzing these kind of files so I might be totally wrong) From the logfile I see that after a lot of gcm messages the message is
Failed to download pending message!
Can that be explained by the priority setting or is there something more I can try?

**Comment by bme13** [comment]
@moxie0 not sure if it's ok to comment on a closed issue however I noticed that in a0e2361 the fix/workaround for this is postponed. I had a similar behavior yesterday and also this morning. In both cases however the debug log did not contain the timestamp of the send message due to the limited log buffer so I cannot be 100% sure that both events had the same root cause -although I assume so-. Is there a way to store specific messages longer or increase the log buffer?  I would like to be able to pinpoint this to one specific cause. Furthermore I was wondering if this could also be the cause for #6246 since I think that on the sending part the message is marked with one check. Also I can imagine that sending a new message will result in a new push notification and that results in flushing the previous message as well I assume.
