### ISSUE TITLE
[suggestion] Making signal server world readable

### ISSUE THREAD

**Issue by alice-roberts** [WhisperSystems/Signal-Android#6715]
I respect that Signal is trying to improve the state of secure communications and is designed in such a way as to minimize the amount of metadata available to Open Whisper Systems, but because it is not a federated protocol, all Signal users must trust that Open Whisper Systems is telling the truth. While we have no reason to doubt that, it would be better not to have to operate solely on trust. There should be no downside to making Signal's servers world-readable (except for API keys, of course) so that users can verify for themselves that all messages are encrypted and minimal metadata are stored.

**Comment by mawed** [comment]
https://signal.org/blog/the-ecosystem-is-moving/

**Comment by NinebitX** [comment]
You can verify that the contents of your messages and calls are end-to-end encrypted by comparing [safety numbers](https://whispersystems.org/blog/safety-number-updates/) with your contacts. No server-side code is involved in the end-to-end encryption of Signal messages or calls. The encryption and decryption is done entirely by the apps.  Anyone can verify this by looking at the source code:  
* https://github.com/WhisperSystems/Signal-Android 
* https://github.com/WhisperSystems/Signal-iOS 
* https://github.com/WhisperSystems/Signal-Desktop 

The only thing that is not protected from the server is the metadata. The Signal servers are able to see which number each Signal message or call is addressed to. However, the servers are designed so that this information is only kept as long as necessary in order to deliver the messages or place the calls. It is not stored on the Signal servers:
* https://whispersystems.org/signal/privacy/
* https://github.com/WhisperSystems/Signal-Server 

Correct me if I'm wrong, but Open Whisper Systems would have committed perjury if they had stored this kind of metadata and not handed it over when they were subpoenaed last year: 
* https://whispersystems.org/bigbrother/eastern-virginia-grand-jury/

If OWS made their servers world-readable, wouldn't that mean that _anyone_ could then be able to see which number each Signal message or call is addressed to? Wouldn't that then make it possible for _anyone_ to easily start collecting and storing the metadata that OWS have always had the ability to collect and store, but have chosen not to?

Here is a thought experiment: If OWS made everything about their servers world-readable _except_ the part that would let anyone in the world see which number each Signal message or call is addressed to, what would prevent OWS from making other parts of their servers non-world-readable? You would still need to trust that OWS does not collect and store the metadata that they say they do not collect and store. With that in mind, don't you think it's a bit pointless to ask OWS to make their servers world-readable?

At best, I don't think this would provide any assurances that we didn't already have, and at worst this would allow anyone in the world to create a database of Signal communications metadata.

**Comment by nrizzio** [comment]
Please take this discussion to the [community forum](https://whispersystems.discoursehosting.net/). The issue tracker is for bugs, and this issue is generating a lot of distracting noise.

**Comment by alice-roberts** [comment]
Thanks for the response, I am closing this issue and will relocate to the community forum once it is approved.
