### ISSUE TITLE
Can't use Signal without a smartphone.

### ISSUE THREAD

**Issue by hundertsieben** [WhisperSystems/Signal-Android#6781]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

### Bug description
I can't use Signal just with the desktop app, not having a smartphone.

-------------------

I could provide a mobile number, but using the desktop app without a smartphone that has a camera that is able to read a QR code is impossible. Why?

**Comment by NinebitX** [comment]
https://github.com/WhisperSystems/Signal-Desktop/blob/master/CONTRIBUTING.md#standalone-registration

**Comment by armata** [comment]
The problem is that the desktop app source uses the staging server and the Android app on Google Play uses the production server. That's why you're having issues with the QR code.

You either need to build a Android app that uses the staging server or change the server to production in the desktop app source.

You can also use the standalone registration feature as linked by @NinebitX

**Comment by Trolldemorted** [comment]
Or you can use the [inofficial signal-cli client](https://github.com/AsamK/signal-cli) as the master device, and link the desktops to it.

But to be honest, this is not a Signal-Android issue, but rather a question for the [mailing list](https://lists.riseup.net/www/arc/whispersystems/2014-07/msg00000.html), the [forum](https://whispersystems.discoursehosting.net/), or the [subreddit](https://www.reddit.com/r/signal/).
