### ISSUE TITLE
Unsubscribed users are not removed from groups

### ISSUE THREAD

**Issue by paride** [WhisperSystems/Signal-Android#6806]
### Steps to reproduce
- Have a member of a group unsubscribe from Signal
- Check how the now unsubscribed number is still part of the group
- Now the stale number is impossible to remove from the group. Sometimes re-registering is not an option, as access to the number might have been lost. Most of the time the user just doesn't care.

**Expected result:** The unsubscribed user is automatically removed from all the groups. I know the server is not aware of groups, but I think there are still ways to handle this. For example:

- When sending a message to a group (i.e., to all the group members), if a user is not a Signal user anymore, remove it;
- Before adding a user to a group because of a message coming from another group member, check if the number is actually a Signal number.

**Signal version:** 4.8.0

**Comment by nrizzio** [comment]
This is unfortunately technically infeasible with the current group architecture and was rejected in #828.

**Comment by paride** [comment]
@nrizzio How is my proposal incompatible with the current architecture? There's no need for a group administrator (what #828 is about).

**Comment by nrizzio** [comment]
My interpretation may very well be incorrect. In the interest of reducing notification spam, I'm going to take a step back and let Moxie make a determination when he gets around to it. Feel free to make a thread on the forum though.

**Comment by haffenloher** [comment]
> When sending a message to a group (i.e., to all the group members), if a user is not a Signal user anymore, remove it

That was the plan at some point (see https://github.com/WhisperSystems/Signal-Android/issues/5891#issuecomment-263163151), but Lilia and Moxie ended up deciding against it (see #6175).

**Comment by Trolldemorted** [comment]
@paride you cannot just remove a member from a group on your device without [things going terribly wrong](https://github.com/WhisperSystems/Signal-Android/pull/6175#issuecomment-279688603).

So far no one has come up with a scheme for removing group members in asynchronous egalitarian groups that is simple and works.

I had suggested a single source of truth-device which "owns" the group and is the only device capable of sending group updates, but apparently moxie did not like it (and neither did i tbh since it imposes severe limitations to the user).

I am all in for some brainstorming to devise a new groups scheme, but this is not the right place (unlike the [forum](https://whispersystems.discoursehosting.net) or the [subreddit](https://www.reddit.com/r/signal)).

@moxie0 i know you do not want the groups "to be on the server", but would storing an encrypted blob (to which the server does not have the key) be ok? I don't think there is a way to solve signal's group issues without an external instance  (read: not a signal device) deciding which async event came first.

**Comment by paride** [comment]
Duplicate of #6175.

(Still, the issue remains to be addressed.)
