### ISSUE TITLE
Weak APK signing key (RSA1024 / SHA1 Digest)

### ISSUE THREAD

**Issue by livmackintosh** [WhisperSystems/Signal-Android#6833]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal APK on website (and likely via Google Play store) is signed with cert that uses a RSA1024 key with SHA1 digest. Unsure if this is actually an issue as it seems likely that you would be aware already but since I couldn't find a prior issue I thought I should raise it.

My instinct tells me that changing to a >=2048bit key would break update functionality as the signing certificate digest is pinned in the app.

Better safe than sorry to raise this anyway,
Livvy

### Steps to reproduce
`jarsigner -verify -certs -verbose Signal-website-release-4.8.1.apk`

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
```
- Signed by "CN=Whisper Systems, OU=Research and Development, O=Whisper Systems, L=Pittsburgh, ST=PA, C=US"
    Digest algorithm: SHA1
    Signature algorithm: SHA1withRSA, 1024-bit key

jar verified.
```

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
Not necessarily a bug report so not necessarily an "expected" result but in an ideal world:
```
- Signed by "CN=Whisper Systems, OU=Research and Development, O=Whisper Systems, L=Pittsburgh, ST=PA, C=US"
    Digest algorithm: SHA1
    Signature algorithm: SHA256withRSA, 4096-bit key

jar verified.
```

### Device info

**Device:** N/A
**Android version:** N/A
**Signal version:** 4.8.1

**Comment by moxie0** [comment]
It's not possible to use larger signature algorithms with the versions of Android we support, and even for newer platforms, Android has no mechanism for migrating keys.

**Comment by thestinger** [comment]
FWIW, it seems that within the next year Android will support rotating to a stronger key for newer devices while still supporting older devices (APK Signature Scheme v3):

https://android-review.googlesource.com/c/platform/tools/apksig/+/589594/

@livmackintosh Raising it would currently require re-uploading with a new app id, and they'd still need to update the old API, so they'd end up permanently maintaining the app with both ids. I think it's best to wait.

**Comment by livmackintosh** [comment]
Nice observation @thestinger. I think this is a piece of tech/security debt that will get more costly with time. But as with anything, it seems to be all about balancing risk with other functional/technical concerns and restrictions. Hopefully this new signature scheme will make tackling the piece of work easier. Will wait and see what the outcome of the scheme is.

**Comment by thestinger** [comment]
Play Signing exists because developers losing their keys or having them compromised was a major issue and users on devices with privileged Google Play are already heavily trusting Google regardless. Users are trusting that they get the actual app from Google on first install too, and it's not as if people are verifying the key fingerprint in practice. Since Play Signing is mandatory for all new apps, that's simply the way things are now.

For GrapheneOS, we release our apps both in our own app repository with our own app repository client signed with our keys with the app repository metadata also versioned and signed with our keys. We also release our apps through the Play Store with a different app id: we add a `.play` suffix so that they're treated as separate from the ones we sign and release ourselves, so they don't conflict with each other and there isn't an attempt to update the app with the wrong updates. You can install app.attestation.auditor in one profile from our app repository and app.attestation.auditor.play in another, etc. We're entirely fine with this approach and we don't mind Play Signing. In fact, we got forced to cleanly split things this way by it and we're quite happy about the result compared to the Play Store and our app repository fighting over which gets to update the apps. Play Store will update apps it didn't install to the same version, which is important due to due to how split APKs work.

v2 signing is important because it makes the whole APK signed. It provides significant benefits over v1 where the whole APK isn't signed and therefore attacks can put data in parts of the zip. This proved to be an issue in practice. v3 signing is important for key rotation but the Play Store never started using it themselves. Instead, Play Signing has the option to rotate the key where new installs will use the new key but existing installs use what they already had. I don't know why they haven't started using v3 signing to upgrade the existing installs to the new key as long as they're on a version supporting it.

**Comment by thestinger** [comment]
> As I have already mentioned, you do not have to rotate the key. You can generate a second proper length (and potentially also algorithm) key and add a second signature with that key. You also do not need v2 or v3 code signing (but it does not hurt either) for this to work on the directly released APK.

v2 signing is mandatory for modern Android with modern API level, therefore it's mandatory as a whole since modern API level is mandatory for Play Store. You also can't just add another key. You need to do a key rotation with v3 signing and ancient Android versions (if supported) will continue using the v1/v2 signatures with the original key.

**Comment by thestinger** [comment]
Play Signing existed before app bundles and was already highly encouraged. Using your own keys was highly discouraged and triggered warnings. App bundles are an open source feature, as are split APKs, and they can be used without Play Signing. It's entirely possible to simply generate a set of split APKs on your own and the Play Store could have used those for even quite old Android devices. You're wrong about how this all works. There's no need to generate device-specific APKs for anything but ancient devices due to split APKs.

Devices using standard Google Play give it an immense amount of privileged access. Google Play provides builds of the AOSP mainline modules along with various core components of the OS being provided by Google Play components. Play services itself can back up / restore the vast majority of app data for apps targeting Android 12+ (device-to-device backups can't be disabled, and few apps provide device-to-device backup file exclusions since it's a new feature) and Play Store can uninstall/install apps without specific consent. A massive portion of the OS including the app runtime is provided via mainline modules. I don't know what you trust you think isn't placed in Google Play on devices with it.

**Comment by thestinger** [comment]
Our app repository supports split APKs. Split APKs have a base APK and you can split out architecture, locale, screen density, etc. Only the splits needed for the device are installed. This is how this works on any remotely modern Android device with the Play Store. It doesn't have to make a device-specific APK. Split APKs are generated from an app bundle with the open source bundletool. Play Store could have simply supported uploading split APKs with all supported archs, densities and locales. Features and assets can also be split out by the app developer, which is not an issue. Play Signing was not a requirement to do any of this. Play Signing was added due to developers not properly handling their keys along with the lack of key rotation on old Android devices.
