### ISSUE TITLE
All messages are failing to send

### ISSUE THREAD

**Issue by kairajohnson** [WhisperSystems/Signal-Android#6834]
I have:
- [x ] searched open and closed issues for duplicates
- [ ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

I cannot send any messages at all. I restarted my phone, checked other devices with signal that works, and found no understanding as to why I can't receive other than a potential bug.

### Steps to reproduce
- send a message
- received error stating "some issues need your attention"
- failed to send is in red
-tried other contacts and have the same issue 
 

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

- I push resend and get the same error

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

I should be able to send message 

### Device info

**Device:** Samsung on5
**Android version:** 6.0.1
**Signal version:** 4.5.3

### Link to debug log

https://gist.github.com/anonymous/801a0aa6e574537493619612be079c39

**Comment by moxie0** [comment]
Hey @kairajohnson, it looks like you're running version 4.5.3, which is 10 releases and 3 months old. That build has expired, so you'll have to update to a recent version in order to be able to send messages again. There should be a big banner in the conversation list that indicates your build is expired, and asks you to update.
