### ISSUE TITLE
Text Messages going to default text messaging app S7 Edge

### ISSUE THREAD

**Issue by usmarine2141** [WhisperSystems/Signal-Android#6877]
I have:
- [X ] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
Text Messages from non signal users going to default text messaging app S7 Edge t
(Submitted debug 
https://gist.github.com/588904edde836c3885935ab1b89bb078)

### Steps to reproduce
- sending message/ receiving message 

**Actual result: the message shows up in the default SMS app

**Expected result: messages not to show up in default sms app

### Device info

Device  : samsung SM-G935T (hero2qltetmo)
Android : 7.0 (G935TUVU4BQG5, NRD90M.G935TUVU4BQG5)
Memory  : 18M (25.77% free, 512M max)
Memclass: 256
OS Host : SWHE7723
App     : Signal 4.9.8

debug log - https://gist.github.com/anonymous/588904edde836c3885935ab1b89bb078

### Link to debug log
https://gist.github.com/anonymous/588904edde836c3885935ab1b89bb078

**Comment by johanw666** [comment]
Do they also show up in Signal? If not, did ypu make Signal the default sms app? If you didn't, they are expected to go to the standard sms app.

**Comment by usmarine2141** [comment]
Yes they show up in signal as well. Signal is set to my default sms app. 


![image](https://user-images.githubusercontent.com/20714147/29333002-bd0bf028-81c7-11e7-9364-7e92bd50ba41.png)

**Comment by johanw666** [comment]
Then the default sms app stores them as well. There is nothing that Signal can do to avoid that, sms messages are since Android 5 passed to all applications that have told Android they can handle sms messages. Signal behaves nicely - if it is not the standard sms app it will only process its own registration sms messages. But there is noone who can prevent another app with this setting from storing all incomming sms messages.
