### ISSUE TITLE
[Feature Request] Target Android API level 26

### ISSUE THREAD

**Issue by bkerensa** [WhisperSystems/Signal-Android#6900]
Please target Android API Level 26 so Signal will respect Background Execution Limits
https://developer.android.com/about/versions/oreo/background.html

**Comment by moxie0** [comment]
The Play version of Signal doesn't do any work in the background, other than an occasional (like once every 48hrs) periodic task which uses the system-appropriate scheduling, or a DB write in the execution window that we get following a GCM or SMS event. Whether or not Signal is targeting API level 26 should have no bearing on its background execution, since there is no background execution that I know of.

**Comment by bkerensa** [comment]
@moxie0 I disagree see Bug #6898 if Signal was targeting 26 whatever defect in your codebase that is causing Signal to drain in the background would not occur because Android 8.0's background limits would kick in and kill signal's excessive background drain.

The background limits in Android 8.0 only work if the app targets API Level 26.

I have submitted a PR to bump the SdkVersion of which you guys were targeting an unofficial Lollipop level? Why? https://github.com/WhisperSystems/Signal-Android/pull/6901

**Comment by moxie0** [comment]
If there is some kind of "defective" background execution, I would love to fix it, so let's start there. Any insight into background execution that you're seeing would be wonderful, but I'm not sure why there would be background execution on Android 8 and not Android 7.
