### ISSUE TITLE
Update Library Versions, Android Support Library and Android SDK Target Levels

### ISSUE THREAD

**Issue by bkerensa** [WhisperSystems/Signal-Android#6902]
1. Signal is targeting SDK 22 which is not even a final API level it is an MR1 for Lollipop
2. Support libraries are heavily behind latest versions
3. Third-Party libraries are heavily behind with many bugfixes upstream that would benefit Signal's stability and performance

**Comment by moxie0** [comment]
> Signal is targeting SDK 22 which is not even a final API level it is an MR1 for Lollipop

This is intentional, a lot of work would need to go into targeting higher API levels, and other tasks have had priority.

> Support libraries are heavily behind latest versions

We do not update libraries just to update them, stability is part of the beauty of versioned artifacts. In particular, we don't like to update play services dependencies since many users have trouble updating play services on their devices.

> Third-Party libraries are heavily behind with many bugfixes upstream that would benefit Signal's stability and performance

If there is a specific new version of a third party library that would address an open Signal issue, please let us know.
