### ISSUE TITLE
Since 4.10.X cannot send Signal message anymore due to missing MMS settings

### ISSUE THREAD

**Issue by mlsxlist** [WhisperSystems/Signal-Android#6954]
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Since 4.10.X when I try to send a Signal message (encrypted), Signal complains about missing MMS settings. I am sure that worked before with 4.9.9. Receiving messages does work. 

### Steps to reproduce
- Send a message to Signal contact. Signal shows a screen **Configure MMS settings**

**Actual result:** When I send a message to a Signal contact Signal shows a screen **Configure MMS settings**

**Expected result:** Even if my MMS settings are messed up, I would not expect that this prevents me from sending a Signal message (encrypted) to a contact.

### Screenshots
![screenshot_2017-09-10-10-34-27](https://user-images.githubusercontent.com/6071818/30259519-3b932206-96b1-11e7-9922-cb9598ee3358.png)

### Device info
**Device:** samsung GT-I9100
**Android version:** 4.4.4 cm_i9100-userdebug
**Signal version:** 4.10.7

### Link to debug log
Log does not contain any information apart from device information

**Comment by p4nci** [comment]
@mlsxlist related to https://github.com/WhisperSystems/Signal-Android/issues/6417 ?

**Comment by FeuRenard** [comment]
Thanks for reporting this, @mlsxlist ! I have the exact same issue on my Sony Xperia U with Android 4.4.4 (CyanogenMod). But I didn't think it was a general issue, as this phone is my testing device and runs CM.

To be clear: there is absolutely no Signal message sending possible due to this bug. Signal as SMS app on/off doesn't matter.

@p4nci I don't think there is a relation to #6417. This is on 4.4.4, #6417 on 5.0 (which handles MMS settings differently). This is a malfunction when sending a Signal message, #6417 affects actual MMS.
