### ISSUE TITLE
Group name and picture is missing in the lastest beta

### ISSUE THREAD

**Issue by KarolTrzeszczkowski** [WhisperSystems/Signal-Android#6962]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
I have a group called "rodzinka". Today I noticed that now it shows "No name group" (but in polish) and on other people phones in group everything is ok. Also I can't write anything in this group, keyboard doesn't show up.

### Steps to reproduce
I couldn't get that result another time. Maybe during update some info was lost?

**Actual result:** Shows "No name group" and you can't write in it.
**Expected result:** Shows the actual name of the group and you are able to write a message.

### Screenshots

![screenshot_20170913-112546](https://user-images.githubusercontent.com/11697819/30370929-53e4298a-9879-11e7-8edb-0b9b465955d4.png)
![screenshot_20170913-112553](https://user-images.githubusercontent.com/11697819/30370937-598e91d6-9879-11e7-85c5-ef08461a9747.png)

### Device info

**Device:** Meizu M2 Note 
**Android version:** Lineage OS 14.1, android 7.1.2 
**Signal version:** 4.10.8

### Link to debug log
https://gist.github.com/anonymous/c95901fcccc375d44adeac1fd48578b4

**Comment by lazlolazlolazlo** [comment]
Same symptoms, was added in group. Group showed up as Unnamed I can't write anything in this group. Running Signal 4.10.8 on Android 7.1.

![screenshot_20170913-151932](https://user-images.githubusercontent.com/601905/30379941-618be130-9898-11e7-9dd1-d320ab6628ae.png)
![screenshot_20170913-151926](https://user-images.githubusercontent.com/601905/30379940-6187ee9a-9898-11e7-8510-4cab7843c4d6.png)

**Comment by moxie0** [comment]
@KarolTrzeszczkowski It looks like there are only a few (very recent) messages to that group. Is it possible that this was a group you were a member of in a previous install of Signal, and have reinstalled since the group was created?

**Comment by KarolTrzeszczkowski** [comment]
Yes, this is exactly the case. I've installed android 7.1 two days ago so my signal is fresh. But I've uploaded backup and when I've noticed this problem there was no message history in this group thread. Then I deleted messages and ask group members to write to see if this was not just a lag. But it appeared the same way.

**Comment by FxRe** [comment]
I'm not quite sure, if I'm experiencing the same thing and this actually is a bug, or if it's a result of how information about groups (names, images) are saved and distributed.

I had to switch from Android to the iOS client and on iOS I no longer see the group names or images. To add to my confusion, after I connected the Windows Desktop Client with the iOS client, the information is visible there (presumably because it had been stored there previously).

So is this simply a result of the Signal server not knowing the group names and attached image? If so, then some sort of short "warning" or "explanation" should be provided by the client as soon as you re-register the device with your mobile number and it detects you're a part of groups. Ideal would be a safe way to restore the information by securely sharing it between, in my case, the Desktop Client and the iOS client (generally: if one of your clients has information that the other is missing, the information should be shared).

This is somewhat related to the ability to create encrypted backups on Android an iOS, where they are being saved in both cases, and being able to restore them, possibly cross-platform.
