### ISSUE TITLE
Should not ask to make profile visible to group as long as all members are in contacts

### ISSUE THREAD

**Issue by cascheberg** [WhisperSystems/Signal-Android#7027]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
In most of the groups all members are in my contacts already (e.g. close friends). I am never asked to make my profile visible to any of those users individually, because they are in my contacts. But now in those groups I am asked to do this explicitly. It would be nice if I would not see this banner as long as there are only contacts in this group.

### Steps to reproduce
- someone else creates a group where all members are already in your contacts

**Actual result:** Banner requests to make profile visible.
**Expected result:** I already made my profile visible to all group members individually (e.g. automatically), so the banner should not be there.

P.S.: The "contact verified" flag could also be used to decide that a profile should be made visible automatically.

### Device info
**Signal version:** 4.11.0

**Comment by moxie0** [comment]
In groups, we're asking permission for sharing profile info for all current *and* all future members. We don't want to assume that you're OK with that just because all existing members are contacts. We also don't want to wait until there are non-contacts in the group to ask, since that might be confusing, and also because we want users who are OK with it to have made that choice ahead of time so that new members can immediately get a view of who they're in a group with.
