### ISSUE TITLE
Description of keyboard incognito mode incorrect

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/Signal-Android#7037]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Incognito mode's description string currently says
*"Use keyboard without suggestions or auto-correct"*

When using Gboard in incognito mode, my keyboard *does* use a) suggestions and b) auto-correction.

A better description would be something like
*"If set to incognito mode, the keyboard won't remember, learn, or store any words you type"*

On a related note:
It seems like incognito mode is currently only used in conversation threads. What about Signal's other input fields like password, search, etc?

**Comment by FeuRenard** [comment]
Another suggestion:
"Request keyboard not to save/store your input/entered text"

**Comment by bitmold** [comment]
sorry to be posting on a closed issue.... i was thinking about using this API in another thing I was doing and was researching how to do it here +i wanted to say that the description @FeuRenard proposed is also incorrect for anyone considering this API in Signal or elsewhere since there's nothing forcing the keyboard implementation to respect that flag
