### ISSUE TITLE
Feature: Profile Pictures

### ISSUE THREAD

**Issue by fratzi** [WhisperSystems/Signal-Android#706]
A nice feature would be, if I could store a profile picture of myself inside the app.
The app downloads other profile pictures only, if both clients have each other in their address book and uses that stored picture, instead of the local one.
Most users don't have set up a google profile picture, so my address book is blank or they use iOS/Microsoft.

Privacy would be respected, because both must have exchanged at least their numbers.

**Comment by manhole11** [comment]
I feel like the lack of this feature has become even more evident with the new design. It's supposed to be fancy and colorful, but all my contacts look the same right now -- sad to say but they look pretty ugly. What's the problem? Is it because it's hard to implement having encryption in mind?

**Comment by Norbert80** [comment]
I am also missing the feature to be able to set a profile picture like in Telegram or in most other messengers.

**Comment by moxie0** [comment]
@Norbert80 please don't post in issues unless you have new information to add.

**Comment by oaim** [comment]
(I'm writing it here because it's older, but may I should have written it in #916 since moxie is assigned there)
Judging by the answers of the developers it's unclear: are profile pictures set by the users on the roadmap at all? I'm not asking when it will happen (though of course, the sooner the better), just wondering if the intention is to support them at some point.
Thanks

**Comment by mcginty** [comment]
If an issue's open that means it's considered a legitimate feature request.

**Comment by moxie0** [comment]
In 4.10.0
