### ISSUE TITLE
Importing issue to Signal Desktop

### ISSUE THREAD

**Issue by Julian2000nl** [WhisperSystems/Signal-Android#7175]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Signal Android does not properly sync up with Signal Desktop. This [issue was notified in the Desktop repo](https://github.com/WhisperSystems/Signal-Desktop/issues/1727#issuecomment-343634749) but after submitting error logs, it was determined the issue was on Android side.

### Steps to reproduce
- Set up Signal desktop, latest version on mobile and desktop
- Try to import contacts, chats & groups

**Actual result:** Signal Desktop is empty, no data is synced. New outgoing/incoming messages do come in/out, but the contact has no name. 
**Expected result:** Contacts, chats and groups will be imported to Signal Desktop.

### Device info

**Device:** Nexus 5
**Android version:** 7.1.2
**Signal version:** 4.12.3
**Desktop OS:** Ubuntu 17.10 GNOME
**Desktop Version:** 1.0.37

### Link to debug log

https://gist.github.com/Julian2000nl/4cc0c7ccdc6ce436deae4059c584aea6
Link to issue on Desktop repo: https://github.com/WhisperSystems/Signal-Desktop/issues/1727#issuecomment-343634749

**Comment by DanDev** [comment]
Same issue here.

Bug description

Unable to import contacts from Android to Win 10 Desktop. Note: I am using Signal with a Google Voice number rather than the SIM Card cell phone number on my Android device (in case this makes a difference).

Steps to reproduce

installed Android Signal (Samsung S8 with Android 7.0)
made Android Signal default phone and messaging app: it brought in all my contacts
installed Desktop Signal onto Windows 10 x64 (Enterprise 1703.15063.674) laptop
attempted to import contacts: only imported 2 (out of 271).
restarted both Android Phone and Windows Laptop.
restarted Signal on both
reattempted to import contacts on Desktop: still no joy
when texting using Android Signal, none show up on Desktop version
Actual result: Managed to import my own contact and one other in the Desktop version.
Expected result: All contacts and groups should import; text messages should appear in the Desktop version as they do the Android version.

Screenshots

Platform info

Operating System: Windows 10 x64 (Enterprise 1703.15063.674)
Browser: Chrome 62.0.3202.94 (Official Build) (64-bit)

Signal version: Win 10 Desktop v1.0.39

Link to debug log

Installed Chrome extension and the same exact behavior as above applied. Copying link from Chrome Extension debug log here (couldn't figure out how to do this from the standalone desktop version):
https://gist.github.com/b0849ce4735cc394c0ec9cbcf40e2bad
