### ISSUE TITLE
Connectivity error - Signal was unable to connect to the server

### ISSUE THREAD

**Issue by XiovV** [WhisperSystems/Signal-Android#7220]
I have Lineage OS 14.1 (Android 7.1.2) with microG and I have downloaded Signals apk from their website. I have enabled GCM in microG settings then Signal stops at "Registering with server..." and tells me that the connection has failed.

**Comment by moxie0** [comment]
Please don't delete the issue template. We can't do anything without a debug log, but chances are very likely that it's a problem with your microG install.

**Comment by githtz** [comment]
I've had the same problem, turned out I had 'Google device registration' disabled. Make sure to enable it in the microG settings.
I cleared the App data afterwards and tried to register again, and voila!

![img_20171126_165930](https://user-images.githubusercontent.com/15327800/33241809-6910130a-d2cb-11e7-9605-1a614bffa82d.jpg)
