### ISSUE TITLE
Group security: limit adding new contacts to existing members

### ISSUE THREAD

**Issue by mejo-** [WhisperSystems/Signal-Android#7346]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

This issue is about the recently published [paper regarding (flaws in) end-to-end security in Signal and other messengers](https://eprint.iacr.org/2017/713.pdf).

If I got it right, then the described vulnerability is as follows: The Signal client doesn't authenticate messages that add new members to a group. So if the Group ID (impossible to guess, but known to the server) and *one* group member are known to the attacker, then she can send a group joining message to this contact and gets joined without further authentication.

I'm aware of Moxies response [Here's how WhatsApp group messaging works](https://news.ycombinator.com/item?id=16117487) but I'm not aware of a public statement by any of the OpenWhispersystems/Signal developers regarding the evaluation of *Signal* group messaging by the paper.

My understanding is, that in Signal there would be a fairly easy fix for the described vulnerability: the Signal client could check whether the group joining request comes from an *existing* member of the group and deny the joining attempt if not.

Do you intend to implement this fix in Signal? If not, what's the rationale to not do so?

**Comment by Trolldemorted** [comment]
The group ID is not known to the server.

**Comment by p4nci** [comment]
@mejo- 
> Do you intend to implement this fix in Signal? If not, what's the rationale to not do so?

from that paper:
"We discussed this proposal with Open WhisperSystems, but it turned out that this verification is unfeasible due to their current implementation. Open WhisperSystems is currently developing a new group management system with advanced administrative features so that they decided not to apply our fix."

@Trolldemorted 
> The group ID is not known to the server.

I hope, this will NOT change with the new (currently in development) group management (see above). 
Fortunately Moxie wrote:
"I think it would be better if the server didn't have metadata visibility into group membership,..." (see [Here's how WhatsApp group messaging works](https://news.ycombinator.com/item?id=16117487)) 👍

**Comment by Trolldemorted** [comment]
Even if the server knows about group metadata , clients could still sign changes and validate those changes.

My biggest group contains 38 members at the moment, sending takes ages, client-side fan-out is not feasible.

**Comment by mejo-** [comment]
> The group ID is not known to the server.

Indeed, that was a misunderstand on my side. Thanks for clarification.

**Comment by moxie0** [comment]
Thanks everyone but please read the contributing guidelines before posting here again. We don't use GH issues for discussion or Q&A.
