### ISSUE TITLE
Add trust level indicator to conversation screen

### ISSUE THREAD

**Issue by virtualritz** [WhisperSystems/Signal-Android#910]
In #766 @lindworm suggested adding display of trust level with the other party to the conversation screen. This requires a separate issue from the aforementioned ticket.

There were different suggestions as to how this should be done.
- @lindworm suggested coloring the lock icon in the top bar (green = manually verified, black/yellow = unverified/automatic key exchange/, red = unencrypted).
- I suggested overlaying the other party's avatar with an icon instead. Icon indicates they're a manually verified contact. No icons means they're not.

Specifically I also suggested not mixing the information of whether a conversation is encrypted or not with the information of how well the other party is trusted, into one icon.
Least not by color. There are color vision impaired users and this information, if displayed at all, needs to be unambiguous.

**Comment by repat** [comment]
Is there any news on this discussion that I couldn't find in 400+ issues? ;)

My 2 cents:
It is now possible to verify the identity but TextSecure doesn't save the "verification status". My idea, like to many others before, would be to add that little verified icon (that skype, twitter, facebook etc use) next to the name. People that don't know about all of this would still think everything is fine and encrypted because of the closed lock-icon (TOFU, which should be the case) and tinfoil-hat users can use the manual verification, but don't have remember who they already verified and they don't have to re-verify, unless the key changes, in which case he would be notified anyway.
This would follow the principal, "Trust (as in TOFU) is good, control is better)", that you hear so often in Germany :P. For my mum trust is good enough, for mexican journalists or whatever it was, control would be better. As a person from a risk group I would rather not trust things I don't understand (like key exchange and delivery of the public key through the server) but trust WhisperSystems/the open source community here to implement/verifiy QR-Code verification correctly. We could help him by not making it too hard to remember who he verified before.

I don't know how group messages are implemented but they way I understood is that the group chat would only be verified if all the users are verified? Maybe this could be implemented in 2 stages, start with 1-on-1 conversations? Threema doesn't show this too btw, you can click on the group conversation users and the traffic light verification for each one of them but no sign for the group conversation itself.

**Comment by maquis** [comment]
Could someone from the developer team please comment whether there are any plans to implement trust level management in the near future (possibly as opt-in feature, if there are reservations that it might break the concept of simplicity and scare away users)? If you have several textsecure-contacts, it is difficult to memorize which ones have already been verified and which ones haven't. Also, it doesn't make much sense that the only truly open source and secure messaging app out there does not support users that wish to rely on true end-to-end-encryption rather than server-assisted "end-to-end" encryption that is always more prone to MITM attacks...

**Comment by mcginty** [comment]
@maquis trust management isn't in the near-future plans. There will be changes to how we encode fingerprints and possibly some trust indicators to show you've verified, but those aren't solidified and there are other higher-priority tasks compared to this.

**Comment by digineut** [comment]
+1 for a visual clue whether or not i have verified the identity of my contact. a checkmark next to the contact's icon is my preference.

**Comment by xmw** [comment]
+1 for any indication ...
