### ISSUE TITLE
Mark new/unread messages in conversation

### ISSUE THREAD

**Issue by jocelynthode** [WhisperSystems/Signal-Android#965]
In whatsapp, when you open a group chat for example, you see just above the new messages that were posted a little banner "New messages /unread messages". I find this feature really helpful to not be lost in a conversation.

**Comment by Stuie** [comment]
It looks like the problem here is that the `ThreadRecord` class only has a binary representation of whether a given conversation thread is "read" or not.

If this read state was persisted on `MessageRecord` instead (need to double-check that it's not already there) then it would be simpler to add in a header in the right place. It would also be possible to flag how many new messages are in a conversation on the `ConversationListActivity` instead of just making the message and date texts bold.

The work required is fairly significant.

1. Add a `read` flag to `MessageRecord` (DB update and schema change)
1. Remove `read` flag from `ThreadRecord` and add foreign key lookup for `MessageRecord`s where required (maintaining both may lead to bugs, but would also keep the query faster)
1. Implement a new header similar to the "Today" and "Yesterday" date headers that exist
1. Integrate the header with the `ConversationAdapter` to get the header in the right place

**Comment by FeuRenard** [comment]
Fixed by d9b42c4
