### ISSUE TITLE
[Suggestion] Allow arbitrary file types (txt, zip, apk, pdf ...) to be sent as attachments, not only audio/video/media

### ISSUE THREAD

**Issue by Wikinaut** [WhisperSystems/Signal-Android#993]
Currently, only media files (image, video, audio) can be selected as attachment, but I want also be able to send **text** and **zip** files via the Android Filemanager.

What was the original reason to limit attachments to media types?

[UPDATED 20151020]
#### Bounty for implementation

We have a bounty for the implementation, it's now at 

[![Bounty](https://www.bountysource.com/badge/issue?issue_id=1464832)](https://www.bountysource.com/issues/1464832-suggestion-allow-arbitrary-file-types-txt-zip-apk-pdf-to-be-sent-as-attachments-not-only-audio-video-media)

Click, if you want to support. Bitcoin payment is supported.

**Comment by fabrig** [comment]
As there has not been any update for more than half a year, I'd like to join this request.

Please allow sending for arbitrary file types! This would make Textsecure an even more valuable tool!

**Comment by Wikinaut** [comment]
I would like to know whether this is still on the to-do list (allow arbitrary file types as attachments).

**Comment by alex42ka** [comment]
Would be really great being able to send PDF encrypted to my TextSecure-contacts. 
The headmaster of our school wanted to recommend TextSecure to the teachers and students as open replacement for existing nonsecure communication. He has stopped this for instance because he wanted to send a PDF which didn't work.

**Comment by fantasia45** [comment]
Can we still hope that it will be possible to send arbitrary files with TextSecure from our tablets and phones?

**Comment by Wikinaut** [comment]
I anyone working on a solution ? (info only: the new version of Threema can send files up to 20 MB, see http://www.heise.de/newsticker/meldung/Krypto-Messenger-Neue-Threema-Version-bietet-Dateiversand-2750001.html )

**Comment by moxie0** [comment]
God damn @Wikinaut how many times do we have to ask you not to bump threads. Please respect our time.

**Comment by alex42ka** [comment]
Opened a bounty on bountysource for this:

https://www.bountysource.com/issues/1464832-suggestion-allow-arbitrary-file-types-txt-zip-apk-pdf-to-be-sent-as-attachments-not-only-audio-video-media

**Comment by Wikinaut** [comment]
Great! I sent some mBTC.

**Comment by Wikinaut** [comment]
Now at <img src="https://www.bountysource.com/badge/issue?issue_id=1464832">

**Comment by JasperWeiss** [comment]
I'd like to extend this to all file types.
But I can imagine this would take up a massive amount of storage on your servers at some point.

Therefore, an option would be to limit it to a certain size. But I might have a cooler idea. What I've you could link a cloud storage account (like whatsapp does with google drive for backups) that is automatically used for sharing large files securely.
I'd imagine signal encrypting the file, upload it to your chosen cloud storage and then get a public link and send that to the recipient. Which can then download and decrypt it again. 
Fortunately most providers have a nice api so it shouldn't be extremely hard to make.

**Comment by Evi1M4chine** [comment]
There is absolutely no reason for size limitations btw.
Any file can by transferred segment by segment, allowing segments to be below any limit, and retransmission of segments in case of failure.

The transfers should of course exclusively happen in a direct, serverless way. Nobody expects 2GB file transfers to happen unless both people are online. Segmentation takes care of the usual connection/transfer errors, resuming, etc. When it’s done, the user simply gets a message, and the phone resumes saving power.

**Comment by shobhitg** [comment]
I like the connected storage idea as an option. That also adds another feature to incoming/outgoing have media backed up automatically (based on retention settings within the app).

**Comment by wizdom13** [comment]
@Wikinaut @moxie0 Good news guys! My fork as Signal Plus added this option along with others useful options.
Play Store: https://play.google.com/store/apps/details?id=org.privatechats.securesms
Source:      https://github.com/wizdom13/SignalPlus-Android

**Comment by cxarmonato** [comment]
@wizdom13 that is awesome!! I'm downloading it right now. If I like it, I'll force all my friends to make the switch :) It won't be hard since I see that you have custome backgrounds and that's what they've been asking for since forever lol Thank you!

**Comment by cxarmonato** [comment]
I can't believe the kind of CENSORSHIP that is going on here!! Someone posted a comment about a client they'd built and their comment has been removed. (apparently their client is better, uh?) Here is the client: https://play.google.com/store/apps/details?id=org.privatechats.securesms

**Comment by cxarmonato** [comment]
ATTENTION EVERYONE: the developers at whispersystems are CENSORING comments about forks like https://play.google.com/store/apps/details?id=org.privatechats.securesms
This is NOT the way FOSS works. For your safety stop using their apps!

**Comment by JasperWeiss** [comment]
@ghost For the security of their users, the devs don't want people advertising unofficial forks of signal on their website/gitub page. That said, removing comments is not really something I'd call professional. 

> For your safety stop using their apps!

This has nothing to do with safety. Signal is no less secure just because the devs happen to remove links to unofficial (possibly insecure) forks.

**Comment by Wikinaut** [comment]
@ghost perhaps you can send a formal PR (pull request) of your patch?

**Comment by Evi1M4chine** [comment]
@JasperWeiss: Sorry, “safety” is and has always been the number one bullshit lie to do evil things. That shit don’t fly anymore.

And Moxie is well-known for his… to put it mildly… strange behavior.
<small>(I’ll just quickly reminding you of all the bugs that have been closed with childish nonsense “reasons” like “not feeling it”. And generally his treatment of others. [Regarding /that: I understand, _but I don’t agree_.])</small>

Your code is not one bit more trustworthy to somebody than the other one’s, until one has personally read and checked every single bit of logic and data in there.

@JasperWeiss: But anyone who employs censorship of any kind… (aka “moderation”, on websites) …is not to be trusted. It is _the_ trust killer.

@Wikinaut: It’s not healthy to try to suck up to somebody who’s clearly treating you badly. A fork has been extremely long overdue anyway, due to the gaping lack of features that should be standard by now. (Not only because Moxie doesn’t have the time, but again because he actively rejects it and even kills the bugs with aforementioned nonsense reasoning.)

@ghost: Telegram is the [FSB](https://en.wikipedia.org/wiki/Federal_Security_Service)’s little bitch. The security features are mere theater. Like putting a safe door on a tent. You could as well just use WhatsApp. Signal is the only client that actually gets it right. (And the EFF’s list is just silly if you actually think about it.) You can think about Moxie what you want, but this he gets 100% right.

Conclusion: I shall fork too, and sync my patches with whomever wants them. But I shall be my own master branch, and not depend on any of that human-shaped cancer. Goodbye.

**Comment by WoZaoNi** [comment]
@Evi1M4chine Eigenlijk, moet jij gewoon je bek houden. 你他媽的 Chupa mi dollor.
https://www.youtube.com/watch?v=j7l8sLGTEFA

> It’s not healthy to try to suck up

~ Evi1M4chine

@Ghost Supreme leader

**Comment by Evi1M4chine** [comment]
@WoZaoNi: The sand box is over there, kid → http://www.thesun.co.uk/

**Comment by WoZaoNi** [comment]
@Evi1M4chine Why I need sandbox? In china, the air has plenty of sand.

**Comment by JasperWeiss** [comment]
@WoZaoNi Could you please not spam this github page Mr Zao.
